### PR TITLE
issue 508 JSCore response format updates - Swift side

### LINKED ISSUE #508: refactor Core response from string to string + byte array
after https://github.com/FlowCrypt/flowcrypt-ios/issues/507

currently, when we call a method in Core, for example here: https://github.com/FlowCrypt/flowcrypt-ios/blob/6367703c35bfe3df860573e8b2b8b0393b64a545/FlowCrypt/Core/Core.swift#L47

```swift
    func version() throws -> CoreRes.Version {
        let r = try call("version", jsonDict: nil, data: nil)
        return try r.json.decodeJson(as: CoreRes.Version.self)
    }
```

it will call into javascript eg here:

```ts
  public version = async (): Promise<Buffers> => {
    return fmtRes({ app_version: VERSION });
  }
```

The `fmtRes` method formats a resulting JSON + optional data into a single string. After we dropped Android support and HTTP server support, there is no point in doing this. We can instead return an object like `{json:string, data: Uint8Array}` which Swift's `JavaScriptCore` can load directly instead of parsing it.

Here's the `fmtRes` implementation:

```ts
export const fmtRes = (response: {}, data?: Buf | Uint8Array): Buffers => {
  const buffers: Buffers = [];
  buffers.push(Buf.fromUtfStr(JSON.stringify(response)));
  buffers.push(Buf.fromUtfStr('\n'));
  if (data) {
    buffers.push(data);
  }
  return buffers;
}
``` 

I suppose it should change to something like this:

```ts
type EndpointRes = {json: strring, data: Buf | Uint8Array};

export const fmtRes = (response: {}, data?: Buf | Uint8Array): EndpointRes => {
  return {
    json: JSON.stringify(response)),
    data: data || new Uint8Array(0)
  }
}
``` 

Therefore the endpoints almost don't need to change:

```ts
  public version = async (): Promise<EndpointRes> => {
    return fmtRes({ app_version: VERSION });
  }
```

Then similarly, we should no longer try to parse it on Swift side. Currently done here: https://github.com/FlowCrypt/flowcrypt-ios/blob/6367703c35bfe3df860573e8b2b8b0393b64a545/FlowCrypt/Core/Core.swift#L198

Something like this:

```diff
    private func call(_ endpoint: String, jsonData: Data, data: Data) throws -> RawRes {
        try blockUntilReadyOrThrow()
        cb_last_value = nil
        jsEndpointListener!.call(withArguments: [endpoint, String(data: jsonData, encoding: .utf8)!, data.base64EncodedString(), cb_catcher!])
-       let b64response = cb_last_value![0] as! String
-       let rawResponse = Data(base64Encoded: b64response)!
-       let separatorIndex = rawResponse.firstIndex(of: 10)!
-       let resJsonData = Data(rawResponse[...(separatorIndex - 1)])
+       // now somehow access the object from Swift 
+       let resObject = cb_last_value![0] as! Dict<any> // pseudo code
+       let resJsonData = Data(resObject["json"] as! String) // pseudo code
+       let resBytesData = Data(resObject["data"] as! [Uint8]) // pseudo code
        let error = try? resJsonData.decodeJson(as: CoreRes.Error.self)
        if let error = error {
            let errMsg = "------ js err -------\nCore \(endpoint):\n\(error.error.message)\n\(error.error.stack ?? "no stack")\n------- end js err -----"
            logger.logError(errMsg)
            
            throw CoreError.init(coreError: error) ?? CoreError.exception(errMsg)
        }
-        return RawRes(json: resJsonData, data: Data(rawResponse[(separatorIndex + 1)...]))
+        return RawRes(json: resJsonData, data: Data(resBytesData)
    }
```

### PR DESCRIPTION
**Pull request by tomholub**
This is a draft PR - I've only checked in master and run `cd Core && npm run-script deploy` which updated the javascript resource in iOS app. This will break the app, and I'll be assigning this PR to be finished on the Swift side, as per #508 

this will eventually close #508

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes) - once existing tests pass, we are good

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Core/Core.swift [hunk 1]
```diff
@@ -171,8 +171,6 @@ final class Core: KeyDecrypter, CoreComposeMessageType {
                 self.context!.evaluateScript(jsFileSrc)
                 self.jsEndpointListener = self.context!.objectForKeyedSubscript("handleRequestFromHost")
                 self.cb_catcher = self.context!.objectForKeyedSubscript("engine_host_cb_value_formatter")
-                let cb_last_value_filler: @convention(block) ([NSObject]) -> Void = { values in self.cb_last_value = values }
-                self.context!.setObject(unsafeBitCast(cb_last_value_filler, to: AnyObject.self), forKeyedSubscript: "engine_host_cb_catcher" as (NSCopying & NSObjectProtocol)?)
```
Comment (tomholub) [inline FlowCrypt/Core/Core.swift:175]: You managed to remove this mess - that looks good too.

**Review by tomholub — COMMENTED** [review]
You're on a good track. If some tests started failing, please debug them. Looks to me this is viable.

**Comment by ivan-ushakov** [comment]
Now all unit tests from `FlowCryptAppTests` are green but I'm not sure about correct error handling. You have different approaches to errors passing from JavaScript code to Swift.

For example you have general error result for any exception, like this:
```
export const fmtErr = (e: any): EndpointRes => {
  return fmtRes({
    error: {
      message: String(e),
      stack: e && typeof e === 'object' ? e.stack || '' : ''
    }
  });
}

global.handleRequestFromHost = (endpointName: string, request: string, data: string, cb: (response: EndpointRes) => void): void => {
  try {
    const handler = endpoints[endpointName];
    if (!handler) {
      cb(fmtErr(new Error(`Unknown endpoint: ${endpointName}`)));
    } else {
      handler(JSON.parse(request), [Buf.fromBase64Str(data)])
        .then(res => cb(res))
        .catch(err => cb(fmtErr(err)));
    }
  } catch (err) {
    cb(fmtErr(err));
  }
};
```

On the other hand you have errors inside decrypt methods like this:
```
return { success: false, error: { type: DecryptErrTypes.keyMismatch, message: 'Missing appropriate key' }, message: prepared.message, longids, isEncrypted };
```

And in current unit tests I need to map some `DecryptErrTypes` errors to `CoreError` types.

File: FlowCrypt/Core/Core.swift [hunk 2]
```diff
@@ -60,6 +60,11 @@ final class Core: KeyDecrypter, CoreComposeMessageType {
 
     func decryptKey(armoredPrv: String, passphrase: String) throws -> CoreRes.DecryptKey {
         let r = try call("decryptKey", jsonDict: ["armored": armoredPrv, "passphrases": [passphrase]], data: nil)
+
+        if let error = try? r.json.decodeJson(as: CoreRes.Error.self) {
+            throw CoreError.exception(error.error.message)
+        }
```
Comment (tomholub) [inline FlowCrypt/Core/Core.swift:66]: Can there be a generic one in `_call` like before? All of these errors have a consistent format `{"error": {"message": ".", "stack": "..."}}`. The original `_call` error handling was generic and had logging done too which is important.

The system there should be generic but flexible enough so that you could get finer grained errors out of it for individual methods, but only when needed. Elese you have to add the same error handlers / guards into every method here which is worse.

**Comment by tomholub** [comment]
> Now all unit tests from `FlowCryptAppTests` are green but I'm not sure about correct error handling. You have different approaches to errors passing from JavaScript code to Swift.
> 
> For example you have general error result for any exception, like this:
> 
> ```
> export const fmtErr = (e: any): EndpointRes => {
>   return fmtRes({
>     error: {
>       message: String(e),
>       stack: e && typeof e === 'object' ? e.stack || '' : ''
>     }
>   });
> }
> 
> global.handleRequestFromHost = (endpointName: string, request: string, data: string, cb: (response: EndpointRes) => void): void => {
>   try {
>     const handler = endpoints[endpointName];
>     if (!handler) {
>       cb(fmtErr(new Error(`Unknown endpoint: ${endpointName}`)));
>     } else {
>       handler(JSON.parse(request), [Buf.fromBase64Str(data)])
>         .then(res => cb(res))
>         .catch(err => cb(fmtErr(err)));
>     }
>   } catch (err) {
>     cb(fmtErr(err));
>   }
> };
> ```
> 
> On the other hand you have errors inside decrypt methods like this:
> 
> ```
> return { success: false, error: { type: DecryptErrTypes.keyMismatch, message: 'Missing appropriate key' }, message: prepared.message, longids, isEncrypted };
> ```
> 
> And in current unit tests I need to map some `DecryptErrTypes` errors to `CoreError` types.

I see - I would put one generic error handler into `_call` which has a `message`, optional `stack` and then the full json (either directly or as a generic Dict).
That means all methods except for `parseDecryptMsg` and `decryptFile` don't need further error handling in them.

But in these two, you could add additional error handling that parses the json (or evaluates the Dict) to choose to raise a more appropriate error.

would that make sense?

If not, then you'd have to put an error handler in each method, which is less ideal.

**Comment by tomholub** [comment]
Alternatively if you want, you could have one huge error handler in _call that discerns all of these errors including the decrypt errors into their appropriate swift counterparts, and then no more error handling in any of these methods. That would also be ok with me.

File: FlowCrypt/Core/Core.swift (hunk 2 above)
Comment (ivan-ushakov) [reply FlowCrypt/Core/Core.swift]: Yes you are right. I was thinking that you need to have strong typing like you have in `MsgBlock.DecryptErr.ErrorType`. Now I see that `CoreRes.Error` has `type` parameter too.

File: FlowCrypt/Core/Core.swift [hunk 3]
```diff
@@ -211,18 +213,22 @@ final class Core: KeyDecrypter, CoreComposeMessageType {
...
-        let separatorIndex = rawResponse.firstIndex(of: 10)!
-        let resJsonData = Data(rawResponse[...(separatorIndex - 1)])
+        guard
+            let resJsonData = cb_last_value?.0.data(using: .utf8),
+            let rawResponse = cb_last_value?.1
+        else {
+            throw CoreError.format("JavaScript callback response not available")
+        }
+
         let error = try? resJsonData.decodeJson(as: CoreRes.Error.self)
```
Comment (ivan-ushakov) [inline FlowCrypt/Core/Core.swift:223]: Now we have the same error handler for all methods in JavaScript.

Comment (tomholub) [reply FlowCrypt/Core/Core.swift:223]: Yes but test are failing - please have a look further.

Comment (tomholub) [reply FlowCrypt/Core/Core.swift:223]: added - try now

Comment (ivan-ushakov) [reply FlowCrypt/Core/Core.swift:223]: I forgot to add `FlowCrypt/Resources/flowcrypt-ios-prod.js.txt` because I was thinking you generate it from sources

Comment (tomholub) [reply FlowCrypt/Core/Core.swift:223]: Sorry about that - we don't have an automated process for that yet, for now it has to be manually updated with `npm run-script deploy` and checked into the repo.

Once we auto-generate it from sources during build, we'll definitely gitignore it, to avoid confusion.

**Comment by tomholub** [comment]
@ivan-ushakov do you think this is ready to merge? If yes, then you can mark it ready for review.

**Comment by ivan-ushakov** [comment]
Who could be added as reviewer here?

**Comment by tomholub** [comment]
I'll review it myself, and force-merge if good.

**Review by tomholub — COMMENTED** [review]
LGTM

**Comment by tomholub** [comment]
@ivan-ushakov well done - good to see we don't have to pass it as a base64 string it after all.
