### PR TITLE
Time units are wrong in the API call logs

### LINKED ISSUE #838: time units are wrong in the API call logs
```
"ℹ️[URLSession] URLSession.asyncCall status:200 ms:0.485 ms GET https://flowcrypt.com/.well-known/openpgpkey/policy, headers: [:]"
```

should say 

```
"ℹ️[URLSession] URLSession.asyncCall status:200 ms:485 GET https://flowcrypt.com/.well-known/openpgpkey/policy, headers: [:]"
```

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #838

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCryptCommon/Trace.swift [hunk 1]
```diff
@@ -6,23 +6,22 @@
...
 
 public final class Trace {
     private let id: String
-    private var startTime: CFAbsoluteTime?
+    private var startTime: TimeInterval?
 
     public init(id: String) {
         self.id = id
-        self.startTime = CFAbsoluteTimeGetCurrent()
+        self.startTime = CACurrentMediaTime()
```
Comment (ivan-ushakov) [inline FlowCryptCommon/Trace.swift:17]: This should give monotonic time

File: FlowCrypt/Extensions/URLSessionExtension.swift [hunk 2]
```diff
@@ -44,16 +52,6 @@ extension URLSession {
             }.resume()
         }
     }
-
-    func call(_ urlStr: String, tolerateStatus: [Int]? = nil) -> Promise<HttpRes> {
```
Comment (ivan-ushakov) [inline FlowCrypt/Extensions/URLSessionExtension.swift:48]: Unused code removed

**Review by tomholub — APPROVED** [review]
