### PR TITLE
#2675 Fix: duplicated signature after draft save issue

### LINKED ISSUE #2675: Duplicated signature after draft save
- open encrypted email thread
- tap `Reply`
- enter some text
- click `Back` button, to save draft and go back to email thread
- wait until draft appears in the messages list
- tap on it
- draft compose screen appears and it has duplicated signature, like this:

Image

### PR DESCRIPTION
**Pull request by ioanatflowcrypt**
This PR fixed duplicated signature after draft save issue

close #2675 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift [hunk 1]
```diff
@@ -160,8 +160,17 @@ extension ComposeViewController {
...
-        if let signature = getSignature(), !mutableString.string.replacingOccurrences(of: "\r", with: "").contains(signature) {
-            mutableString.append(signature.attributed(.regular(17)))
+        if let signatureRaw = getSignature() {
+            let body = mutableString.string.replacingOccurrences(of: "\r\n", with: "\n")
+                .replacingOccurrences(of: "\r", with: "\n")
+                .trimmingCharacters(in: .whitespacesAndNewlines)
+            let signature = signatureRaw.replacingOccurrences(of: "\r\n", with: "\n")
+                .replacingOccurrences(of: "\r", with: "\n")
+                .trimmingCharacters(in: .whitespacesAndNewlines)
+            let alreadyEndsWithSig = body.contains(signature)
```
Comment (sosnovsky) [inline FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift:170]: it works well for plain signatures, but fails for html signatures (they're still duplicated). to reproduce it, you can try to use multi-line signature with bold font:

Best **regards**,
Roma

Comment (ioanatflowcrypt) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift:170]: Hmm.... Couldn't reproduce this issue. 
I tried both plain and html message and also tried html (multi line signature with bold font)and plain signatures.

Comment (ioanatflowcrypt) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift:170]: Maybe some other problems or because of cache?
Could you check again?

Comment (ioanatflowcrypt) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift:170]: @sosnovsky In case you missed this message

Comment (ioanatflowcrypt) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Nodes.swift]: Thank you for your info. I was able to produce this issue too.
Fixed it. Please check

**Review by sosnovsky — APPROVED** [review]
works well now, thanks!
