### PR TITLE
Use throwing var methods for realm references to other objects

### LINKED ISSUE #1035: use throwing var methods for realm references to other objects
> @tomholub ability to throw from `var` variable was added to the Swift recently:
> 
> ```swift
> var activeUser: UserRealmObject {
>     get throws {
>         guard let user = user else { throw AppErr... }
>         return user
>     }
>   }
> ```

This looks good. Probably for another issue/PR?

The advantage is that an exception can be captured and handled (in the general error handling somewhere in VC, wherever user action was initiated) while a forced unwrap cannot.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1030#issuecomment-972716809_

### LINKED ISSUE #1174: global router -> switch active user: error handling
I'll file an issue for this

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762540652_

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #1035
close #1174

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift [hunk 1]
```diff
@@ -222,7 +222,7 @@ extension ThreadDetailsViewController {
                 input[index].rawMessage = updatedMessage
                 node.reloadSections(IndexSet(integer: index), with: .fade)
             } catch {
-                showToast("Could not mark message as read: \(error)")
+                showToast("Could not mark message as read: \(error.localizedDescription)")
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift:225]: Localisation?

File: FlowCrypt/Functionality/Services/Folders Services/FoldersService.swift [hunk 2]
```diff
@@ -53,18 +53,22 @@ final class FoldersService: FoldersServiceType {
         let fetchedFolders = try await self.remoteFoldersProvider.fetchFolders()
         return try await withCheckedThrowingContinuation { continuation in
             DispatchQueue.main.async {
-                // TODO: - Ticket? - instead of removing all folders remove only
-                // those folders which are in DB and not in remoteFolders
-                self.localFoldersProvider.removeFolders(for: user.email)
+                do {
+                    // TODO: - Ticket? - instead of removing all folders remove only
+                    // those folders which are in DB and not in remoteFolders
+                    try self.localFoldersProvider.removeFolders(for: user.email)
```
Comment (ivan-ushakov) [inline FlowCrypt/Functionality/Services/Folders Services/FoldersService.swift:59]: @tomholub
Maybe you need this transactional? Now this are independent DB changes.

File: FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift [hunk 3]
```diff
@@ -70,7 +70,8 @@ extension KeyInfoRealmObject {
 
 extension KeyInfoRealmObject {
     /// associated user email
-    var account: String? {
-        user?.email
+    var account: String {
+        guard let email = user?.email else { fatalError() }
```
Comment (ivan-ushakov) [inline FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift:74]: I'm not sure it is good to use `throws` here because having such error already makes app wrong. So it is better to guaranty that we always have `user` property when we create/update object.

**Comment by ivan-ushakov** [comment]
Looks like this PR is more about removing `EncryptedCacheService` and changing `try?` to `try`.

File: FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift [hunk 4]
```diff
@@ -22,6 +22,8 @@ protocol EncryptedStorageType {
     func putKeypairs(keyDetails: [KeyDetails], passPhrase: String?, source: KeySource, for email: String)
     func getKeypairs(by email: String) -> [KeyInfo]
 
+    func find(with email: String) -> Recipient?
```
Comment (ivan-ushakov) [inline FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift:25]: Maybe `getRecipient`?

File: FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift [hunk 5]
```diff
@@ -8,66 +8,73 @@
...
 
 extension LocalContactsProvider: LocalContactsProviderType {
-    func updateLastUsedDate(for email: String) {
-        let recipient = find(with: email)
+    func retrievePubKeys(for email: String) -> [String] {
+        guard let object = find(with: email) else { return [] }
 
-        try? localContactsCache.realm.write {
-            recipient?.lastUsed = Date()
+        do {
```
Comment (ivan-ushakov) [inline FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift:41]: I don't throw here because problem with updating timestamp does not mean we don't have public keys.

File: FlowCrypt/Functionality/Services/Folders Services/FoldersService.swift (hunk 2 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/Folders Services/FoldersService.swift:59]: Maybe, you can use your judgement

File: FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift (hunk 3 above)
Comment (tomholub) [reply FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift:74]: Sure, assuming our own code in the future will never be buggy. Would you bet your neck on that? I wouldn't :-)

File: FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift (hunk 4 above)
Comment (tomholub) [reply FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift:25]: agree

File: FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift (hunk 5 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift:41]: I'd throw either way - it's a good habit.

File: FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift (hunk 1 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift:225]: can be spelled both ways

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift:225]: I mean do we need to move this to our localisation file?

File: FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift (hunk 4 above)
Comment (ivan-ushakov) [reply FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift]: This one not needed anymore

File: FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift [hunk 6]
```diff
@@ -10,16 +10,15 @@ import FlowCryptCommon
 import RealmSwift
 import UIKit
 
-// swiftlint:disable force_try
```
Comment (ivan-ushakov) [inline FlowCrypt/Functionality/DataManager/Encrypted Storage/EncryptedStorage.swift:13]: Now all methods with `try` are throwing so we don't need this hint anymore

File: FlowCrypt/Resources/en.lproj/Localizable.strings [hunk 7]
```diff
@@ -160,8 +160,11 @@
 
 // Contacts
 "contacts_screen_title" = "Contacts";
+"contacs_screen_load_error" = "Failed to load recipients: %@";
```
Comment (ivan-ushakov) [inline FlowCrypt/Resources/en.lproj/Localizable.strings:163]: `contacts`

File: FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+//  FlowCrypt
+//
+//  Created by  Ivan Ushakov on 05.12.2021
+//  Copyright © 2017-present FlowCrypt a. s. All rights reserved.
+//
+
+import FlowCryptUI
+import AsyncDisplayKit
+
+final class FatalErrorViewController: TableNodeViewController {
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift:12]: This one is for cases when it is not possible to continue using app and you have to restart it

File: FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift (hunk 1 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift]: I see. Sure - that never hurts.

File: FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactDetailViewController.swift [hunk 9]
```diff
@@ -91,7 +91,11 @@ extension ContactDetailViewController {
 
         recipient.remove(pubKey: keyToRemove)
         if let fingerprint = keyToRemove.fingerprint, fingerprint.isNotEmpty {
-            contactsProvider.removePubKey(with: fingerprint, for: recipient.email)
+            do {
+                try contactsProvider.removePubKey(with: fingerprint, for: recipient.email)
+            } catch {
+                showToast("contact_detail_remove_public_key_error".localizeWithArguments(error.localizedDescription))
+            }
         }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Settings/Contacts/Contacts List/ContactDetailViewController.swift:99]: This should be made a transaction in storage (can be another PR later) else it produces inconsistent results.

File: FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift [hunk 10]
```diff
@@ -228,41 +228,41 @@ extension SetupManuallyEnterPassPhraseViewController {
...
-            newKeysToAdd
+            try newKeysToAdd
                 .map {
                     PassPhrase(value: passPhrase, fingerprintsOfAssociatedKey: $0.fingerprints)
                 }
                 .forEach {
-                    appContext.passPhraseService.savePassPhrase(with: $0, storageMethod: storageMethod)
+                    try appContext.passPhraseService.savePassPhrase(with: $0, storageMethod: storageMethod)
                 }
         }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift:267]: I'd like to ban `forEach` in this codebase. Let's instead use`for thing in things {`, in this case `for newKeyToAdd in newKeysToAdd {`. I'll make another issue, to do this across the codebase.

File: FlowCrypt/Functionality/Services/Folders Services/LocalFoldersProvider.swift [hunk 11]
```diff
@@ -11,27 +11,45 @@ import RealmSwift
...
     }
+}
 
+extension LocalFoldersProvider: LocalFoldersProviderType {
     func fetchFolders(for userEmail: String) -> [FolderViewModel] {
-        return folderCache.getAll(for: userEmail).compactMap(FolderViewModel.init)
+        storage.objects(FolderRealmObject.self).where {
+            $0.user.email == userEmail
+        }.compactMap(FolderViewModel.init)
     }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Folders Services/LocalFoldersProvider.swift:35]: I prefer to see explicit returns - maybe there is some linter for this? That would be nice.

File: FlowCrypt/Functionality/Services/GlobalRouter.swift [hunk 12]
```diff
@@ -123,11 +126,15 @@ extension GlobalRouter: GlobalRouterType {
...
-            return
+        do {
+            guard let session = try appContext.userAccountService.switchActiveSessionFor(user: user) else {
+                logger.logWarning("Can't switch active user with \(user.email)")
+                return
+            }
+            proceed(with: appContext.withSession(session))
+        } catch {
+            // TODO
         }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/GlobalRouter.swift:137]: I'll file an issue for this

File: FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift [hunk 13]
```diff
@@ -62,12 +62,10 @@ extension ContactsService: ContactsProviderType {
...
-        return publicKeys
+        return localContactsProvider.retrievePubKeys(for: email)
     }
 
-    func removePubKey(with fingerprint: String, for email: String) {
-        localContactsProvider.removePubKey(with: fingerprint, for: email)
+    func removePubKey(with fingerprint: String, for email: String) throws {
+        try localContactsProvider.removePubKey(with: fingerprint, for: email)
     }
 }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift:71]: Useless methods, Let's delete then, and use `localContactsProvider` directly

File: FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift [hunk 14]
```diff
@@ -46,12 +46,12 @@ extension ContactsService: ContactsProviderType {
...
-            localContactsProvider.save(recipient: recipient)
+            try localContactsProvider.save(recipient: recipient)
             return recipient
         }
 
         let recipient = try await pubLookup.lookup(email: email)
-        localContactsProvider.updateKeys(for: recipient)
+        try localContactsProvider.updateKeys(for: recipient)
         return contact
     }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift:56]: We could find a new home for this method, and then delete `ContactsService`.

File: FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift [hunk 15]
```diff
@@ -8,66 +8,77 @@
...
+            try storage.write {
+                object.lastUsed = Date()
+            }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Local Pub Key Services/LocalContactsProvider.swift:48]: For another issue - need to review usage. Just because a public key is retrieved doesn't mean that we should update lastUsed. lastUsed should only be updated when user explicitly uses the recipient, like writing a message to them.

File: FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift (hunk 3 above)
Comment (tomholub) [reply FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift:74]: Still prefer throws here rather than `fatalError`.

File: FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift (hunk 8 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift:12]: This is very similar to the other error screen we have. It should be the same screen and same VC, with a boolean init parameter to offer to reset storage or not.

**Review by tomholub — APPROVED** [review]

**Review by tomholub — CHANGES_REQUESTED** [review]
I meant "request changes". I'll file a bunch of these issues for later, but some remain.

File: FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift (hunk 3 above)
Comment (ivan-ushakov) [reply FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift:74]: It makes code hard to use. We use this property in select queries, and having all such method throws will make code verbose.

File: FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift (hunk 8 above)
Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift:12]: It is strange to have universal controller with all possible error handling logic.

**Comment by tomholub** [comment]
Btw it's a great improvement overall 👍

**Comment by tomholub** [comment]
Please also have a look at:
 - https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762541426
 - https://github.com/FlowCrypt/flowcrypt-ios/pull/1165#discussion_r762541537

File: FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift (hunk 3 above)
Comment (tomholub) [reply FlowCrypt/Models/Realm Models/KeyInfoRealmObject.swift:74]: I'd still like to look into this in the future. Will file another issue.

File: FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift (hunk 8 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Bootstrap/FatalErrorViewController.swift:12]: It's not strange to me. A "fatal error" kind of page will always look about the same, no matter the underlying problem. Sometimes it will have a button and sometimes not. But they are very similar, aren't they? I'll file another issue.
