### PR TITLE
Reply to message on Gmail was wrongly not in the same thread

### LINKED ISSUE #492: reply to message on Gmail was wrongly not in the same thread
In my case, the following happened. I didn't try to reproduce it again.

1) I received a plain message
2) I replied to the plain message from iOS app (encrypted)
3) the resulting message was received on the other end (on Gmail)

expected: the reply should have been attached to the same thread

actual: Gmail regarded the reply as the first message of a new thread

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #492

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Core/CoreTypes.swift [hunk 1]
```diff
@@ -139,6 +139,7 @@ struct SendableMsg: Equatable {
     let replyToMimeMsg: String?
     let atts: [Attachment]
     let pubKeys: [String]?
+    let threadId: String?
```
Comment (tomholub) [inline FlowCrypt/Core/CoreTypes.swift:142]: I don't think this one needs it. It would only be meaningful if the TS code received and used it on the other end, which afaik it doesn't.

Comment (tomholub) [reply FlowCrypt/Core/CoreTypes.swift:142]: please try that - it would be confusing to have this be passed into composeEmail where it's not used

Comment (ivan-ushakov) [reply FlowCrypt/Core/CoreTypes.swift]: `threadId` added as argument

**Comment by ivan-ushakov** [comment]
Looks like `iOS Tests` failed because of timeout/interruption.

**Comment by tomholub** [comment]
You can try to re-run them if that's the case, in the SemaphoreCI pipeline ui.
