### PR TITLE
#1405 Fix cc recipients not respected issue

### LINKED ISSUE #1405: Cc/Bcc recipients are not respected on reply-all
to reproduce:

1) open a message that has cc or bcc recipients in it. In my case, it was `to:me,cc:many people`. It could also be `from:me,to:somebody,cc:others,bcc:the rest` for example.
2) tap reply all
3) the message I'm composing now is `to:original sender` but it's missing all the cc.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed cc recipients not respected issue when user choose to `Reply All`.

close #1405 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 1]
```diff
@@ -334,6 +334,16 @@ extension ComposeViewController {
             contextToSend.add(recipient: recipient)
             evaluate(recipient: recipient)
         }
+
+        input.quoteCCRecipients.forEach { email in
+            let recipient = ComposeMessageRecipient(email: email, type: .cc, state: decorator.recipientIdleState)
+            contextToSend.add(recipient: recipient)
+            evaluate(recipient: recipient)
+        }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:342]: Looking at the code, please try the following scenario (in Gmail app for reference, and then also in FlowCrypt app)

1) send and email `to:A` `bcc:B`
2) open sent email. It should show `to:A` `bcc:B` (I think? since you are the sender, you should see this)
3) reply to that email

expected result (in Gmail - please confirm, in which case also in FlowCrypt): the reply will be initiated as `to:A`, `bcc:B`

Comment (ioanmo226) [reply FlowCrypt/Controllers/Compose/ComposeViewController.swift:342]: Well, IMO bcc should not appear in reply.
image

As you can see from below, `reply all` button is not even there when there are only bcc recipients 
image

Comment (tomholub) [reply FlowCrypt/Controllers/Compose/ComposeViewController.swift:342]: thank you

**Review by tomholub — APPROVED** [review]
👍

**Comment by tomholub** [comment]
Filing a separate issue to write a test for this issue #1405 / PR #1407 . The UI test should:

1) navigate to a message that has both `to:` and `cc:` (some already existing, don't add one during test. Or add one manually to the test account if there isn't any already present, then during test expect it to be already present)
2) tap reply all
3) verify cc included

**Comment by ioanmo226** [comment]
Ok, got it
