### PR TITLE
issues 948 950 960 fix inbox conversations data

### LINKED ISSUE #948: Gmail provider error: the request timed out
I'm getting these relatively frequently in inbox lately.

What is the timeout on these requests? maybe it can be adjusted

Alternatively, are there many requests being called when loading inbox? Or is it one single request?

### LINKED ISSUE #950: certain inbox items are missing after the conversations update
I went to an email that was from:me to:me and I replied to it from the iOS app. Then I went to sent messages, and could not find it. Also could not find it in inbox in the app.

But I could easily find it in both browser webmail and previous version of the iOS app without threads.

However, I was not able to reproduce it on another conversation following the steps above (also tried replying to already archived message). So while I can observe it on one particular conversation anytime, I don't know how to reproduce this for other conversations.

### LINKED ISSUE #960: wrong date on thread inbox items
shows date of first message, should be date of last message

### PR DESCRIPTION
**Pull request by tomholub**
This PR:
 - close #960 - was date of first msg instead of last
 - close #948 - reduced concurrency
 - close #950 - just wrong ordering
 - renames various vars and methods for clarity

`for try await result in taskGroup` seems to execute in order that the tasks finish, not necessarily in the order in which the `taskGroup` array was defined. Instead of using an array to collect results, using a dict by id now, which is then converted to array in expected order.

When the order is kept correct that way, `.sort()` is no longer needed on the result. The sort was broken anyway, sorting by first message in thread. 

----------------------------------

**Tests**:
 - tests will be added in https://github.com/FlowCrypt/flowcrypt-ios/issues/959

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift [hunk 1]
```diff
@@ -276,7 +276,7 @@ extension InboxViewController {
         if input.data.isEmpty {
             state = .empty
         } else {
-            inboxInput = input.data.sorted()
+            inboxInput = input.data
```
Comment (tomholub) [inline FlowCrypt/Controllers/Inbox/InboxViewController.swift:279]: The fix is here

File: FlowCrypt/Controllers/Inbox/InboxRenderable.swift [hunk 2]
```diff
@@ -56,23 +50,19 @@ extension InboxRenderable {
...
-
         self.title = sender
         self.messageCount = thread.messages.count
         self.subtitle = thread.subject ?? "message_missed_subject".localized
-
-        if let date = thread.messages.first?.date {
+        self.isRead = !thread.messages
+            .map(\.isMessageRead)
+            .contains(false)
+        let date = thread.messages.last?.date
```
Comment (tomholub) [inline FlowCrypt/Controllers/Inbox/InboxRenderable.swift:59]: The fix is here

File: FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift [hunk 3]
```diff
@@ -25,20 +24,21 @@ extension GmailService: MessagesThreadProvider {
...
                 }
             }
             for try await result in taskGroup {
-                messages.append(result)
+                if let id = result.identifier {
+                    messageThreadsById[id] = result
+                }
             }
-
+            let messageThreads = requests.compactMap { messageThreadsById[$0.0] }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift:39]: The fix is here

**Review by sosnovsky — APPROVED** [review]
Works good 👍
