### PR TITLE
#954 add cc and bcc recipients

### LINKED ISSUE #954: adding cc and bcc recipients
currently missing on compose screen

### LINKED ISSUE #1352: UI tests failing on Semaphore
UI tests are failing on Semaphore with error

```bash
ios-sim start --devicetypeid com.apple.CoreSimulator.SimDeviceType.iPhone-13 Failed in 
00:02
385.   SyntaxError: Unexpected token u in JSON at position 0 00:02
386    at JSON.parse (<anonymous>) 00:02
387    at Object.list (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/node_modules/simctl/simctl.js:171:33) 00:02
388    at getDeviceFromDeviceTypeId (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/src/helpers.js:196:21) 00:02
389    at StartCommand.run (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/src/commands/start.js:10:20) 00:02
390    at StartCommand._run (/Users/semaphore/.nvm/versions/node/v16.13.2/lib/node_modules/ios-sim/node_modules/@oclif/command/lib/command.js:43:31) 00:02
391    TypeError: Cannot read properties of undefined (reading 'devicetypes')
```

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR adds cc and bcc recipients on compose screen

close #954
close #1352 

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated - updated `CheckComposeEmailAfterReopening` test

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by sosnovsky** [comment]
@tomholub here is video of current implementation of `cc/bcc recipients` feature:
https://user-images.githubusercontent.com/1062093/154237676-1e0f1bed-d6de-4633-974e-c8cfab1fe350.mp4

**Comment by tomholub** [comment]
Looks good so far :+1:

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 1]
```diff
@@ -724,46 +764,94 @@ extension ComposeViewController {
...
+        switch type {
+        case .to:
+            self.calculatedRecipientsToPartHeight = layoutHeight
+        case .cc:
+            self.calculatedRecipientsCcPartHeight = layoutHeight
+        case .bcc:
+            self.calculatedRecipientsBccPartHeight = layoutHeight
+        }
+    }
+
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:826]: There's quite a bit of rendering or layouting code now in this VC, which makes business logic less obvious. Would it make sense to move it into some sort of decorator or rendering file (specific for this VC) instead of being here? Could be another PR, more of a maintenance task.

**Review by tomholub — COMMENTED** [review]
Code looks good. I'll test run it now

**Review by tomholub — APPROVED** [review]
I'll approve and merge this but it needs improvement.

First: Cc/Bcc recipients are not respected on reply-all. To reproduce:

1) open a message that has cc or bcc recipients in it. In my case, it was `to:me,cc:many people`. It could also be `from:me,to:somebody,cc:others,bcc:the rest` for example.
2) tap reply all
3) the message I'm composing now is `to:original sender` but it's missing all the cc.

Second: The UI is disorderly. Let's follow what Gmail app does more closely - they do it well:
 - instead of `Add Recipient` placeholder, let's put `To` label to the left of the input that stays there
 - Similarly for cc and bcc when we expand it. Add `cc` and `bcc` to the left as labels
 - Let's auto-collapse all of this, only showing the email bubbles, when switches to subject or body (lost focus)
 - Let's re-expand the recipient area when user taps on the collapsed rendering

This way, we no longer need to have `Add Recipient`, `Add cc Recipient`, `Add bcc recipient` placeholders which take up a lot of space, each occupying own line. When user adds a few recipients, it quickly overwhelms my small screen (12 mini) whereas on Gmail app, it's comfortable.
