### PR TITLE
issue 404 remove Promises

### LINKED ISSUE #404: Replace Promise with async/await
continuation of https://github.com/FlowCrypt/flowcrypt-ios/issues/290

similarly how was done in https://github.com/FlowCrypt/flowcrypt-ios/pull/400 and #590

possibly after https://github.com/FlowCrypt/flowcrypt-ios/issues/402

It should not be one big PR. When possible, it would be better to make several PRs to change the app chunk by chunk. That way errors are less likely to slip in during refactoring, and also to prevent merge conflicts.

### LINKED ISSUE #981: MenuBarScreen.clickMenuIcon not always open menu
```
[iPhone Simulator iOS 15.0 #0-1] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts
[iPhone Simulator iOS 15.0 #0-1] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-1] Session ID: aaaeab87-e4aa-4285-b98d-af3a229328c5
[iPhone Simulator iOS 15.0 #0-1]
[iPhone Simulator iOS 15.0 #0-1] COMPOSE EMAIL: 
[iPhone Simulator iOS 15.0 #0-1]    ✖ user is able to select recipient from contact list using contact name
[iPhone Simulator iOS 15.0 #0-1]
[iPhone Simulator iOS 15.0 #0-1] 1 failing (57.6s)
[iPhone Simulator iOS 15.0 #0-1]
[iPhone Simulator iOS 15.0 #0-1] 1) COMPOSE EMAIL:  user is able to select recipient from contact list using contact name
[iPhone Simulator iOS 15.0 #0-1] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-1] Error: element ("~e2e.enterprise.test@flowcrypt.com") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-1]     at MenuBarScreen.checkUserEmail (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/menu-bar.screen.ts:39:21)
[iPhone Simulator iOS 15.0 #0-1]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts:29:23)
```

Sometimes it works fine, sometimes I have to manually click menu icon during the test

### PR DESCRIPTION
**Pull request by tomholub**
This PR removes remaining Promise usage, particularly in IMAP class.

**The SMTP/IMAP functionality is likely broken after this change. IMAP/SMTP is currently low-value feature with very few (if any) users using it. I'll file another issue to test and fix it, and after that, we'll write some UI tests for it to ensure it remains stable.**

close #404
close #981

Also stabilized opening menu in appium, and used a shorter pass phrase for appium tests so that less time is wasted typing long pass phrase during tests.

----------------------------------

**Tests**:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift [hunk 1]
```diff
@@ -56,42 +60,38 @@ extension Imap: BackupProvider {
...
-                    encoding: part.encoding
-                )
-                .start(self.finalize("fetchMsgAtt", resolve, reject, retry: {
-                    self.fetchMsgAttachment(in: folder, msgUid: msgUid, part: part)
-                }))
-        }
+    // todo - this is likely a duplicate of another method on Imap class
+    private func fetchMsgAttachment(in folder: String, msgUid: UInt32, part: MCOIMAPPart) async throws -> Data {
+        try await execute("fetchMsgAttachment", { sess, respond in
+            sess.fetchMessageAttachmentOperation(
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift:88]: Todo in another issue - see if we have two methods that use `sess.fetchMessageAttachmentOperation`

File: FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift [hunk 2]
```diff
@@ -7,117 +7,118 @@
 //
 
 import Foundation
-import Promises
+import MailCore
 
 extension Imap {
-    func finalize<T>(
+
+    func executeVoid(
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift:14]: `execute` and `executeVoid` could probably be united somehow. But my attempt was ugly. Could do in another issue.

File: FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift [hunk 3]
```diff
@@ -7,117 +7,118 @@
...
+    ) async throws {
+        guard let imapSess = self.imapSess else {
+            throw ImapError.noSession
+        }
+        do {
+            try await asAsync(imapSess, voidExecutor)
+            // todo - log time
+            return
+        } catch {
+            // todo - log error + time
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift:26]: Todo in future PR - log op name, error execution times, results etc

File: FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift [hunk 4]
```diff
@@ -7,117 +7,118 @@
...
+            return true
+        case .connection:
+            // the connection has dropped, so it's probably ok to not officially "close" it. but maybe there could be a cleaner way to dispose of the connection?
+            imapSess = nil
+            smtpSess = nil
+            // this is a mess, neads a real refactor. use DI
+            // todo - for now renewing of session disabled, will probably break retries
+//            setupSession()
+//            await connectImap(session: imapSessNotNil)
             return true
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Imap/Imap+retry.swift:119]: Todo - this is likely completely broken and will need a fix. But not in this PR.

Also, `setupSession` and `connectImap` and `connectSmpt` all need complete refactoring.

File: FlowCrypt/Functionality/Services/GoogleUserService.swift [hunk 5]
```diff
@@ -70,66 +70,55 @@ extension GoogleUserService: UserServiceType {
...
+                    continuation.resume(throwing: error)
                 } else {
                     fatalError("Shouldn't happe because covered received non nil error and non nil authState")
                 }
             }
-
-            self.appDelegate?.googleAuthSession = googleAuthSession
+            DispatchQueue.main.sync { // because of MainActor. Wrong?
+                appDelegate?.googleAuthSession = googleAuthSession
+            }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/GoogleUserService.swift:114]: looks ok? using .sync

File: FlowCrypt/Functionality/Services/GoogleUserService.swift [hunk 6]
```diff
@@ -70,66 +70,55 @@ extension GoogleUserService: UserServiceType {
...
         }
     }
 
     func signOut(user email: String) {
-        appDelegate?.googleAuthSession = nil
+        DispatchQueue.main.sync { // because of MainActor. Wrong?
+            appDelegate?.googleAuthSession = nil
+        }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/GoogleUserService.swift:121]: Looks ok? using .sync

**Comment by tomholub** [comment]
This removes Promises. @ivan-ushakov could you share feedback? I could have overlooked something.

File: FlowCrypt/Functionality/Services/GoogleUserService.swift (hunk 6 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/GoogleUserService.swift]: changed to .async, works better

File: FlowCrypt/Functionality/Services/GoogleUserService.swift (hunk 5 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/GoogleUserService.swift]: changed to .async, refactored

**Review by tomholub — COMMENTED** [review]
app works again now. checking tests
// swift tests are happy, at least locally

**Comment by sosnovsky** [comment]
Looks massive :) 

Screenshot 2021-11-11 at 13 53 08

**Comment by tomholub** [comment]
got one failing appium test:

```
[iPhone 13 iOS 15.0 #0-1] Spec: /Users/semaphore/git/flowcrypt-ios/appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts 18:04
[iPhone 13 iOS 15.0 #0-1] Running: iPhone 13 on iOS 15.0 executing /Users/semaphore/git/flowcrypt-ios/appium/FlowCrypt.app 18:04
[iPhone 13 iOS 15.0 #0-1] Session ID: 4da8bec1-0319-446b-b268-383fe7471ee6 18:04
[iPhone 13 iOS 15.0 #0-1] 18:04
[iPhone 13 iOS 15.0 #0-1] COMPOSE EMAIL: 18:04
[iPhone 13 iOS 15.0 #0-1]    ✖ user is able to select recipient from contact list using contact name 18:04
[iPhone 13 iOS 15.0 #0-1] 18:04
[iPhone 13 iOS 15.0 #0-1] 1 failing (1m 18.4s) 18:04
[iPhone 13 iOS 15.0 #0-1] 18:04
[iPhone 13 iOS 15.0 #0-1] 1) COMPOSE EMAIL:  user is able to select recipient from contact list using contact name 18:04
[iPhone 13 iOS 15.0 #0-1] Error: element ("~Inbox") still not displayed after 15000ms 18:04
[iPhone 13 iOS 15.0 #0-1] Error: element ("~Inbox") still not displayed after 15000ms 18:04
[iPhone 13 iOS 15.0 #0-1]     at processTicksAndRejections (internal/process/task_queues.js:97:5) 18:04
[iPhone 13 iOS 15.0 #0-1]     at Function.waitAndClick (/Users/semaphore/git/flowcrypt-ios/appium/tests/helpers/ElementHelper.ts:49:17) 18:04
[iPhone 13 iOS 15.0 #0-1]     at MenuBarScreen.clickInboxButton (/Users/semaphore/git/flowcrypt-ios/appium/tests/screenobjects/menu-bar.screen.ts:56:23) 18:04
[iPhone 13 iOS 15.0 #0-1]     at UserContext.<anonymous> (/Users/semaphore/git/flowcrypt-ios/appium/tests/specs/composeEmail/SelectRecipientByName.spec.ts:42:23)
```

will check

File: FlowCrypt/Functionality/Services/GoogleUserService.swift [hunk 7]
```diff
@@ -164,46 +157,26 @@ extension GoogleUserService {
         return GTMAppAuthFetcherAuthorization(fromKeychainForName: Constants.index + email)
     }
 
+    // todo - isn't this call supported by Google client library?
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Services/GoogleUserService.swift:160]: Google library supports this request - https://github.com/google/google-api-objectivec-client-for-rest/blob/main/Source/GeneratedServices/Oauth2/GTLROauth2Query.m#L46

The only difference is that it uses `oauth2/v2/userinfo` instead of `oauth2/v3/userinfo`, but response looks similar.

File: FlowCrypt/Functionality/Services/GoogleUserService.swift [hunk 8]
```diff
@@ -164,46 +157,26 @@ extension GoogleUserService {
...
-            logger.logError("Authorization error during token refresh, clearing state. \(error)")
-            if let email = currentUserEmail {
+        do {
+            let data = try await fetcherService.fetcher(with: url).beginFetch()
+            return try JSONDecoder().decode(GoogleUser.self, from: data)
+        } catch {
+            let isTokenErr = (error as NSError).isEqual(OIDOAuthTokenErrorDomain)
+            if isTokenErr, let email = self.currentUserEmail {
+                self.logger.logError("Authorization error during token refresh, clearing state. \(error)")
+                // todo - what exactly does this do and why?
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Services/GoogleUserService.swift:176]: It removes any authorisation information which was stored in Keychain, the same happens on logout.
So if any error happens during token refresh then user will be signed out automatically.

File: FlowCrypt/Functionality/Services/GoogleUserService.swift [hunk 9]
```diff
@@ -70,67 +69,61 @@ extension GoogleUserService: UserServiceType {
...
                         }
+                        return
                     }
-                } else if let error = error {
-                    reject(error)
-                } else {
-                    fatalError("Shouldn't happe because covered received non nil error and non nil authState")
+                    return continuation.resume(throwing: error ?? AppErr.unexpected("Shouldn't happen because covered received non nil error and non nil authState"))
+                }
+                DispatchQueue.main.async {
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Services/GoogleUserService.swift:98]: It's `DispatchQueue.main.async` inside `DispatchQueue.main.async`, probably should work with just parent one.

**Review by sosnovsky — APPROVED** [review]

File: FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift [hunk 10]
```diff
@@ -58,13 +58,18 @@ final class InboxViewContainerController: TableNodeViewController {
...
+            do {
+                let folders = try await folderService.fetchFolders(isForceReload: true)
+                DispatchQueue.main.async {
+                    self.handleFetched(folders: folders)
+                }
+            } catch {
+                DispatchQueue.main.async {
+                    self.state = .error(error)
+                }
             }
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift:71]: Thanks! Will do.

File: FlowCrypt/Functionality/Mail Provider/Imap/Imap+Other.swift [hunk 11]
```diff
@@ -8,50 +8,33 @@
...
+        let kind = self.messageKindProvider.imapMessagesRequestKind
+        guard uids.count() > 0 else {
+            self.logger.logError("Empty messages fetched")
+            // attempting to fetch an empty set of uids would cause IMAP error
+            return []
         }
+        return try await fetchMessage(in: folder, kind: kind, uids: uids)
     }
 
     func fetchMessage(
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Functionality/Mail Provider/Imap/Imap+Other.swift:27]: 👍

File: FlowCrypt/Functionality/Services/GoogleUserService.swift (hunk 7 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/GoogleUserService.swift:160]: 👍 will file another issue, see if we can use that - for consistency

**Comment by tomholub** [comment]
(small) regression:
 - menu items (folders) now take visibly longer to load
 - it says `INBOX` instead of `Inbox` etc (had to adjust appium test for it)
Will file another issue.

File: FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift (hunk 10 above)
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Inbox/Container/InboxViewContainerController.swift:71]: Alright - that's really convenient 👍

File: FlowCrypt/Functionality/Services/GoogleUserService.swift (hunk 9 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/GoogleUserService.swift:98]: Well spotted 👍

**Comment by tomholub** [comment]
@sosnovsky you're good at reviews - the PR isn't small and you found clear ways to improve it. Updated, hopefully appium tests should pass now (they pass locally)

**Comment by sosnovsky** [comment]
> @sosnovsky you're good at reviews - the PR isn't small and you found clear ways to improve it. Updated, hopefully appium tests should pass now (they pass locally)

Thanks Tom :) It's easier to find possible improvements when there are 50 files with changes than in some small PRs

Also for `@MainActor` I left comment only in 1 file, but we can create separate issue for it, as there are other places where it can help us to avoid running some functions on wrong thread. For example we can wrap `showToast`, `handleError` with `@MainActor` so we won't need to check if it's on main thread or not.

**Review by tomholub — COMMENTED** [review]
.

**Review by sosnovsky — APPROVED** [review]

File: FlowCrypt/Controllers/Msg/MessageActionsHandler.swift [hunk 12]
```diff
@@ -30,10 +30,17 @@ extension MessageActionsHandler where Self: UIViewController {
     }
 
     func setupNavigationBar() {
-        trashFolderProvider.getTrashFolderPath()
-            .then(on: .main) { [weak self] path in
-                self?.setupNavigationBarItems(with: path)
+        Task {
+            do {
+                let path = try await trashFolderProvider.getTrashFolderPath()
+                DispatchQueue.main.async {
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Msg/MessageActionsHandler.swift:36]: Better to avoid having to different concurrency approaches in one place

Comment (tomholub) [reply FlowCrypt/Controllers/Msg/MessageActionsHandler.swift:36]: Agree - is it the same issue as #997 ?

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Msg/MessageActionsHandler.swift:36]: Yes
