### PR TITLE
#1813 Drafts functionality

### LINKED ISSUE #691: ui tests for saving drafts
>     Difficult to test (explain why). there was not tests to this modules ( gmail service etc ). if we need to cover it with tests I would prefer it as separate issue.

This should be covered by ui tests, I'll file an issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/690#issuecomment-945174146_

### LINKED ISSUE #834: send email from draft
as user I want to send email from draft.
work is already partially done, the main thing that left is to get message/participants from draft and pre-show it in compose view controller

> when user navigates to a draft and taps it, allow the user to send or modify+send the draft, similar to what Gmail app does

### LINKED ISSUE #873: render recipients instead of sender in list of drafts
**Steps:**

1. Login as "e2e.enterprise.test@flowcrypt.com"
2. Set compose email with Recipient email('dmitry@flowcrypt.com')
2. Open Drafts screen
3. Observe screen

**Actual:** Recipient email is "e2e.enterprise.test@flowcrypt.com"
**Expected:** Recipient email should be "dmitry@flowcrypt.com"

**Notes:** Incorrect email is displayed opening draft too

https://user-images.githubusercontent.com/91205853/139641102-842eb1e3-b9d1-40ac-a55e-1f179164648e.mp4

### LINKED ISSUE #887: draft wrongly saved before any field is edited
Drafts should only be saved if the user edited any fields in this session.

can branch from #854 or wait

### LINKED ISSUE #888: re-enable drafts + unobtrusive way to request for pass phrase if missing for draft
see what browser extension is doing: the UI gets changed to request pass phrase in a way that doesn't break user typing. On iOS can say `Draft not saved: enter pass phrase` just below the top green header. When user taps it, they will see pass phrase prompt. Second, if the draft was not saved the whole time and user taps the back icon, they will be prompted for pass phrase before they can leave the screen, so we make sure to save the draft.

### LINKED ISSUE #963: mark drafts in conversation with a red "draft" label
Message in the red rectangle is draft, but it looks the same as other received or sent messages.
So for user it's not clear that this message is draft and wasn't sent yet.

Simulator Screen Shot - iPhone 13 - 2021-11-09 at 13 13 46

### LINKED ISSUE #965: App should use existing draft when creating new message in thread
New draft is created each time when I try to compose new message from thread screen.
App should check if there is existing draft for this thread and use it, instead of creating new one.

### LINKED ISSUE #970: more crashes from 0.3.2 - when encrypting drafts
these may be various users

[testflight_feedback4.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7506066/testflight_feedback4.zip)
[testflight_feedback5.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7506067/testflight_feedback5.zip)
[testflight_feedback6.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7506068/testflight_feedback6.zip)
[testflight_feedback7.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7506069/testflight_feedback7.zip)
[testflight_feedback8.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7506070/testflight_feedback8.zip)

### LINKED ISSUE #972: frequency of draft save timer to 5 seconds, ensure it runs when tapping back
We shouldn't actually be encrypting the draft every second. We should only be encrypting a draft if the content changed from last second to the next.

And even then, we should probably change it to check once in 5 seconds, and one last time when we tap the back icon. I'll file a separate issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/970#issuecomment-964360732_

### LINKED ISSUE #1813: master issue for drafts functionality
- [x]  #888
- [x]  #972 
- [x]  #887 
- [x]  #834 
- [ ]  #965
- [x]  #963 
- [x]  #873 
- [ ]  #970

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR adds drafts functionality

close #1813 
close #888 
close #972 
close #887 
close #834 
close #965 
close #963
close #873 
close #970 
close #691

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
@DenBond7 you can start here :-) same instructions as for Roma on android. Please go through the code and ask questions. It will be good for you to be able to have a basic understanding of the iOS codebase.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ErrorHandling.swift [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+//
+//  Created by Roma Sosnovsky on 14/09/22
+//  Copyright © 2017-present FlowCrypt a. s. All rights reserved.
+//
+
+import UIKit
+
+// MARK: - Error handling
+extension ComposeViewController {
+    func requestMissingPassPhraseWithModal(for signingKey: Keypair, isDraft: Bool = false, withDiscard: Bool = false) {
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+ErrorHandling.swift:13]: On Android, I think we went with not signing drafts, and that way we could avoid this. But I think either way is fine. Highlighting the difference.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift [hunk 2]
```diff
@@ -28,87 +28,27 @@ extension ComposeViewController {
         // https://github.com/FlowCrypt/flowcrypt-ios/issues/291
         try await Task.sleep(nanoseconds: 100 * 1_000_000) // 100ms
 
-        let sendableMsg = try await self.composeMessageService.validateAndProduceSendableMsg(
-            senderEmail: selectedFromEmail,
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift:32]: Was `senderEmail` moved elsewhere?

**Review by tomholub — COMMENTED** [review]
Reviewed 35 files so far. Out of 239? :eyes: that's quite a PR.

File: FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift [hunk 3]
```diff
@@ -12,42 +12,42 @@ struct ComposeMessageInput: Equatable {
...
         let sender: Recipient?
         let subject: String?
         let sentDate: Date
-        let message: String
+        let text: String
         let threadId: String?
         let replyToMsgId: String?
         let inReplyTo: String?
+        let rfc822MsgId: String?
+        let shouldEncrypt: Bool
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift:27]: I noticed this functionality in android version during testing, looked like a useful addition.

File: FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift [hunk 4]
```diff
@@ -12,42 +12,42 @@ struct ComposeMessageInput: Equatable {
...
-        return info.ccRecipients
+    var text: String? {
+        type.info?.text
     }
 
-    var subject: String? {
-        type.info?.subject
+    var isPgp: Bool {
+        guard let text = text else { return false }
+        return text.contains("-----BEGIN PGP ") && text.contains("-----END PGP ")
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift:50]: Agree, current implementation is quite basic, will need to add `treatAs` parsing too

File: FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+draft.swift [hunk 5]
```diff
@@ -5,70 +5,98 @@
 //  Created by Evgenii Kyivskyi on 10/22/21
 //  Copyright © 2017-present FlowCrypt a. s. All rights reserved.
 //
-import Foundation
+
 import GoogleAPIClientForREST_Gmail
 
 extension GmailService: DraftGateway {
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+draft.swift:11]: `Gateway` is something that stuff passes through. Like an `EmailGateway` - you send an email, it passes through, ends up in another email server.

I guess we could call all of these classes just `...ApiClient` ? `DraftApiClient`, `MessagesApiClient`, `SendMessageApiClient` ? I think that would be the clearest. Can leave it for another PR.

In particular I don't want to call everything `...Service` unless it's some sort of background service that keeps running, like a daemon, which we don't have many off.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift (hunk 2 above)
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift:32]: Yes, now we use `contextToSend.sender` as `senderEmail`

File: FlowCrypt/Functionality/DataManager/SessionService.swift [hunk 6]
```diff
@@ -112,22 +110,6 @@ extension SessionService: SessionServiceType {
         return try switchActiveSession(for: currentUser)
     }
 
-    func logOutUsersThatDontHaveAnyKeysSetUp() throws {
```
Comment (tomholub) [inline FlowCrypt/Functionality/DataManager/SessionService.swift:115]: Is this no longer wanted, or has it moved somewhere?

File: FlowCrypt/Functionality/Mail Provider/Gmail/GmailServiceError.swift [hunk 7]
```diff
@@ -54,9 +54,9 @@ extension GmailServiceError {
     static func convert(from error: NSError) -> GmailServiceError {
         switch error.code {
         case -10: // invalid_grant error code
-            return GmailServiceError.invalidGrant(error)
+            return .invalidGrant(error)
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Gmail/GmailServiceError.swift:57]: Similarly this class could be `GmailApiError`

File: FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift [hunk 8]
```diff
@@ -17,11 +16,11 @@ enum MessageFetchState {
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift:16]: The class could later be called `MessageHelper`

File: FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Gmail+MessageOperations.swift [hunk 9]
```diff
@@ -6,29 +6,28 @@
 //  Copyright © 2017-present FlowCrypt a. s. All rights reserved.
 //
 
-import Foundation
 import GoogleAPIClientForREST_Gmail
 
 extension GmailService: MessageOperationsProvider {
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/MessageOperations Provider/Gmail+MessageOperations.swift:11]: Could be called `GmailApiClient: MessageOperationsApiClient`

File: FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Gmail+MessagesList.swift [hunk 10]
```diff
@@ -13,7 +13,7 @@ import GoogleAPIClientForREST_Gmail
 // TODO: - https://github.com/FlowCrypt/flowcrypt-ios/issues/669 Remove in scope of the ticket
 extension GmailService: MessagesListProvider {
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/MessagesList Provider/Gmail+MessagesList.swift:14]: `GmailApiClinet: MessageListProviderApiClient` or something like that, maybe

File: FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift [hunk 11]
```diff
@@ -10,33 +10,28 @@ import FlowCryptCommon
 import GoogleAPIClientForREST_Gmail
 
 protocol MessagesThreadProvider {
+    func fetchThread(identifier: String, path: String) async throws -> MessageThread
     func fetchThreads(using context: FetchMessageContext) async throws -> MessageThreadContext
 }
 
 extension GmailService: MessagesThreadProvider {
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Threads/MessagesThreadProvider.swift:17]: `GmailApiClient: MessageThreadProviderApiClient`

File: FlowCrypt/Functionality/Services/Backup Services/BackupService.swift [hunk 12]
```diff
@@ -11,16 +11,16 @@ import UIKit
...
     init(
         backupProvider: BackupProvider,
         core: Core = .shared,
-        messageSender: MessageGateway
+        messageGateway: MessageGateway
     ) {
         self.backupProvider = backupProvider
         self.core = core
-        self.messageSender = messageSender
+        self.messageGateway = messageGateway
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Backup Services/BackupService.swift:23]: Same question here - how is message sender determined going forward (it may be different than currently logged in account)

File: FlowCrypt/Functionality/Services/Google User Service/GoogleUserService.swift [hunk 13]
```diff
@@ -326,7 +325,7 @@ extension GoogleUserService {
             .replacingOccurrences(of: "-", with: "+")
             .replacingOccurrences(of: "_", with: "/")
 
-        while decodedString.utf16.count % 4 != 0 {
+        while !decodedString.utf16.count.isMultiple(of: 4) {
             decodedString += "="
         }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Google User Service/GoogleUserService.swift:330]: Nice :-)

File: FlowCrypt/Resources/flowcrypt-ios-prod.js.txt [hunk 14]
```diff
@@ -20636,34 +20636,34 @@ var time_estimates;time_estimates={estimate_attack_times:function(e){var t,n,s,o
   /******/ (() => { // webpackBootstrap
```
Comment (tomholub) [inline FlowCrypt/Resources/flowcrypt-ios-prod.js.txt:20636]: On other codebases (though not yet on Android) we have a habit of placing generated code into a `../generated/..` folder. I think for this file that would be appropriate. Let's file that for another issue. (the alternative would be to name it `generated-flowcrypt-ios-prod.js.txt`)

File: appium/tests/specs/mock/composeEmail/CheckDraftFunctionality.spec.ts [hunk 15]
```diff
@@ -0,0 +1,102 @@
...
+import {
+  EmailScreen,
+  MailFolderScreen, MenuBarScreen, NewMessageScreen,
+  SetupKeyScreen,
+  SplashScreen
+} from '../../../screenobjects/all-screens';
+
+describe('COMPOSE EMAIL: ', () => {
+
+  it('check drafts functionality', async () => {
```
Comment (tomholub) [inline appium/tests/specs/mock/composeEmail/CheckDraftFunctionality.spec.ts:14]: Test looks good :+1:

**Review by tomholub — COMMENTED** [review]
The class renames would all be for one issue in the future.

Overall looks good.

File: FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift:50]: Let's file that for another issue. Should be able to reproduce it by trying to reply to any pgp/mime message, I suppose.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 16]
```diff
@@ -191,29 +218,15 @@ final class ComposeViewController: TableNodeViewController {
...
-        }
-        for recipient in message.bcc {
-            evaluateMessage(recipient: recipient, type: .bcc)
-        }
-    }
-
-    func evaluateMessage(recipient: Recipient, type: RecipientType) {
-        let recipient = ComposeMessageRecipient(
+    func add(recipient: Recipient, type: RecipientType) {
+        let composeRecipient = ComposeMessageRecipient(
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/ComposeViewController.swift:222]: Ah, `add(recipient: Recipient, type: RecipientType)` depends on `decorator` and `evaluate(recipient: composeRecipient)` which are part of `ComposeViewController`.
Moving it to `ComposeMessageContext` will need passing these variables too, so I think it'll be better to use current implementation

File: FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift (hunk 3 above)
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift:27]: Yes. Android app actually allows to send plain messages, which iOS app doesn't. So it fits a little better in Android app. But eventually I think we'll add that functionality to iOS as well, so it's not wrong to already do similar things now for draft.

File: FlowCrypt/Functionality/Services/Backup Services/BackupService.swift (hunk 12 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/Backup Services/BackupService.swift:23]: answered

**Comment by tomholub** [comment]
@sosnovsky is there a way you could build an app for Den to run with just an iPhone without a mac?

File: FlowCrypt/Functionality/DataManager/SessionService.swift (hunk 6 above)
Comment (sosnovsky) [reply FlowCrypt/Functionality/DataManager/SessionService.swift:115]: It wasn't used anywhere, so I just removed unused code

Comment (tomholub) [reply FlowCrypt/Functionality/DataManager/SessionService.swift:115]: It was called just a few lines above. But the question is, did it have any useful effect? That's hard to say.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift (hunk 16 above)
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Compose/ComposeViewController.swift:222]: ok

File: FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift (hunk 4 above)
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift:50]: I didn't find `pgp/mime` message in our `e2e.enterprise.test` mail account, probably we'll need to add one for testing and then use it for mock ui test.

[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/ComposeViewControllerInput.swift:50]: Created issue https://github.com/FlowCrypt/flowcrypt-ios/issues/1853

File: FlowCrypt/Resources/flowcrypt-ios-prod.js.txt (hunk 14 above)
Comment (sosnovsky) [reply FlowCrypt/Resources/flowcrypt-ios-prod.js.txt:20636]: https://github.com/FlowCrypt/flowcrypt-ios/issues/1854

File: FlowCrypt/Functionality/DataManager/SessionService.swift (hunk 6 above)
Comment (sosnovsky) [reply FlowCrypt/Functionality/DataManager/SessionService.swift:115]: It wasn't called there, it was just in the list of `protocol SessionServiceType` methods - https://github.com/FlowCrypt/flowcrypt-ios/blob/8d1e041872723730fe0c44b1805e2fc78fae57fa/FlowCrypt/Functionality/DataManager/SessionService.swift#L39

File: FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+draft.swift (hunk 5 above)
Comment (sosnovsky) [reply FlowCrypt/Functionality/Mail Provider/Message Gateway/GmailService+draft.swift:11]: https://github.com/FlowCrypt/flowcrypt-ios/issues/1855

**Comment by DenBond7** [comment]
> Yes, I'll need UDID of @DenBond7 iPhone (here is how you can get it - https://www.itexico.com/blog/find-unique-device-identifier-udid-on-the-iphone)

Is it safe to share it here?

**Comment by tomholub** [comment]
> > Yes, I'll need UDID of @DenBond7 iPhone (here is how you can get it - https://www.itexico.com/blog/find-unique-device-identifier-udid-on-the-iphone)
> 
> Is it safe to share it here?

I think so, but you can alternatively send it to sosnovsky at flowcrypt.com

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift [hunk 17]
```diff
@@ -91,3 +142,25 @@ extension ComposeViewController {
...
+            guard let self = self else { return }
+
+            if let error = error {
+                self.handle(error: error)
+            } else {
+                if var messageIdentifier = self.composeMessageService.messageIdentifier {
+                    messageIdentifier.draftMessageId = self.input.type.info?.id
+                    self.handleAction?(.update(messageIdentifier))
+                }
+                self.showToast("draft_saved".localized)
```
Comment (DenBond7) [inline FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift:161]: This one is interesting. Do you show "draft_saved" after a draft was saved remotely or locally?

**Comment by DenBond7** [comment]
> I think so, but you can alternatively send it to sosnovsky at flowcrypt.com

I've already done it.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TableView.swift [hunk 18]
```diff
@@ -77,7 +77,7 @@ extension ComposeViewController: ASTableDelegate, ASTableDataSource {
             case let (.searchEmails(recipients), .searchResults):
                 guard indexPath.row > 0 else { return DividerCellNode() }
                 guard recipients.isNotEmpty else { return self.noSearchResultsNode() }
-                guard let recipient = recipients[safe: indexPath.row-1] else { return ASCellNode() }
+                guard let recipient = recipients[safe: indexPath.row - 1] else { return ASCellNode() }
```
Comment (DenBond7) [inline FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TableView.swift:80]: It seems this line contains just code formatting. Does your IDE support auto formating before committing?

File: FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift [hunk 19]
```diff
@@ -304,90 +422,101 @@ extension ThreadDetailsViewController {
...
-            handleWrongPassPhrase(for: message, at: indexPath)
+        case .missingPassPhrase:
+            handleWrongPassPhrase(indexPath: indexPath)
         default:
             // TODO: - Ticket - Improve error handling for ThreadDetailsViewController
             if let someError = error as NSError?, someError.code == Imap.Err.fetch.rawValue {
                 // todo - the missing msg should be removed from the list in inbox view
                 // reproduce: 1) load inbox 2) move msg to trash on another email client 3) open trashed message in inbox
-                showToast("Message not found in folder: \(thread.path)")
+                showToast("Message not found in folder: \(inboxItem.folderPath)")
```
Comment (DenBond7) [inline FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift:519]: It seems it's not a localized text. Am I right?

File: FlowCryptUI/Views/NavigationBarItemsView.swift [hunk 20]
```diff
@@ -69,7 +69,7 @@ public final class NavigationBarItemsView: UIBarButtonItem {
         fatalError("init(coder:) has not been implemented")
     }
 
-    public override var isEnabled: Bool {
+    override public var isEnabled: Bool {
```
Comment (DenBond7) [inline FlowCryptUI/Views/NavigationBarItemsView.swift:72]: There are a lot of changes like this one. Was it necessary to do it as a part of the current PR? If not, please do such changes in a separate PR in the future. It seems these changes don't relate to the current PR title and make it too big.

File: Gemfile.lock [hunk 21]
```diff
@@ -3,7 +3,7 @@ GEM
   specs:
     CFPropertyList (3.0.5)
       rexml
-    activesupport (6.1.6.1)
+    activesupport (6.1.7)
```
Comment (DenBond7) [inline Gemfile.lock:6]: As I understand `dependabot` works for the current repo. It will be better to update dependencies one by one via `dependabot` if the tests work. When you update a lot of dependencies there is a big chance that some thing can be broken under the hood.

**Comment by DenBond7** [comment]
@sosnovsky I've completed my review. Looks good to me :+1: 

> And then I'll be able to create FlowCrypt build and share it through https://www.diawi.com/

Please share a debug build for testing when you will be able. I'd like to test my cases.

**Comment by sosnovsky** [comment]
@DenBond7 I sent app link to your email

File: Gemfile.lock (hunk 21 above)
Comment (sosnovsky) [reply Gemfile.lock:6]: Ruby dependencies here are used only for building app for testing.
No tests depend on them, so it's safe to update.

File: FlowCryptUI/Views/NavigationBarItemsView.swift (hunk 20 above)
Comment (sosnovsky) [reply FlowCryptUI/Views/NavigationBarItemsView.swift:72]: Yeah, agree 100%, I started updating these small things when noticed them during development.
But then there were too many of them, so I stopped but it was already too late :)

File: FlowCrypt/Functionality/Mail Provider/Gmail/GmailService.swift [hunk 22]
```diff
@@ -63,5 +62,5 @@ extension String {
     static let bcc = "bcc"
     static let replyTo = "reply-to"
     static let inReplyTo = "in-reply-to"
-    static let identifier = "Message-ID"
+    static let identifier = "message-id"
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Functionality/Mail Provider/Gmail/GmailService.swift:65]: On iOS we compare lowercased header names - https://github.com/FlowCrypt/flowcrypt-ios/blob/feature/issue-1813-drafts/FlowCrypt/Functionality/Mail%20Provider/Message%20Provider/Gmail%2BMessageExtension.swift#L44

And I think there were some messages with `Message-Id` header, so it's safer to convert them to lowercase.

File: FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift (hunk 19 above)
Comment (sosnovsky) [reply FlowCrypt/Controllers/Threads/ThreadDetailsViewController.swift:519]: Yep, there are still some non-localized string in the app, I'll add localization here.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TableView.swift (hunk 18 above)
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+TableView.swift:80]: Yes, we use `swiftlint`, but in this PR I updated it's config with additional rules like this one - spaces around operators.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift (hunk 17 above)
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift:161]: On iOS we currently don't have local storage for drafts and messages. Alert is shown after remote save

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Picker.swift [hunk 23]
```diff
@@ -34,7 +34,7 @@ extension ComposeViewController: UIImagePickerControllerDelegate, UINavigationCo
         reload(sections: [.attachments])
     }
 
-    internal func appendAttachmentIfAllowed(_ attachment: MessageAttachment) {
+    private func appendAttachmentIfAllowed(_ attachment: MessageAttachment) {
         let totalSize = contextToSend.attachments.map(\.size).reduce(0, +) + attachment.size
         if totalSize > GeneralConstants.Global.attachmentSizeLimit {
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Picker.swift:39]: Currently it's 10mb - https://github.com/FlowCrypt/flowcrypt-ios/blob/feature/issue-1813-drafts/FlowCrypt/App/GeneralConstants.swift#L16

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift [hunk 24]
```diff
@@ -8,53 +8,67 @@
...
-        return false
-//        let newDraft = ComposedDraft(email: email, input: input, contextToSend: contextToSend)
-//        guard let oldDraft = composedLatestDraft else {
-//            composedLatestDraft = newDraft
-//            return true
-//        }
-//        let result = newDraft != oldDraft
-//        composedLatestDraft = newDraft
-//        return result
+    private func createDraft() -> ComposedDraft? {
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift:29]: Draft is auto-saved when user taps back button - https://github.com/FlowCrypt/flowcrypt-ios/blob/feature/issue-1813-drafts/FlowCrypt/Controllers/Compose/Extensions/ComposeViewController%2BSetup.swift#L151

And it's also automatically saved each 5 seconds

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 25]
```diff
@@ -117,24 +121,46 @@ final class ComposeViewController: TableNodeViewController {
...
+
+        if let composeMessageService = composeMessageService {
+            self.composeMessageService = composeMessageService
+        } else {
+            self.composeMessageService = try await ComposeMessageService(
+                appContext: appContext,
+                keyMethods: keyMethods,
+                draftGateway: draftGateway
+            )
+        }
```
Comment (ioanmo226) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:134]: I think you updated above code because `ComposeMessageService` requires  `messageOperationsProvider` (and it needs to be async/await)
But As I checked, `ComposeMessageService.messageOperationsProvider` is not used at all and we can remove that and revert above change to below one?

   ```swift
     self.composeMessageService = composeMessageService ?? ComposeMessageService(
            appContext: appContext,
            keyMethods: keyMethods
        )

```

**Review by ioanmo226 — COMMENTED** [review]
Great work @sosnovsky  👍 
I've only reviewed 20 files so far and will continue tomorrow

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift (hunk 24 above)
[the remark this answers is not in the document]
Comment (DenBond7) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift:29]: Thanks. I've tested it. Looks a little strange this behavior `Draft is auto-saved when user taps back button`.

A user can't leave a screen while a draft is saving. Firstly, I thought I didn't tap on the back button. 
What about a case when the saving process will take around 20 seconds? All this time a user will try to tap on the back button and will not understand why he can't leave a screen. (As it was for me during 5-6 seconds. I thought the app is frozen). It would be nice to have some progress bar or notification about saving a draft.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift (hunk 17 above)
Comment (DenBond7) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Setup.swift:161]: about this one. It seems you show this toast wrongly for some cases

>draft should not be saved if I only just rendered compose or reply. I have to actually input something first (any of the fields)

To test just open a compose screen and leave the screen without any actions. The same situation with reply/forward mode. 
You show a notification `showToast("draft_saved".localized)` but don't save a draft.

**Review by ioanmo226 — COMMENTED** [review]
Looks good. 👍 
With few comments/issues

- Draft password protected message issue
1. Try to create new draft with recipient without pubkeys.
2. Tap back button(app will ask user to enter password to password-protect message) and enter password
3. Two new drafts will appear(This is also issue. I think there should be one draft saved in this case)
[Edit] 2 new drafts appear to my side because I pressed back button 2 times. If I press back button 5 times, 5 new drafts would appear. This issue will be fine if we show progress bar while saving draft i think.
5. Try to open that draft and send message. It will ask user to enter password again (Entering password before doesn't have effect. Maybe we need to save password in LocalStorage or do not ask user password for this case)
- Draft delete crash issue 
1. Go to `Draft` screen
2. create 2 new drafts
3. delete one draft(let's say we delete 2nd draft)
6. now try to delete 1st draft and app will crash
image

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift (hunk 24 above)
[the remark this answers is not in the document]
Comment (ioanmo226) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift:29]: I agree with @DenBond7.
I also thought app was frozen when I tap back button. I think we should show progress bar while saving draft.

**Comment by DenBond7** [comment]
A few more comments

@sosnovsky Please test the following steps

1. Go to `Drafts` folder
2. Create a draft
3. Now you have some draft
4. Got to other email clients(for example a web version)
5. Modify this draft
6. Back to the app on iPhone
7. DO NOT UPDATE list
8. Open a draft from 3.
9. Modify it
10. Now you will see that you have two drafts in a thread.

Is it expected? I tested this scenario with Web Gmail and Android Gmail. They update the existing draft and do not create a new one in a thread.

@tomholub I'm not sure what is better.

**Comment by DenBond7** [comment]
@sosnovsky App crashes for the following scenario: Open any message and tap on the reply button with the green arrow. It doesn't allow me to test drafts for threads.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift (hunk 24 above)
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift:29]: Or just save it in the background, with automatic delay and repeat on network error or error 5xx. Until the app is killed, of course.

**Comment by tomholub** [comment]
Agree, Mart can do further testing on both.

**Comment by sosnovsky** [comment]
> Is it expected? I tested this scenario with Web Gmail and Android Gmail. They update the existing draft and do not create a new one in a thread.

No, it should update existing draft as Gmail does. Probably it happens because of old message id (which changes on draft edit), I'll try to reproduce and fix it. Thanks for finding!

**Comment by tomholub** [comment]
It would be great to create test cases for the discovered issues, and then work on fixes from there.

Well noticed @DenBond7

**Comment by sosnovsky** [comment]
> @sosnovsky App crashes for the following scenario: Open any message and tap on the reply button with the green arrow. It doesn't allow me to test drafts for threads.

@DenBond7 are you using Gmail account? As imap functionality for iOS is currently not implemented, so there are possible crashes.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift [hunk 26]
```diff
@@ -8,53 +8,67 @@
...
+            composedLatestDraft = newDraft
+            return nil
+        }
+
+        return newDraft != existingDraft ? newDraft : nil
     }
 
-    internal func saveDraftIfNeeded() {
-        guard shouldSaveDraft() else { return }
+    func saveDraftIfNeeded(withAlert: Bool = false, handler: ((Error?) -> Void)? = nil) {
```
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift:43]: It was used for asking passphrase, but then we removed signing of drafts, so it's not needed anymore, I'll remove it.
Thanks for noticing!

**Comment by tomholub** [comment]
> > @sosnovsky App crashes for the following scenario: Open any message and tap on the reply button with the green arrow. It doesn't allow me to test drafts for threads.
> 
> @DenBond7 are you using Gmail account? As imap functionality for iOS is currently not implemented, so there are possible crashes.

Do we still allow users to sign in using IMAP? If yes, we should hide that login button, and only offer Gmail, until fixed up. I'll file a separate issue.

**Comment by sosnovsky** [comment]
> Do we still allow users to sign in using IMAP? If yes, we should hide that login button, and only offer Gmail, until fixed up. I'll file a separate issue.

@tomholub yes, imap login button is shown on login screen.

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift (hunk 24 above)
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+Drafts.swift:29]: On simulator draft saving usually takes less than 1 second, so I didn't add any progress bar, but on device it takes several seconds for me too.
I'll try to find why it happens to make saving on device faster and will also run saving in background, so it won't affect user experience.

**Comment by DenBond7** [comment]
> are you using Gmail account? 

Yup, it was flowcrypt.com account

**Comment by sosnovsky** [comment]
@DenBond7 does it happen for all threads or just for specific ones? As I've just tested the same build from diawi and it works well for me - I'm able to create draft replies.

**Comment by DenBond7** [comment]
> does it happen for all threads or just for specific ones? As I've just tested the same build from diawi and it works well for me - I'm able to create draft replies.

It happens in most cases

https://user-images.githubusercontent.com/2863246/194542813-47197f4c-ca74-4560-9b3c-d077151b04cb.MP4


https://user-images.githubusercontent.com/2863246/194542818-13134a7a-6b11-4dba-b7e3-7cdcb92ad32c.MP4

**Comment by DenBond7** [comment]
> does it happen for all threads or just for specific ones? As I've just tested the same build from diawi and it works well for me - I'm able to create draft replies.

@sosnovsky The last build works well. This issue is fixed.

**Comment by DenBond7** [comment]
@sosnovsky But I've found a new issue. To reproduce you can use our conversation in Gmail. Please choose any message in the thread and make a reply. The app will create a draft. But the web Gmail client can't edit this draft when I try to open a thread. Actually, the web Gmail client shows that there is a draft in the message list, but doesn't show a draft when I open a thread.

It seems you've missed updating headers in the draft. Please check https://developers.google.com/gmail/api/guides/threads#adding_drafts_and_messages_to_threads

**Comment by sosnovsky** [comment]
PR is ready for re-review - I fixed mentioned bugs and also updated ui test to include more cases.

File: Core/source/mobile-interface/endpoints.ts [hunk 27]
```diff
@@ -55,9 +55,10 @@ export class Endpoints {
     if (req.format === 'plain') {
       const atts = (req.atts || []).map(({ name, type, base64 }) =>
         new Att({ name, type, data: Buf.fromBase64Str(base64) }));
-      return fmtRes({}, Buf.fromUtfStr(await Mime.encode(
-        // eslint-disable-next-line @typescript-eslint/naming-convention
-        { 'text/plain': req.text, 'text/html': req.html }, mimeHeaders, atts)));
+      // eslint-disable-next-line @typescript-eslint/naming-convention
+      const body: SendableMsgBody = { 'text/plain': req.text };
+      if (req.html) { body['text/html'] = req.html; }
```
Comment (tomholub) [inline Core/source/mobile-interface/endpoints.ts:60]: A detail - please have the block code on its own line

File: FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift [hunk 28]
```diff
@@ -17,8 +17,7 @@ final class InMemoryPassPhraseStorage: PassPhraseStorageType {
     let passPhraseProvider: InMemoryPassPhraseProviderType
 
     init(
-        passPhraseProvider: InMemoryPassPhraseProviderType = InMemoryPassPhraseProvider.shared,
-        timeoutInSeconds: Int = 4 * 60 * 60 // 4 hours
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift]: I suppose this has moved somewhere and is therefore retained?

**Review by tomholub — COMMENTED** [review]
See comments below, looks good to me. Tests still not happy? Did they get more troublesome lately, or is that PR related?

File: FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift (hunk 28 above)
Comment (sosnovsky) [reply FlowCrypt/Functionality/Services/Local Private Key Services/InMemoryPassPhraseStorage.swift]: Yes, this change is from https://github.com/FlowCrypt/flowcrypt-ios/pull/1840 - `timeoutInSeconds` is now parsed from client configuration.

**Comment by DenBond7** [comment]
I've tested the latest build. It works well. Draft functionality looks good. Just found a few UI issues. What's strange, I can reproduce it only in our last conversation. It can be fixed in another PR, @sosnovsky is up to you.

photo1665729362 (1)
photo1665729362

**Review by DenBond7 — DISMISSED** [review]

**Review by ioanmo226 — COMMENTED** [review]
Looks good.
A few issues/crashes.

- Crash issue
1. Go to drafts screen(ensure no drafts are there)
2. create new draft and press back button
3. Wait until `saving draft` toast is disappeared
4. Pull-to refresh and you will see below crash
image

- Edit existing draft issue 
1. Open existing draft (which recipients do not have pub key)
2. Enter another recipient which have pub key
3. Press back button and you will see below toast (which doesn't make sense to me. Draft was created without issue first time for recipients without pubkey but can't update)
image

- Draft update issue
1. Go to drafts screen
2. Create draft (enter valid recipients, subject, message)
3. Go back to draft screen
4. Now click newly saved draft
5. You will notice below issue

Therefore I couldn't test draft send feature.

image

**Comment by sosnovsky** [comment]
Thanks guys for such detailed testing 👍

@ioanmo226 I pushed fixes for found issues, should work well now
@DenBond7 I emailed you link to the new build with fix for separator issue

**Comment by ioanmo226** [comment]
Just tested and I can see that all above issues are all fixed.

**Comment by ioanmo226** [comment]
This is small issue but need to be fixed.
When I click subject it leads to crash.
I think we sure always use `safe` for getting nth elements like `input[safe: indexPath.section - 1]`.

image

**Comment by sosnovsky** [comment]
> @sosnovsky By the way, I think we should have UI test(for last case at above comment) which tests draft send feature

Agree, I'll update current ui test to include this case too.

**Comment by ioanmo226** [comment]
Another issue I noticed.

1. Select any thread and click reply
2. Type some reply text
3. Go back and go to `Drafts` screen
4. Open that thread
5. Open that Draft.
6. Click back button. You will see 2 drafts 
7. If you repeat 5th and 6th step, you will see 3 drafts and so more.

**Comment by DenBond7** [comment]
> I emailed you link to the new build with fix for separator issue

@sosnovsky I've tested. My issues were fixed. Thanks!

**Comment by sosnovsky** [comment]
@ioanmo226 I fixed issues from your list and also updated ui test, please check

**Comment by ioanmo226** [comment]
@sosnovsky I see 2 drafts for this case.
1. Open app, In Inbox screen, click compose button
2. Enter recipient and subject
3. Go back, Click menu button and click draft button and go to draft screen
4. Now you will see 2 new drafts
image

**Comment by sosnovsky** [comment]
@ioanmo226 does it happen every time for you? As I wasn't able to reproduce this bug.

Maybe it happens when first 'save draft` request is still in progress and user taps back button, which triggers another 'save draft' request. I'll try to handle this case, probably by cancelling previous request

**Comment by ioanmo226** [comment]
Hmm.. It happens everytime.
After I entered recipient subject, I immediately tapped back button though

**Comment by ioanmo226** [comment]
Here's video
chrome-capture-2022-9-18

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift [hunk 29]
```diff
@@ -28,87 +28,27 @@ extension ComposeViewController {
...
+            messageId: identifier
         )
-        present(alert, animated: true, completion: nil)
-    }
-
-    internal func handle(error: Error) {
-        UIApplication.shared.isIdleTimerDisabled = false
-        hideSpinner()
-        navigationItem.rightBarButtonItem?.isEnabled = true
+        handleAction?(.sent(messageIdentifier))
```
Comment (ioanmo226) [inline FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift:46]: Is `handleAction` handler implemented somewhere? I couldn't find.

**Review by ioanmo226 — COMMENTED** [review]
Everything else(except above issue) looks great 👍  (I tried possible draft functionalities and they all work well)

File: FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift (hunk 29 above)
Comment (sosnovsky) [reply FlowCrypt/Controllers/Compose/Extensions/ComposeViewController+MessageSend.swift:46]: `handleAction` is passed to `ComposeViewController` on init - https://github.com/FlowCrypt/flowcrypt-ios/blob/feature/issue-1813-drafts/FlowCrypt/Controllers/Compose/ComposeViewController.swift#L158

So view controller, from which `ComposeViewController` was opened, can handle actions like sending message or creating new draft.

**Comment by sosnovsky** [comment]
@ioanmo226 I pushed fix for duplicated drafts, please check if it works well for you now, thanks

**Review by ioanmo226 — APPROVED** [review]
@sosnovsky Previous issue is fixed and everything looks fine 👍 
I'm gonna merge this PR first as this PR is getting bigger and bigger.
@martgil Please leave comments if you have any so that it can be addressed in other PR.
