### PR TITLE
#2063 Fix: Double encrypt attachment issue when forwarding 

### LINKED ISSUE #2063: Attachment is double-encrypted in forwarded message
While forwarding an email (with attachment) the attachment becomes "over" encrypted and has a .pgp.pgp extension, which makes it impossible to decrypt by recipient.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed double encrypt attachment issue when forwarding

close #2063 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TapActions.swift [hunk 1]
```diff
@@ -119,7 +125,39 @@ extension ThreadDetailsViewController {
...
+                progressHandler: { [weak self] progress in
+                    self?.handleFetchProgress(state: .download(progress))
+                }
+            )
+            return updatedAttachment
+        }
+        return attachment
+    }
+
+    private func decryptAttachment(for attachment: MessageAttachment) async throws -> MessageAttachment {
```
Comment (sosnovsky) [inline FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TapActions.swift:144]: It can be just `decrypt(attachment: MessageAttachment)`, as `decryptAttachment(for: attachment)` looks strange

Comment (ioanmo226) [reply FlowCrypt/Controllers/Threads/ThreadDetailsViewController+TapActions.swift]: ok

**Review by sosnovsky — APPROVED** [review]
👍
