### PR TITLE
#1913 Fix trash button tap

### LINKED ISSUE #1913: tapping trash icon on an email does nothing
on version 1.1.1. It just shows loader for a second, but nothing changes.

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR fixes bug when it was impossible to delete thread + adds error message alert for such cases (so it'll be easier to find reason for possible issues in the future)

close #1913

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: appium/api-mocks/apis/google/google-data.ts [hunk 1]
```diff
@@ -389,14 +389,28 @@ export class GoogleData {
...
+        if (labelIds.length) {
+          const messageLabels = m.labelIds || [];
+          if (messageLabels.includes('TRASH')) {
+            return labelIds.includes('TRASH');
+          } else {
+            return messageLabels.some(l => labelIds.includes(l));
+          }
+        } else {
+          return true;
+        }
```
Comment (ioanmo226) [inline appium/api-mocks/apis/google/google-data.ts:403]: we don't need `else` statements here. just `return` would do a job.
Not necessary to remove `else` though.
