### PR TITLE
Fix for collection view layout

### LINKED ISSUE #1315: iPad - fix layout for recipients
Screenshot 2022-01-13 at 14 51 41

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR fixes layout for recipients input

close #1315

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (ui changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Shouldn't the recipient bubbles flow like text? Eg how the browser extension does it, or more or less how it was before. After this change it's one recipient per line - why so?

**Comment by Kharchevskyi** [comment]
Can change it to layout one to another like text flow

**Comment by tomholub** [comment]
What was the issue in this screenshot?

image

**Comment by Kharchevskyi** [comment]
Wrong calculation for collection view frame height. Each new recipient adds extra space to the bottom of collection view. 

Will just fix height calculation.

**Comment by tomholub** [comment]
ah - understood

> Will just fix height calculation.

:+1:

**Comment by Kharchevskyi** [comment]
@tomholub please check attached sreen shots.

File: FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift [hunk 1]
```diff
@@ -55,15 +61,8 @@ final public class RecipientEmailsCellNode: CellNode {
...
-        let recipientNodeInset = RecipientEmailNode.Constants.layoutInsets.height
-            + RecipientEmailNode.Constants.titleInsets.height
 
-        let textSize: CGSize = recipients.first?.email.size() ?? .zero
-        let recipientsHeight = (textSize.height + recipientNodeInset) * CGFloat(recipients.count)
-        let insets = Constants.minimumLineSpacing * CGFloat(recipients.count - 1)
-        let height = recipientsHeight + insets + Constants.sectionInset.height
-
-        collectionNode.style.preferredSize.height = height
+        collectionNode.style.preferredSize.height = collectionLayoutHeight
```
Comment (Kharchevskyi) [inline FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift:65]: @sosnovsky note for reviewing:
Calculation for flow layout height happens after we set height for collectionNode, so it is not possible to calculate height here( 

Thats why we need to observe calculated height from collection layout in controller to be able to react on height changes and update `RecipientEmailsCellNode` with updated height value

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 2]
```diff
@@ -713,11 +719,27 @@ extension ComposeViewController {
     }
 
     private func recipientsNode() -> RecipientEmailsCellNode {
-        RecipientEmailsCellNode(recipients: recipients.map(RecipientEmailsCellNode.Input.init))
+        return RecipientEmailsCellNode(
+            recipients: recipients.map(RecipientEmailsCellNode.Input.init),
+            height: calculatedRecipientsPartHeight ?? minRecipientsPartHeight
+        )
+            .onLayoutHeightChanged { [weak self] layoutHeight in
```
Comment (Kharchevskyi) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:726]: observe changes from flow layout

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 3]
```diff
@@ -22,6 +22,12 @@ private struct ComposedDraft: Equatable {
  * - Or from *ThreadDetailsViewController* controller by tapping on *reply* or *forward*
  **/
 final class ComposeViewController: TableNodeViewController {
+    private let minRecipientsPartHeight: CGFloat = 44
+    var calculatedRecipientsPartHeight: CGFloat? {
+        didSet {
+            node.reloadRows(at: [recipientsIndexPath], with: .fade)
```
Comment (Kharchevskyi) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:28]: update height of collection node

File: FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift (hunk 1 above)
Comment (tomholub) [reply FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift:65]: If it's generally surprising for the person reading the code, it may be appropriate to add a comment in the code.

Comment (Kharchevskyi) [reply FlowCryptUI/Cell Nodes/RecipientEmailsCellNode.swift:65]: Have just added comment's for reviewers, don't think it worth commenting it.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 4]
```diff
@@ -713,11 +719,27 @@ extension ComposeViewController {
...
+            .onLayoutHeightChanged { [weak self] layoutHeight in
+                guard let self = self, self.calculatedRecipientsPartHeight != layoutHeight else {
+                    return
+                }
+
+                if layoutHeight > self.minRecipientsPartHeight {
+                    self.calculatedRecipientsPartHeight = layoutHeight
+                } else if layoutHeight > 0 {
+                    self.calculatedRecipientsPartHeight = layoutHeight
+                }
```
Comment (sosnovsky) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:735]: Do we need both checks? We can leave only `if layoutHeight > 0` as `minRecipientsPartHeight` is bigger than 0 too.

**Review by sosnovsky — COMMENTED** [review]
Looks good to me, just one small comment

**Review by sosnovsky — APPROVED** [review]
