### PR TITLE
#2013 Fix: Javascript exception after app was in background for long time

### LINKED ISSUE #2013: Javascript exception after app was in background for long time
reported by Tom:
```
happens after the app was running in background for a day
during that day, the app was on conversation view screen
happened when opening existing draft in that conversation
error shows again if i go back and reopen the draft
error goes away when i kill the app

likely related to the webview change. maybe something in the webview gets garbage collected or otherwise disposed to free memory after longer time
```

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed Javascript exception after app was in background for long time

close #2013 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (Hard to reproduce in ci environment)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
Please let me know if you still face issue with this version.
For me, I can't reproduce issue.

**Comment by sosnovsky** [comment]
To reproduce this issue you need several hours to pass:
1) open FlowCrypt on real device
2) open some thread
3) go back to iOS home screen, so app stays in background
4) open app after several hours (it should still have thread screen opened)
5) try to open any thread - infinite spinner

For me it's reproduced when I open app in the morning and then the next time in the evening, so 8-10 hours should be enough.

**Comment by ioanmo226** [comment]
Thank you. Got it

File: FlowCrypt/Core/Core.swift [hunk 1]
```diff
@@ -62,8 +56,13 @@ class Core: KeyDecrypter, KeyParser, CoreComposeMessageType {
 
     // MARK: - Setup
     func setupWebView() {
-        guard let jsFileSrc = getCoreJsFile() else { return }
+        let userController = WKUserContentController()
```
Comment (sosnovsky) [inline FlowCrypt/Core/Core.swift:59]: Here you updated only initial webView initialization, but we also need to use it when `WKErrorDomain` was caught.

Comment (ioanmo226) [reply FlowCrypt/Core/Core.swift:59]: Well, when `WKErrorDomain` was caught this `setupWebView` function would be called and webview should be re-initialized.

```swift
if error._domain == "WKErrorDomain" {
    // Core js code injected using evaluateJavaScript result is removed when app is in background for long time
    // Need to setup again. https://github.com/FlowCrypt/flowcrypt-ios/issues/2013
    setupWebView()
    return try await call(endpoint, params: params, data: data)
}
```

Comment (sosnovsky) [reply FlowCrypt/Core/Core.swift:59]: Ah, I missed it 👍
I'll install new build and check if bug is gone in the evening

**Comment by sosnovsky** [comment]
@ioanmo226 I re-opened app in the evening and it's just crashed for me on step `5. try to open any thread`

**Comment by ioanmo226** [comment]
It crashed in my side too. Let me dig further

File: FlowCrypt/Core/Core.swift [hunk 2]
```diff
@@ -62,10 +56,17 @@ class Core: KeyDecrypter, KeyParser, CoreComposeMessageType {
 
     // MARK: - Setup
     func setupWebView() {
-        guard let jsFileSrc = getCoreJsFile() else { return }
-
-        let appVersion = Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "[unknown version]"
-        webView.evaluateJavaScript("const APP_VERSION = 'iOS \(appVersion)';\(jsFileSrc)") { _, _ in }
+        DispatchQueue.main.async {
```
Comment (ioanmo226) [inline FlowCrypt/Core/Core.swift:59]: @sosnovsky  I believe the app crashed because the webview was not set up on the main thread. When I tried to re-setup the webview in thread detail view, it threw an error stating that the webview setup code must be executed on the main thread.

Comment (ioanmo226) [reply FlowCrypt/Core/Core.swift:59]: Waiting for my testflight build to throw error and new build to work fine.
Will let you know once I finish testing so that you can review

Comment (sosnovsky) [reply FlowCrypt/Core/Core.swift:59]: Sounds good 👍
Maybe we can use `@MainActor` here?

Comment (ioanmo226) [reply FlowCrypt/Core/Core.swift]: Sure. Maybe you need to build & run this PR in device and check after 8-10 hours if app crashes?

**Review by sosnovsky — APPROVED** [review]
Works well for me after this fix 👍
