### PR TITLE
#1373 Fix realm decryption issue when prewarm mode

### LINKED ISSUE #1373: storage corrupted - unable to open realm
image

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed realm decryption issue when prewarm mode

issue #1373 (edited by Tom)

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (This case is hard to reproduce and happens to a few users when app is in prewarm mode)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/AppDelegate.swift [hunk 1]
```diff
@@ -7,17 +7,30 @@ import AppAuth
...
 import GTMAppAuth
 import FlowCryptCommon
+import Combine
 
 @main
 class AppDelegate: UIResponder, UIApplicationDelegate, AppDelegateGoogleSesssionContainer {
     var blurViewController: BlurViewController?
     var googleAuthSession: OIDExternalUserAgentSession?
     let window = UIWindow(frame: UIScreen.main.bounds)
+    private var cancellable = Set<AnyCancellable>()
```
Comment (tomholub) [inline FlowCrypt/AppDelegate.swift:17]: Let's call it `waitingForProtectedDataCancellable`

File: FlowCrypt/AppDelegate.swift [hunk 2]
```diff
@@ -7,17 +7,30 @@ import AppAuth
...
 
     func application(_ application: UIApplication, didFinishLaunchingWithOptions _: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
         if application.isRunningTests {
             return true
         }
+        // Avoid race condition where the app might try to access keychain data before the device has decrypted it
```
Comment (tomholub) [inline FlowCrypt/AppDelegate.swift:23]: let's change this comment to:

`// When trying to initialize storage before protected data is available, existing storage may get corrupted due to a lost db encryption key. See https://github.com/FlowCrypt/flowcrypt-ios/issues/1373`

**Review by tomholub — COMMENTED** [review]
thanks - see below

**Review by tomholub — APPROVED** [review]
Hopefully this will fix it. However, it doesn't close the issue yet - I'll adjust the description.
