### PR TITLE
Use @MainActor instead of DispatchQueue.main.async

### LINKED ISSUE #997: use @MainActor instead of DispatchQueue.main.async
Also for `@MainActor` I left comment only in 1 file, but we can create separate issue for it, as there are other places where it can help us to avoid running some functions on wrong thread. For example we can wrap `showToast`, `handleError` with `@MainActor` so we won't need to check if it's on main thread or not.

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-ios/issues/985#issuecomment-966323269_

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #997

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Common UI/AttachmentManager.swift [hunk 1]
```diff
@@ -9,6 +9,7 @@
 import UIKit
 import Combine
 
+@MainActor
```
Comment (ivan-ushakov) [inline FlowCrypt/Common UI/AttachmentManager.swift:12]: `@MainActor` on type makes all methods and properties to be isolated so we could avoid marking each method with `@MainActor`.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 2]
```diff
@@ -21,7 +21,6 @@ private struct ComposedDraft: Equatable {
  * - User can be redirected here from *InboxViewController* by tapping on *+*
  * - Or from *ThreadDetailsViewController* controller by tapping on *reply*
  **/
-@MainActor
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:24]: Since `TableNodeViewController` is annotated with `@MainActor` we have it on each inherited type.

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift [hunk 3]
```diff
@@ -7,6 +7,7 @@ import FlowCryptCommon
 import FlowCryptUI
 import Foundation
 
+@MainActor
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Inbox/InboxViewController.swift:10]: Here we need to put `@MainActor` since `ASDKViewController` is objc class.

File: FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift [hunk 4]
```diff
@@ -8,6 +8,7 @@
 
 import UIKit
 
+@MainActor
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: Each protocol intended to work with UI state should be marked with `@MainActor` to be sure that we work with it on UI thread.

Comment (tomholub) [inline FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: On a controller, wouldn't this cause some methods that make api calls to run on main? Or as long as we `await` these other methods/services, then the API call would not be on main?

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: It is possible but we should move such methods to services. I mean that view controller is something that interacts with view so we want to be sure that this happens on UI thread. That is why I want to have `@MainActor` on each controller.

Comment (tomholub) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: This is the danger I described earlier - if we just set it on the whole class, things may suddenly run on main that we didn't intend to. I'm not sure it's the best idea without properly studying how @ main actor works, ensuring that api requests are not on main in this situation:

```
@mainactor
class SomeViewController {

  fun handleTap() {
    Task {
       do {
          try await apiClient.someApiCall() // <-- does this run on main or not?
          handleGood()
        } catch {
          handleErr()
        }
    }
  }

  fun handleGood() {
  }

  fun handleErr() {
  }

}
```

Can you please study the docs and also step through this with debugger to make sure?

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: If we run task like this:
```
@MainActor
class SomeViewController {

	func handleTap() {
		print("\(Thread.current): handleTap()")
		Task {
			do {
				print("\(Thread.current): inside Task point 1")
				try await apiClient.someApiCall()
				print("\(Thread.current): inside Task point 2")
				handleGood()
			} catch {
				handleErr()
			}
		}
	}

	func handleGood() {
		print("\(Thread.current): handleGood()")
	}

	func handleErr() {
		print("\(Thread.current): handleErr()")
	}
}
```

Then according to documentation:
> Runs the given nonthrowing operation asynchronously as part of a new top-level task on behalf of the current actor.

So we run task on main thread because we are inside `@MainActor`, but async function may run internally on any other thread. So at "point 1" we are on main thread, but on "point 2" we could be on any other thread, it depends on `apiClient.someApiCall()`. This is the reason why we use `@MainActor`, to be sure that `handleGood()` will be executed on main thread.

On the other hand if we start task like this:
```
@MainActor
class SomeViewController {

	func handleTap() {
		print("\(Thread.current): handleTap()")
		Task.detached {
			do {
				print("\(Thread.current): inside Task point 1")
				try await self.apiClient.someApiCall()
				print("\(Thread.current): inside Task point 2")
				await self.handleGood()
			} catch {
				await self.handleErr()
			}
		}
	}

	func handleGood() {
		print("\(Thread.current): handleGood()")
	}

	func handleErr() {
		print("\(Thread.current): handleErr()")
	}
}
``` 

We have new top level task:
> Runs the given nonthrowing operation asynchronously as part of a new top-level task.

So we run task on another thread (no main), and in "point 1" we are not on main thread. But again, on "point 2" it is possible to be on new thread.

So it depends on how internally works async function.

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: Maybe we need to find out what we want to run on separate thread, like network requests (already implemented in `URLSession` by Apple), our JavaScript functions (Core is actor already), etc.

Comment (tomholub) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: Can we mark these api classes etc with something like BackgroundActor ? :-)

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: I need to check if it is possible to create our own annotations like this.

Comment (ivan-ushakov) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: Looks like there is no way to define your own annotations in Swift, so there is no way to have `@BackgroundActor`. On the other hand any user actor by default is "background".

Comment (tomholub) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: got it

Comment (tomholub) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: > Maybe we need to find out what we want to run on separate thread, like network requests (already implemented in URLSession by Apple), our JavaScript functions (Core is actor already), etc.

All API client classes, including Gmail API (which may not be using URLSession - not sure), and Core as you say. IMAP/SMTP client as well. So here the main thing to look into is Gmail and IMAP/SMTP.

File: FlowCrypt/Common UI/AttachmentManager.swift [hunk 5]
```diff
@@ -49,13 +50,19 @@ extension AttachmentManager: AttachmentManagerType {
             .sinkFuture(
```
Comment (sosnovsky) [inline FlowCrypt/Common UI/AttachmentManager.swift:50]: @tomholub I think we should use `async/await` here instead of Combine for code consistency across project, and for better threads handling with `@MainActor`, can be done in another issue

File: FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift (hunk 4 above)
Comment (sosnovsky) [reply FlowCrypt/Controllers/MessageList Extension/MsgListViewController.swift:11]: It's possible to create our own custom actors with `@globalActor` declaration, like
```swift
@globalActor
struct BackgroundActor {
...
}
```

But I think we don't need such `@BackgroundActor` declaration as Swift automatically runs `async/await` operations not on the main thread, so we just need to re-check our API calls to use `async`

**Review by sosnovsky — APPROVED** [review]
Works well ✅

File: FlowCrypt/Common UI/AttachmentManager.swift (hunk 5 above)
Comment (tomholub) [reply FlowCrypt/Common UI/AttachmentManager.swift:50]: Agree - I've asked @ekievsky to do it as part of #1031

**Comment by tomholub** [comment]
Then I'll merge this, and we make sure that we use actor for Gmail/IMAP/SMTP in another issue.

**Review by tomholub — APPROVED** [review]

File: FlowCrypt/Common UI/AttachmentManager.swift (hunk 5 above)
Comment (tomholub) [reply FlowCrypt/Common UI/AttachmentManager.swift:50]: Will also file another issue to look over the remaining ones after that, if any
