### PR TITLE
fix wasteful backup search in inbox on Gmail API

### LINKED ISSUE #309: fix wasteful backup search in inbox on Gmail API
I debugged the problem(s):

1) there are 5 search expressions - and it seems we make 5 API requests to gmail. This should not be the case, it should be just one search expression and one request with 4 ORs in it.
2) the search expressions are wrong for Gmail search. On my account I have no backups, but it downloads 137 emails! and then 73 attachments with 33mb of data
3) this above seems to take forever, which is why we got to this UI issue in the first place (that you fixed)
4) when it does finish, it was saying "Setup failed" which is a nonsensical error, it should have said "No backups found on this account" (I fixed)

Please address issues 1 and 2 as well

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/304#issuecomment-834435523_

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR fix wasteful backup search in inbox on Gmail API

close #309 
----------------------------------

**Tests**:
- Start working on `GmailService` tests
- Added mocks implementations for `GoogleUserServiceType` and `GmailBackupSearchQueryProviderType`

Screenshot 2021-06-17 at 23 25 53

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by tomholub — APPROVED** [review]
Code looks good, will test functionality manually now

**Review by tomholub — CHANGES_REQUESTED** [review]
This still does not address the issue. When I try it on my personal account, it shows:

```
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[Keychain][KeyChainService] LocalStorage.secureKeychainPrefix generating new: wFjxOWGVu77zZW4o"
"ℹ️[Keychain][KeyChainService] generateAndSaveStorageEncryptionKey"
"ℹ️[Js][Core] JsContext took 0.532 ms to start"
"ℹ️[App Start][GlobalRouter] Sign in with gmailLogin(<FlowCrypt.SignInViewController: 0x108059c00>)"
"ℹ️[App Start][GlobalRouter] proceed for session Optional(FlowCrypt.SessionType.google(...)"
"ℹ️[App Start][GoogleUserService] Renew session for google user"
"ℹ️ [Setup] searching for backups in inbox"
"🏷[GmailService] will begin searching for backups"
"🏷[GmailService] searching done, found 24 backup messages"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Fwd: Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Fwd: Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Problems with my Flowcrypt account\' with 1 attachments"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'FlowCrypt Feedback from ...@gmail.com\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Your FlowCrypt Backup\' with 2 attachments"
"🏷[GmailService] processing backup \'Fwd: Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Please Provide Assistance\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Your FlowCrypt Backup\' with 2 attachments"
"🏷[GmailService] processing backup \'FlowCrypt Feedback from ...@gmail.com\' with 1 attachments"
"🏷[GmailService] processing backup \'Fwd: Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Passphrase lost\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: FlowCrypt Feedback from ...@gmail.com\' with 3 attachments"
"🏷[GmailService] processing backup \'Pass phrase\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Problems with my Flowcrypt account\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Passphrase lost\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Your FlowCrypt Backup\' with 2 attachments"
"🏷[GmailService] processing backup \'Fwd: Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'FlowCrypt Feedback from connythorn19@gmail.com\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Your FlowCrypt Backup\' with 2 attachments"
"🏷[GmailService] processing backup \'FlowCrypt Feedback from ...@gmail.com\' with 1 attachments"
"🏷[GmailService] processing backup \'Re: Passphrase lost\' with 1 attachments"
"🏷[GmailService] downloading 30 attachments with possible backups in them"
"🏷[GmailService] downloaded 30 attachments that contain 2171kB of data"
"❗️[Js][Core] ------ js err -------\nCore parseKeys:\nTypeError: coreHost.log is not a function. (In \'coreHost.log(String(x))\', \'coreHost.log\' is undefined)\n_log\n\n\nasyncFunctionResume@[native code]\n[native code]\npromiseReactionJobWithoutPromise@[native code]\n------- end js err -----"
```

**Comment by tomholub** [comment]
Problems:
1) it's supposed to search for the text only in subject, but it actually searches the text anywhere in the email
2) it's supposed to search for backups from:me, to: me but these filters are missing, so it's picking up on emails that I've sent to others, or that others sent to me, which is not valid

**Comment by tomholub** [comment]
Btw you don't have to construct the search query manually. If you can supply a textual query, then use endpoint called `gmailBackupSearch` - just add a `Core.gmailBackupSearch` method. Input is `acctEmail` where you put the account email address, and back you get the constructed search query that you will know is correct.

https://github.com/FlowCrypt/flowcrypt-mobile-core/blob/b7d8d10bdd2b5c17e17ec03505801e8bf7e89073/source/mobile-interface/endpoints.ts#L224

**Comment by tomholub** [comment]
If you do prefer to construct this query in Swift anyway for some reason, then here is an exact test case to copy, the test case you wrote is too vague:

https://github.com/FlowCrypt/flowcrypt-mobile-core/blob/b7d8d10bdd2b5c17e17ec03505801e8bf7e89073/source/test.ts#L280

**Comment by Kharchevskyi** [comment]
@tomholub can you please check with query generated with `Core`

File: FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift [hunk 1]
```diff
@@ -8,15 +8,18 @@
...
-        return folderQuery + " " + searchExpressionQuery + " has:attachment"
+final class GmailBackupSearchQueryProvider: GmailBackupSearchQueryProviderType {
+    let core: Core
+
+    init(core: Core = .shared) {
+        self.core = core
+    }
+
+    func makeBackupQuery(for email: String) -> String? {
+        core.gmailBackupSearch(for: email)
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift:23]: I think this class became superfluous - the only actual code here is `core.gmailBackupSearch(for: email)` which could be called from one level up directly.

File: FlowCrypt/Core/Core.swift [hunk 2]
```diff
@@ -147,6 +147,12 @@ final class Core: KeyDecrypter {
         }
     }
 
+    func gmailBackupSearch(for email: String) -> String? {
+        let response = try? call("gmailBackupSearch", jsonDict: ["acctEmail": email], data: nil)
+        let result = try? response?.json.decodeJson(as: GmailBackupSearchResponse.self)
+        return result?.query
+    }
```
Comment (tomholub) [inline FlowCrypt/Core/Core.swift:154]: For consistency,  I'd probably write this same as the other methods without the question marks, and return a `String`.

If this is inapropriate, then we should (in another PR) rethink error handling in the whole class.

**Review by tomholub — COMMENTED** [review]
This looks like it will work - will test

File: FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift (hunk 1 above)
Comment (Kharchevskyi) [reply FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift:23]: True, it was done for testing purposes 
`GmailService` initialised with `GmailBackupSearchQueryProviderType` instead of being initialised with `Core` class which is a shared instance. 

What do you think of making `call` functions from `Core` class as public functions, and spread some functionality to other classes? In this case Core will be kind of interface for communicating. 

And for instance this `GmailBackupSearchQueryProvider` will call `core.call(....)`
```
 let response = try? core.call("gmailBackupSearch", jsonDict: ["acctEmail": email], data: nil)
 let result = try? response?.json.decodeJson(as: GmailBackupSearchResponse.self)
 return result?.query
```

Comment (tomholub) [reply FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift:23]: I'm not sure about calling javascript manually this way - I was hoping to contain all javascript-calling things in a single class for ease of maintenance.

If having a `GmailBackupSearchQueryProviderType` helps you with tests, then we can leave it as is.

Comment (tomholub) [reply FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift:23]: I hope to not mix javascript and swift too much across the codebase - I I'd prefer to contain core calling functionality in core. However, I don't care too much if it's one class for all methods or if it's one class per method, if that helps you somehow.

Comment (Kharchevskyi) [reply FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift:23]: Still `Core` class will handle all javascript logic, but logic of parsing and returning client needed data object will be handled in separate classes. 
But no problems, I will keep it as is.

Comment (tomholub) [reply FlowCrypt/Functionality/Mail Provider/SearchMessage Provider/GmailSearchExpressionGenerator.swift:23]: I'd prefer to not do that outside of a contained space (the code is too low level to spread around the app). That could be either one `Core` class, or it could be some sort of `CoreGmailBackupSearch` class, and so on one per method, all in the same folder.

**Review by tomholub — APPROVED** [review]
Code looks good. Will test

**Comment by tomholub** [comment]
This worked for the search, but after entering pass phrase, it sent me back to splash screen. Log:

```
"ℹ️[Keychain][KeyChainService] LocalStorage.secureKeychainPrefix generating new: TyvDJ6VPktNBrGQO"
"ℹ️[Keychain][KeyChainService] generateAndSaveStorageEncryptionKey"
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[Js][Core] JsContext took 0.288 ms to start"
"ℹ️[App Start][GlobalRouter] Sign in with gmailLogin(<FlowCrypt.SignInViewController: 0x15802b400>)"
"ℹ️[App Start][GlobalRouter] proceed for session Optional(Google tom@flowcrypt.com Tom J. H.)"
"ℹ️[App Start][GoogleUserService] Renew session for google user"
"ℹ️[Setup][SetupInitialViewController] Changed to new state searching"
"ℹ️[Setup][SetupInitialViewController] Searching for backups in inbox"
"🏷[GmailService] will begin searching for backups"
"🏷[GmailService] searching done, found 2 backup messages"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] downloading 2 attachments with possible backups in them"
"🏷[GmailService] downloaded 2 attachments that contain 7kB of data"
"ℹ️[Setup][SetupInitialViewController] Finish searching for backups in inbox"
"ℹ️[Setup][SetupInitialViewController] 2 key backups found in inbox"
"ℹ️[Core][KeyMethods] Filtered. decryptedKey = nil"
"ℹ️[PassPhraseStorage] Save to storage 0C9C2E6A4D273C6F"
"ℹ️[App Start][GlobalRouter] proceed for session nil"
```

**Comment by Kharchevskyi** [comment]
I have added some logs. Can you please try to reproduce this issue once again?

**Comment by tomholub** [comment]
"ℹ️[Keychain][KeyChainService] LocalStorage.secureKeychainPrefix generating new: 6D1zqclvuM3iBVUz"
"ℹ️[Keychain][KeyChainService] generateAndSaveStorageEncryptionKey"
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[AppStart] Initialize application with session nil"
"ℹ️[AppStart] Setup Core"
"ℹ️[Js][Core] JsContext took 0.271 ms to start"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[AppStart] User is not logged in -> signIn"
"ℹ️[App Start][GlobalRouter] Sign in with gmailLogin(<FlowCrypt.SignInViewController: 0x105069400>)"
"ℹ️[App Start][GlobalRouter] proceed for session Optional(Google ... Tom J. H.)"
"ℹ️[AppStart] Initialize application with session Optional(Google ... Tom J. H.)"
"ℹ️[AppStart] Setup Core"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[App Start][GoogleUserService] Renew session for google user"
"ℹ️ UserId = current user id"
"ℹ️[AppStart] User with session Google ... Tom J. H. -> setupFlow"
"ℹ️[Setup][SetupInitialViewController] Changed to new state searching"
"ℹ️[Setup][SetupInitialViewController] Searching for backups in inbox"
"🏷[GmailService] will begin searching for backups"
"🏷[GmailService] searching done, found 2 backup messages"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] downloading 2 attachments with possible backups in them"
"🏷[GmailService] downloaded 2 attachments that contain 7kB of data"
"ℹ️[Setup][SetupInitialViewController] Finish searching for backups in inbox"
"ℹ️[Setup][SetupInitialViewController] 2 key backups found in inbox"
"ℹ️[Setup][SetupBackupsViewController] Start recoverAccount with 2"
"ℹ️[Core][KeyMethods] Filtered. decryptedKey = nil for key 84AE4C8A1923A36A"
"ℹ️[Setup][SetupBackupsViewController] matchingKeyBackups = 1"
"ℹ️[PassPhraseService] Save to storage 0C9C2E6A4D273C6F"
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[AppStart] Initialize application with session nil"
"ℹ️[AppStart] Setup Core"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[AppStart] User is not logged in -> signIn"

**Comment by Kharchevskyi** [comment]
thanks for reporting, will investigate this

**Comment by Kharchevskyi** [comment]
@tomholub is this issue for all users? I have added few more logs, can you please try once more with `Tom J. H.` account and maybe with some other account? For example with `cryptup.tester@gmail.com`?

**Comment by tomholub** [comment]
@Kharchevskyi I'll take a look. Please edit your comment per the above bot. Eg you can say `cryptup.tester` account.

**Comment by tomholub** [comment]
That's not what I meant. The comment was asking you to redact email address from your earlier comment here https://github.com/FlowCrypt/flowcrypt-ios/pull/355#issuecomment-869174974

**Comment by tomholub** [comment]
This is a public repo, we don't want email addresses mentioned publicly here.

**Comment by tomholub** [comment]
my own account:

```
"ℹ️[UserAccountService] Clean up sessions"
"ℹ️[Keychain][KeyChainService] LocalStorage.secureKeychainPrefix generating new: ueAHpE1Bu1opbPk9"
"ℹ️[Keychain][KeyChainService] generateAndSaveStorageEncryptionKey"
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[AppStart] Initialize application with session nil"
"ℹ️[AppStart] Setup Core"
"ℹ️[Js][Core] JsContext took 0.265 ms to start"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[AppStart] User is not logged in -> signIn"
"ℹ️[App Start][GlobalRouter] Sign in with gmailLogin(<FlowCrypt.SignInViewController: 0x15c065200>)"
"ℹ️[App Start][GlobalRouter] proceed for session Optional(Google ... Tom J. H.)"
"ℹ️[AppStart] Initialize application with session Optional(Google ... Tom J. H.)"
"ℹ️[AppStart] Setup Core"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[App Start][GoogleUserService] Renew session for google user"
"ℹ️ UserId = current user id"
"ℹ️[AppStart] User with session Google ... Tom J. H. -> setupFlow"
"ℹ️[Setup][SetupInitialViewController] Changed to new state searching"
"ℹ️[Setup][SetupInitialViewController] Searching for backups in inbox"
"🏷[GmailService] will begin searching for backups"
"🏷[GmailService] searching done, found 2 backup messages"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] downloading 2 attachments with possible backups in them"
"🏷[GmailService] downloaded 2 attachments that contain 7kB of data"
"ℹ️[Setup][SetupInitialViewController] Finish searching for backups in inbox"
"ℹ️[Setup][SetupInitialViewController] 2 key backups found in inbox"
"ℹ️[Setup][SetupBackupsViewController] Start recoverAccount with 2"
"ℹ️[Core][KeyMethods] Filtered. decryptedKey = nil for key 84AE4C8A1923A36A"
"ℹ️[Setup][SetupBackupsViewController] matchingKeyBackups = 1"
"ℹ️[PassPhraseService] Save to storage 0C9C2E6A4D273C6F"
"ℹ️[KeyDataStorage] Add keys for [\"Human at FlowCrypt <...>\"]"
"ℹ️[UserAccountService] Clean up sessions"
"ℹ️[UserAccountService] User session to clean up ..."
"ℹ️[UserAccountService] Log out user with ..."
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[AppStart] Initialize application with session nil"
"ℹ️[AppStart] Setup Core"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[AppStart] User is not logged in -> signIn"
```

**Comment by tomholub** [comment]
compatibility account - worked normally:

```

"ℹ️[App Start][GlobalRouter] Sign in with gmailLogin(<FlowCrypt.SignInViewController: 0x15c0dfc00>)"
"ℹ️[App Start][GlobalRouter] proceed for session Optional(Google ... FlowCrypt Compatibility)"
"ℹ️[AppStart] Initialize application with session Optional(Google ... FlowCrypt Compatibility)"
"ℹ️[AppStart] Setup Core"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[App Start][GoogleUserService] Renew session for google user"
"ℹ️ UserId = current user id"
"ℹ️[AppStart] User with session Google ... FlowCrypt Compatibility -> setupFlow"
"ℹ️[Setup][SetupInitialViewController] Changed to new state searching"
"ℹ️[Setup][SetupInitialViewController] Searching for backups in inbox"
"🏷[GmailService] will begin searching for backups"
"🏷[GmailService] searching done, found 3 backup messages"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] processing backup \'Your FlowCrypt Backup\' with 1 attachments"
"🏷[GmailService] downloading 3 attachments with possible backups in them"
"🏷[GmailService] downloaded 3 attachments that contain 20kB of data"
"ℹ️[Setup][SetupInitialViewController] Finish searching for backups in inbox"
"ℹ️[Setup][SetupInitialViewController] 3 key backups found in inbox"
"ℹ️[Setup][SetupBackupsViewController] Start recoverAccount with 3"
"ℹ️[Core][KeyMethods] Filtered. decryptedKey = nil for key 7FDE685548AEA788"
"ℹ️[Core][KeyMethods] Filtered. decryptedKey = nil for key ADAC279C95093207"
"ℹ️[Setup][SetupBackupsViewController] matchingKeyBackups = 1"
"ℹ️[PassPhraseService] Save to storage ADAC279C95093207"
"ℹ️[KeyDataStorage] Add keys for [\"FlowCrypt Compatibility <...>\"]"
"ℹ️[UserAccountService] Clean up sessions"
"ℹ️[App Start][GlobalRouter] proceed for session nil"
"ℹ️[AppStart] Initialize application with session nil"
"ℹ️[AppStart] Setup Core"
"ℹ️[AppStart] Setup Migration"
"ℹ️[AppStart] Setup Session"
"ℹ️[App Start][GoogleUserService] Renew session for google user"
"ℹ️[AppStart] Setup finished -> mainFlow"
"ℹ️[GmailService] Skip category label with CATEGORY_FORUMS"
"ℹ️[GmailService] Skip category label with CATEGORY_UPDATES"
"ℹ️[GmailService] Skip category label with CATEGORY_PERSONAL"
"ℹ️[GmailService] Skip category label with CATEGORY_PROMOTIONS"
"ℹ️[GmailService] Skip category label with CATEGORY_SOCIAL"
```

**Comment by Kharchevskyi** [comment]
> my own account:

probably issue is here `"ℹ️[UserAccountService] Clean up sessions"`. Thank's for the logs

File: FlowCrypt.xcodeproj/xcshareddata/xcschemes/FlowCrypt.xcscheme [hunk 3]
```diff
@@ -7,7 +7,7 @@
       buildImplicitDependencies = "YES">
       <BuildActionEntries>
          <BuildActionEntry
-            buildForTesting = "NO"
+            buildForTesting = "YES"
```
Comment (tomholub) [inline FlowCrypt.xcodeproj/xcshareddata/xcschemes/FlowCrypt.xcscheme:10]: Need to keep track of this to not merge this change

**Comment by tomholub** [comment]
Sent to your email

**Comment by tomholub** [comment]
Copying from email:

> You may completely ignore the email addresses listed inside of the PGP keys. They don't have to match the account they are set up for.

**Review by tomholub — COMMENTED** [review]
Code looks ok - I'm not at my mac until wednesday to test it. I'll merge it and create another issue in case it misbehaves.

**Comment by tomholub** [comment]
However tests are failing - can you take a look?

**Comment by tomholub** [comment]
This fixed the issue, thank you

**Comment by tomholub** [comment]
@Kharchevskyi the CI still cannot build it, I've updated from master

**Comment by tomholub** [comment]
also #381 was observed on this PR

**Comment by Kharchevskyi** [comment]
Last commits should also fix #381

**Review by tomholub — APPROVED** [review]
