### PR TITLE
#1524 Handle parse key from EKM gracefully

### LINKED ISSUE #1524: ensure to properly parse each received key from EKM
> For `test 3: EKM key update errors handled gracefully`, when we want to parse broken key with `core.parseKeys` it doesn't return error but return 0 parsed keys.
> 
> > change EKM mock to start returning a broken key (for example, only return the first half of the armored key text)
> > restart the app
> > _observe that the app shows a modal during startup Could not update keys from EKM due to error: and followed by whatever error happened._

That's odd. In this situation, the parsing should fail. It should not swallow keys silently.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/841#issuecomment-1109067112_

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR ensured to properly parse each received key from EKM.

close #1524 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests will be added later (issue #841)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
@sosnovsky Please review this. This is blocking #841.
By the way, I can see that UI tests success in local but fail in semaphoreci. Do you have idea why?

File: FlowCrypt/Controllers/Setup/SetupInitialViewController.swift [hunk 1]
```diff
@@ -158,30 +158,28 @@ extension SetupInitialViewController {
...
+                            }
+                        )
+                    } else if ekmError == .keysAreNotDecrypted {
+                        showAlert(
+                            message: ekmError.errorMessage,
+                            onOk: { [weak self] in
+                                self?.signOut()
+                            }
+                        )
+                    }
```
Comment (sosnovsky) [inline FlowCrypt/Controllers/Setup/SetupInitialViewController.swift:182]: It'll be better to use `switch` here, as currently we don't handle 2 `EmailKeyManagerApiError` cases.

**Comment by sosnovsky** [comment]
> By the way, I can see that UI tests success in local but fail in semaphoreci. Do you have idea why?

Some tests are failing locally for me too, trying to fix them in my other PR - https://github.com/FlowCrypt/flowcrypt-ios/pull/1523

Reviewing this PR now 👀

**Comment by ioanmo226** [comment]
> > By the way, I can see that UI tests success in local but fail in semaphoreci. Do you have idea why?
> 
> Some tests are failing locally for me too, trying to fix them in my other PR - #1523
> 
> Reviewing this PR now 👀

ok, got it

File: FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift [hunk 2]
```diff
@@ -68,22 +68,25 @@ actor EmailKeyManagerApi: EmailKeyManagerApiType {
...
+        var keys: [KeyDetails] = []
+        for privateKey in decryptedPrivateKeysResponse.privateKeys {
+            let parsedPrivateKey = try await core.parseKeys(armoredOrBinary: privateKey.decryptedPrivateKey.data())
+            // todo - check that parsedPrivateKeys don't contain public keys
+            let isKeyDecrypted = parsedPrivateKey.keyDetails
+                .compactMap { $0.isFullyDecrypted }
+            if isKeyDecrypted.contains(false) {
+                throw EmailKeyManagerApiError.keysAreNotDecrypted
+            }
+            if parsedPrivateKey.keyDetails.count < 1 {
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift:83]: Instead of `count < 1` it'll be better to use `parsedPrivateKey.keyDetails.isEmpty`

**Review by sosnovsky — CHANGES_REQUESTED** [review]

**Review by sosnovsky — DISMISSED** [review]

File: FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift [hunk 3]
```diff
@@ -68,22 +68,25 @@ actor EmailKeyManagerApi: EmailKeyManagerApiType {
...
+            let parsedPrivateKey = try await core.parseKeys(armoredOrBinary: privateKey.decryptedPrivateKey.data())
+            // todo - check that parsedPrivateKeys don't contain public keys
+            let isKeyDecrypted = parsedPrivateKey.keyDetails
+                .compactMap { $0.isFullyDecrypted }
+            if isKeyDecrypted.contains(false) {
+                throw EmailKeyManagerApiError.keysAreNotDecrypted
+            }
+            if parsedPrivateKey.keyDetails.isEmpty {
+                throw EmailKeyManagerApiError.keysAreInvalid
+            }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Remote Private Key Services/EmailKeyManagerApi.swift:85]: Here, we always expect exactly one key in each `decryptedPrivateKey`. Therefore `count !== 1` would be more appropriate.

**Review by tomholub — APPROVED** [review]

**Comment by ioanmo226** [comment]
FYI no new changes. Just merged Roma's changes to save UI test run time.

File: FlowCrypt/Controllers/Setup/SetupInitialViewController.swift [hunk 4]
```diff
@@ -158,30 +158,32 @@ extension SetupInitialViewController {
...
+                    case .keysAreNotDecrypted, .keysAreInvalid:
+                        showAlert(
+                            message: errorMessage,
+                            onOk: { [weak self] in
+                                self?.signOut()
+                            }
+                        )
+                    case .noPrivateKeysUrlString:
+                        break
+                    }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupInitialViewController.swift:186]: All of the situations in this catch could be handled exactly the same way, with an `ok` and `retry` button as follows:

```swift
                        showRetryAlert(
                            message: errorMessage,
                            onRetry: { [weak self] in
                                self?.state = .fetchingKeysFromEKM
                            },
                            onOk: { [weak self] in
                                self?.signOut()
                            }
                        )
```

That means we probably wouldn't need `if let ekmError = error as? EmailKeyManagerApiError {` and we also wouldn't need the switch. It can all be handled the same.

Comment (tomholub) [reply FlowCrypt/Controllers/Setup/SetupInitialViewController.swift:186]: I'm unsure why this handler evolved to have three ways to handle the error, I think one way is enough, as long as it prints the appropriate error message.

Comment (tomholub) [reply FlowCrypt/Controllers/Setup/SetupInitialViewController.swift]: Yeah, that's how it was written, but there wasn't any reason for it that I know.

Comment (ioanmo226) [reply FlowCrypt/Controllers/Setup/SetupInitialViewController.swift]: Got it

**Review by tomholub — APPROVED** [review]

**Comment by tomholub** [comment]
The most obvious examples are passing tests on PR that fail once merged to master. Those situations should be documented as issues so that someone will look into improving them, else eventually we'll be stuck re-running tests forever.

**Comment by ioanmo226** [comment]
@tomholub Right.
We should improve CheckInboxPaginationAfterLoadingAllEmails test first. It fails 100% in my local as it takes 1-2 seconds to load list.
