### PR TITLE
issue #93 fix sender without pgp + refactor compose with Promise/await

### LINKED ISSUE #93: sending to someone who doesn't have pubkey
Regression

Should be showing a proper error, currently showing "Could not compose message"

### PR DESCRIPTION
**Pull request by tomholub**
close #93 / 3 hours

### CODE REVIEW

File: FlowCrypt/Common/AttesterApi.swift [hunk 1]
```diff
@@ -13,24 +13,25 @@ final class AttesterApi {
 
     static let shared: AttesterApi = AttesterApi()
 
-    private let url = "https://flowcrypt.com/attester/"
+    private static let url = "https://flowcrypt.com/attester/"
```
Comment (tomholub) [inline FlowCrypt/Common/AttesterApi.swift]: I added static so that `lookupEmail` does not have to do the `[weak self]` dance.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 2]
```diff
@@ -147,23 +148,7 @@ extension ComposeViewController {
     }
 
     @objc private func handleSendTap() {
-        sendMessage()
-    }
-
-    private func isInputValid() -> Bool {
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift]: I moved this to where it's actually used.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 3]
```diff
@@ -186,68 +172,57 @@ extension ComposeViewController {
...
         showSpinner(Constants.sending)
 
-        attesterApi.lookupEmail(email: email)
-            .then(on: .main) { [weak self] recipientPub in
-                self?.handleLookupEmail(result: recipientPub, message: text, email: email)
-            }
-            .catch(on: .main) { [weak self] error in
-                self?.handleSend(error: error)
-            }
+        Promise<Void> { [weak self] in
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift]: Here a security reviewer can get an easy overview, in a few lines.

File: FlowCrypt/Core/Core.swift [hunk 4]
```diff
@@ -7,7 +7,6 @@ import JavaScriptCore
 enum CoreError: Error {
     case exception(String)
     case notReady(String)
-    case undefined
```
Comment (tomholub) [inline FlowCrypt/Core/Core.swift]: Not sure what `undefined` error would be for, the `Core` library does not need it.
