### PR TITLE
Crash when moving email to trash

### LINKED ISSUE #1076: crash when moving email to trash
image

### PR DESCRIPTION
**Pull request by ivan-ushakov**
close #1076

----------------------------------

**Tests** _(delete all except exactly one)_:
- Does not need tests (refactor only, docs or internal changes)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/ObjC/ObjException.m [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+//  ObjException.m
+//  FlowCrypt
+//
+//  Created by  Ivan Ushakov on 25.01.2022
+//  Copyright © 2017-present FlowCrypt a. s. All rights reserved.
+//
+
+#import "ObjException.h"
+
+@implementation ObjException
```
Comment (sosnovsky) [inline FlowCrypt/ObjC/ObjException.m:11]: It'll be better to call it `ObjcException`, as `ObjException` doesn't make it clear that we're catching exceptions from Objective C.

File: FlowCrypt/ObjC/ObjException.m [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+
++ (BOOL)catchException:(void(^)(void))tryBlock error:(__autoreleasing NSError **)error {
+    @try
+    {
+        tryBlock();
+        return YES;
+    }
+    @catch (NSException *exception)
+    {
+        *error = [[NSError alloc] initWithDomain:exception.name code:0 userInfo:exception.userInfo];
```
Comment (sosnovsky) [inline FlowCrypt/ObjC/ObjException.m:21]: There is updated implementation on stackoverflow, which makes error message more  detailed - https://stackoverflow.com/a/61825487/3091318

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift [hunk 3]
```diff
@@ -452,10 +452,22 @@ extension InboxViewController: MsgListViewController {
                 tableNode.reloadData()
             } else {
                 state = .fetched(.byNumber(total: newTotalNumber))
-                tableNode.deleteRows(at: [IndexPath(row: index, section: 0)], with: .left)
+                do {
+                    try ObjException.catch {
+                        self.tableNode.deleteRows(at: [IndexPath(row: index, section: 0)], with: .left)
+                    }
+                } catch {
+                    logger.logError("Failed to remove message at \(index) in fetched state")
```
Comment (sosnovsky) [inline FlowCrypt/Controllers/Inbox/InboxViewController.swift:460]: Let's also add catched error message here, so it'll be `"Failed to remove message at \(index) in fetched state: \(error)"`

**Review by sosnovsky — CHANGES_REQUESTED** [review]

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift [hunk 4]
```diff
@@ -452,10 +452,22 @@ extension InboxViewController: MsgListViewController {
                 tableNode.reloadData()
             } else {
                 state = .fetched(.byNumber(total: newTotalNumber))
-                tableNode.deleteRows(at: [IndexPath(row: index, section: 0)], with: .left)
+                do {
+                    try ObjcException.catch {
```
Comment (Kharchevskyi) [inline FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: Can you please explain how is this fix related to the crash fix?

Comment (Kharchevskyi) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: It looks like there is an issue related to the index of the row that we try to update

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift [hunk 5]
```diff
@@ -452,10 +452,22 @@ extension InboxViewController: MsgListViewController {
...
+                        self.tableNode.deleteRows(at: [IndexPath(row: index, section: 0)], with: .left)
```
Comment (Kharchevskyi) [inline FlowCrypt/Controllers/Inbox/InboxViewController.swift:457]: Data source for table node should be updated with correct amount of `inboxInput` then reload should be performed.

**Review by Kharchevskyi — CHANGES_REQUESTED** [review]

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift (hunk 4 above)
Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: As @tomholub said, we want to avoid having crash here. Even if issue is still here, we should not crash.

Comment (Kharchevskyi) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: Can we have an issue to solve the root cause of the crash?

Comment (tomholub) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: absolutely. Let's solve it in this PR as well.

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift (hunk 5 above)
Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:457]: Data source is updated above:
```
inboxInput.remove(at: index)
```
We could reload table node with `reloadData()`, but crash means that we are in invalid state. We could move from index to some kind of message ID. 

But I guess that this PR is more about handling Objc exceptions in Swift.

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift (hunk 4 above)
Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: Since all UI is async with Texture, I guess that using message index is unsafe. We should move to message ID, as this is the only way to know that message we want to delete is the same message.

Comment (Kharchevskyi) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:456]: Would suggest to investigate root cause of the issue. 

Also if there was only one message before moving to trash we need to update whole state of the controller.

File: FlowCrypt/Controllers/Inbox/InboxViewController.swift (hunk 5 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:457]: While originally it was indeed primary about handling of ObjC exceptions, that was in part because we didn't know any better.

If the actual root cause of this exception can be fixed, that is even better and more appropriate. Both should be done.

Comment (sosnovsky) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:457]: I think it's something more specific than just updating data source, as this crash happens very rarely.
Implementing ObjC exception handling should help us to find root cause of this issue.

May be switching from index to message id (as @ivan-ushakov proposed) will fix this crash, but we can't be 100% sure as currently we're not able to reproduce this issue.

Comment (tomholub) [reply FlowCrypt/Controllers/Inbox/InboxViewController.swift:457]: If the goal is to collect more information about the crash, I suppose we should have it show a modal similar to other crash scenarios? Then some user may take a screenshot and send it to us for debugging.

As currently, it will just be logged then forgotten.

**Review by sosnovsky — APPROVED** [review]
I think it's a good solution for now - app won't crash if this issue occurs again and users will get alert with error message.

**Comment by ivan-ushakov** [comment]
@Kharchevskyi are you agree with current approach? We will try to track down the cause of the crash with that alerts and also prevent unhandled exception to crash app.

**Comment by Kharchevskyi** [comment]
@ivan-ushakov sure, no objections 👍

**Review by Kharchevskyi — APPROVED** [review]

**Review by sosnovsky — APPROVED** [review]
