### PR TITLE
#2183 Blind carbon copy leak fix

### LINKED ISSUE #2183: Blind carbon copy leak
for more information, please see: https://github.com/FlowCrypt/flowcrypt-security/issues/223

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed blind carbon copy leak issue

close #2183 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
typo in title and deception too

**Comment by ioanmo226** [comment]
Fixed

File: FlowCrypt/Core/CoreTypes.swift [hunk 1]
```diff
@@ -139,13 +139,13 @@ struct SendableMsg: Equatable {
 }
 
 extension SendableMsg {
-    func copy(body: SendableMsgBody, atts: [Attachment], pubKeys: [String]?) -> SendableMsg {
+    func copy(body: SendableMsgBody, atts: [Attachment], pubKeys: [String]?, bcc: [String]) -> SendableMsg {
```
Comment (sosnovsky) [inline FlowCrypt/Core/CoreTypes.swift:142]: I think it'll be better to use `includeBcc: Bool = true` param, instead of `bcc: [String]`.
So in common case we won't need to pass additional `bcc` array. And if `bcc` should be removed - you just set `includeBcc: false` parameter.

File: appium/api-mocks/apis/fes/fes-endpoints.ts [hunk 2]
```diff
@@ -69,13 +69,28 @@ export const getMockFesEndpoints = (mockConfig: MockConfig, fesConfig: FesConfig
...
-        authenticate(req);
-        expectContains(body, '"from":"user@disablefesaccesstoken.test:8001"');
-        return { url: `${mockConfig}/message/FES-MOCK-MESSAGE-ID` };
+        const match = String(body).match(/Content-Type: application\/json\s*\n\s*(\{.*\})/);
+
+        if (!match) {
+          throw new FesHttpErr('Bad request', Status.BAD_REQUEST);
+        }
+        const contentType = JSON.parse(match[0]);
+        const { associateReplyToken, to, cc, bcc } = contentType;
```
Comment (sosnovsky) [inline appium/api-mocks/apis/fes/fes-endpoints.ts:78]: It looks strange when `contentType` contains recipients and reply token, let's call it `messageData`

File: appium/api-mocks/apis/fes/fes-endpoints.ts [hunk 3]
```diff
@@ -69,13 +69,28 @@ export const getMockFesEndpoints = (mockConfig: MockConfig, fesConfig: FesConfig
...
+          if (toCheck) expect(to).toBe(toCheck);
+          if (ccCheck) expect(cc).toBe(ccCheck);
+          if (bccCheck) expect(bcc).toBe(bccCheck);
+        }
+
+        return {
+          url: `https://flowcrypt.com/shared-tenant-fes/message/6da5ea3c-d2d6-4714-b15e-f29c805e5c6a`,
+          externalId: 'FES-MOCK-EXTERNAL-ID',
+          emailToExternalIdAndUrl: {},
+        };
```
Comment (sosnovsky) [inline appium/api-mocks/apis/fes/fes-endpoints.ts:93]: Are `externalId` and `emailToExternalIdAndUrl` properties needed here? Didn't find any usage of them in the code.

**Review by sosnovsky — COMMENTED** [review]
Works well 👍

File: FlowCrypt/Core/CoreTypes.swift (hunk 1 above)
Comment (ioanmo226) [reply FlowCrypt/Core/CoreTypes.swift:142]: Sounds good!

File: appium/api-mocks/apis/fes/fes-endpoints.ts (hunk 2 above)
Comment (ioanmo226) [reply appium/api-mocks/apis/fes/fes-endpoints.ts:78]: Ok

File: appium/api-mocks/apis/fes/fes-endpoints.ts (hunk 3 above)
Comment (ioanmo226) [reply appium/api-mocks/apis/fes/fes-endpoints.ts:93]: It was copied from browser extension source code :-)

**Review by sosnovsky — APPROVED** [review]
