### PR TITLE
#1120 Fix inbox items order

### LINKED ISSUE #1120: wrong ordering of items in inbox
visible on e2e account

@tomholub check this pls
Screenshot 2021-11-30 at 13 30 03

_Originally posted by @fcvakintos in https://github.com/FlowCrypt/flowcrypt-ios/issues/959#issuecomment-982549799_

should be ordered by date descending

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR fixes wrong messages order on Inbox screen

issue #1120

----------------------------------

**Tests** _(delete all except exactly one)_:
- Difficult to test (explain why) - messages list on test account can change in the future, so it's not possible to get exact date of the last inbox message

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Controllers/Inbox/InboxProviders.swift [hunk 1]
```diff
@@ -50,11 +50,16 @@ class InboxMessageListProvider: InboxDataProvider {
 
     override func fetchInboxItems(using context: FetchMessageContext, userEmail: String) async throws -> InboxContext {
         let result = try await provider.fetchMessages(using: context)
-        let inboxData = result.messages.map { InboxRenderable(message: $0) }
+
+        let inboxData = result.messages
+            .sorted(by: { $0.date > $1.date })
+            .map(InboxRenderable.init)
```
Comment (tomholub) [inline FlowCrypt/Controllers/Inbox/InboxProviders.swift:56]: I was hoping to avoid doing that (because I want to be able to change order by sending a different parameter to Gmail list fetch, and not having to order in two places - always once in Gmail API and once manually..).

Do the messages from Gmail API list come correctly or wrongly ordered?

Comment (sosnovsky) [reply FlowCrypt/Controllers/Inbox/InboxProviders.swift]: I removed additional sorting here, as API response returns right order.

**Review by tomholub — APPROVED** [review]
:+1:
