### PR TITLE
#1163 Add ui test for wrong error format

### LINKED ISSUE #1163: write appium test that returns FES mock error with wrong error format
currently the app gets confused

should still show that it was a 400 from FES url

### PR DESCRIPTION
**Pull request by sosnovsky**
This PR adds ui test for handling FES errors with wrong format.

close #1163

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCryptCommon/Extensions/ErrorExtensions.swift [hunk 1]
```diff
@@ -14,7 +14,9 @@ public extension Error {
         case let self as CustomStringConvertible:
             return String(describing: self)
         default:
-            return localizedDescription
+            return localizedDescription.trimmingCharacters(
+                in: CharacterSet(charactersIn: "\"") // remove quotes from error message
+            )
```
Comment (tomholub) [inline FlowCryptCommon/Extensions/ErrorExtensions.swift:19]: I imagine the quotes could sometimes be meaningful in error messages, like quoting some wrong input. Which may eg be empty and without quotes, that would be difficult to describe

File: appium/api-mocks/apis/fes/fes-endpoints.ts [hunk 2]
```diff
@@ -70,7 +76,11 @@ export const getMockFesEndpoints = (
 
 const throwErrorIfConfigSaysSo = (config: FesConfig) => {
   if (config.returnError) {
-    throw new FesHttpErr(config.returnError.message, config.returnError.code);
+    if (config.returnError.format == "wrong-text") {
+      throw new FesPlainHttpErr(config.returnError.message, config.returnError.code);
+    } else {
+      throw new FesHttpErr(config.returnError.message, config.returnError.code);
+    }
```
Comment (tomholub) [inline appium/api-mocks/apis/fes/fes-endpoints.ts:83]: Here please make a if-else that == `wrong-json` and it would return a json of a wrong format for example `{"wrongFieldError": {"wrongFieldCode": 400, "wrongFieldMessage": "wrong format"}}`

That will be returned if you put `returnError: {  code: 400, message: "wrong format", format: "wrong-json" }` in config.

Comment (tomholub) [reply appium/api-mocks/apis/fes/fes-endpoints.ts:83]: Then write one more test (or extend the newly added test - eg you can change config and restart app) that also tests the wrong-json format.

**Review by tomholub — COMMENTED** [review]
Looks good - there is also one more thing to test

File: FlowCryptCommon/Extensions/ErrorExtensions.swift (hunk 1 above)
Comment (sosnovsky) [reply FlowCryptCommon/Extensions/ErrorExtensions.swift:19]: It removes quotes only in the beginning and end of the string, so `"some client err"` becomes `some client err`.
I added this trimming because quotes were automatically added to the error message from `wrong-text` test.

There can be an issue if we have quotes only on 1 side, like `wrong format: "some text"`, it'll be transformed into `wrong format: "some text`.

I can leave as it was before - without trimming, or improve current logic to better handle such cases, what do you prefer?

Comment (tomholub) [reply FlowCryptCommon/Extensions/ErrorExtensions.swift:19]: I think we can do without trimming. Thanks!

**Review by tomholub — APPROVED** [review]
