### PR TITLE
issue 852 no prv found - added logs + refactor + pass phrase for signing

### LINKED ISSUE #681: clarity of encryptAndSend exception handling
This needs additional scrutiny in another issue. Error may be thrown by either composeEmail or sendMail. But either way we are throwing `gatewayError`. It should be balled `composeError` (and make sure it can handle both types of errors)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/650#discussion_r730132242_

### LINKED ISSUE #819: pass phrase not remembered when sending email
> Hi Tom,
> 
> When I initially set up my FlowCrypt on my iPhone and
> iPad I set the password to be saved temporarily. Everytime
> I encrypt or decrypt a message I''m required to reenter my
> password. I thought that setting the password to temporary
> would be per session and when I quit FlowCrypt IOS the
> password would then be deleted.
> 
> Thanks,

my response

> thanks for the feedback! You're right - the pass phrase gets remembered when you enter it to view an encrypted message, but it doesn't get remembered when you enter it to send a message. That's a bug - thank you for reporting it. We'll get it fixed.

### LINKED ISSUE #849: crash feedback version 0.3.2
[testflight_feedback 032.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7444601/testflight_feedback.032.zip)

### LINKED ISSUE #851: cannot find recipient public key when reply
when I write a new email to @sosnovsky then it finds public key. Saves it in contacts.

When I reply to @sosnovsky it cannot find it (gray). Even though already in contacts.

### LINKED ISSUE #852: race cond: Core.parseKeys returns result of another key
even though I have a matching private key

also can view encrypted emails without issue

### LINKED ISSUE #860: signing prv accepts a wrong pass phrase

### LINKED ISSUE #878: includeAttachments is ignored, atts should not send for drafts
includeAttachments boolean is ignored but should be used, as far as drafts don't need to save attachments.

_Originally posted by @ekievsky in https://github.com/FlowCrypt/flowcrypt-ios/pull/854#discussion_r740199227_

### LINKED ISSUE #884: crash feedbacks from 2021-10-31 and 2021-11-01
here user said `When selecting the to: adr from the list` [testflight_feedback-2.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7455874/testflight_feedback-2.zip)

here without feedback: [testflight_feedback-3.zip](https://github.com/FlowCrypt/flowcrypt-ios/files/7455876/testflight_feedback-3.zip)

### LINKED ISSUE #895: appium: CheckSettingsForLoggedUser.spec failed
Output:

```
[iPhone Simulator iOS 15.0 #0-6] Spec: /Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts
[iPhone Simulator iOS 15.0 #0-6] Running: iPhone Simulator on iOS 15.0 executing /Users/ivan/Library/Developer/Xcode/DerivedData/FlowCrypt-dkmvlhcprnebshbeurvkormazmnk/Build/Products/Debug-iphonesimulator/FlowCrypt.app
[iPhone Simulator iOS 15.0 #0-6] Session ID: 964b1378-4733-470c-b903-822fa3e667fe
[iPhone Simulator iOS 15.0 #0-6]
[iPhone Simulator iOS 15.0 #0-6] SETTINGS: 
[iPhone Simulator iOS 15.0 #0-6]    ✖ user should see public key and should not see private key
[iPhone Simulator iOS 15.0 #0-6]
[iPhone Simulator iOS 15.0 #0-6] 1 failing (1m 0.6s)
[iPhone Simulator iOS 15.0 #0-6]
[iPhone Simulator iOS 15.0 #0-6] 1) SETTINGS:  user should see public key and should not see private key
[iPhone Simulator iOS 15.0 #0-6] Error: element ("~Show public key") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-6] Error: element ("~Show public key") still not displayed after 15000ms
[iPhone Simulator iOS 15.0 #0-6]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[iPhone Simulator iOS 15.0 #0-6]     at KeysScreen.checkSelectedKeyScreen (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/screenobjects/keys.screen.ts:79:34)
[iPhone Simulator iOS 15.0 #0-6]     at UserContext.<anonymous> (/Users/ivan/Documents/Projects/FlowCrypt/flowcrypt-ios/appium/tests/specs/settings/CheckSettingsForLoggedUser.spec.ts:29:20)
```

Simulator Screen Shot - appiumTest-9D7CBD23-6790-436E-926D-CA189C5C5DAC-iPhone X - 2021-11-02 at 13 46 19

For some reason we can not read keys from storage

### PR DESCRIPTION
**Pull request by tomholub**
This PR synchronizes calls to Core using a queue and async methods, while refactoring the app for async (usage of Core) and fixing many other issues along the way:
- close #852
- close #819
- close #851
- close #860
- close #849 - possibly
- close #884
- close #895
- close #878
- close #681
- issue #867
- close #895

----------------------------------

**Tests**
 - new tests added, existing updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by tomholub** [comment]
Need to later refactor the pass phrase alert to be able to re-render it, similar to what viewing message does.

image

File: FlowCrypt/Controllers/Msg/MessageViewController.swift [hunk 1]
```diff
@@ -163,16 +163,18 @@ extension MessageViewController {
...
     private func handlePassPhraseEntry(rawMimeData: Data, with passPhrase: String) {
         showSpinner("loading_title".localized, isUserInteractionEnabled: true)
-        do { // todo - should be a task on non-main thread?
-            let matched = try messageService.checkAndPotentiallySaveEnteredPassPhrase(passPhrase)
-            if matched {
-                self.processedMessage = try awaitPromise(self.messageService.decryptAndProcessMessage(mime: rawMimeData))
-                self.handleReceivedMessage()
-            } else {
-                handleWrongPathPhrase(for: rawMimeData, with: passPhrase)
+        Task {
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Msg/MessageViewController.swift:166]: Since you don't have `async/await` inside Task, you don't need it

Comment (tomholub) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:166]: Thanks! Updating.

File: FlowCrypt/Core/Core.swift [hunk 2]
```diff
@@ -227,45 +227,55 @@ final class Core: KeyDecrypter, KeyParser, CoreComposeMessageType {
...
-
-        let error = try? resJsonData.decodeJson(as: CoreRes.Error.self)
-        if let error = error {
-            let errMsg = "------ js err -------\nCore \(endpoint):\n\(error.error.message)\n\(error.error.stack ?? "no stack")\n------- end js err -----"
-            logger.logError(errMsg)
-
-            throw CoreError(coreError: error)
+    private func call(_ endpoint: String, jsonData: Data, data: Data) async throws -> RawRes {
+        try await sleepUntilReadyOrThrow()
+        return try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<RawRes, Error>) in
```
Comment (ivan-ushakov) [inline FlowCrypt/Core/Core.swift:240]: Since you want to have all `Core` class methods to be synchronised, you could use `actor` keyword. So you can remove queue and `withCheckedThrowingContinuation`

Comment (tomholub) [reply FlowCrypt/Core/Core.swift:240]: Just adding actor to the class will do that?

File: FlowCrypt/Controllers/Msg/MessageViewController.swift (hunk 1 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:166]: I'll change it back :-) `checkAndPotentiallySaveEnteredPassPhrase` is now async anyway.

File: FlowCrypt/Core/Core.swift (hunk 2 above)
Comment (tomholub) [reply FlowCrypt/Core/Core.swift:240]: I just tried and needs some further refactor - I'll try again once I can at least build the app again.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 3]
```diff
@@ -190,18 +193,17 @@ extension ComposeViewController {
...
                 )
-                guard case let .success(message) = messagevalidationResult else {
-                    return
-                }
-                try await composeMessageService.encryptAndSaveDraft(message: message, threadId: input.threadId)
-            } catch {}
+                try await composeMessageService.encryptAndSaveDraft(message: sendableMsg, threadId: input.threadId)
+            } catch {
+                showToast("Error saving draft: \(error.localizedDescription)")
+            }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:206]: Do I have to synchronize to main thread?

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 4]
```diff
@@ -328,8 +330,10 @@ extension ComposeViewController {
         Task {
             do {
                 let key = try await prepareSigningKey()
-                sendMessage(key)
-            } catch {}
+                try await sendMessage(key)
+            } catch {
+                handle(error: error)
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:335]: Have to worry about rendering on main thread?

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 5]
```diff
@@ -338,94 +342,98 @@ extension ComposeViewController {
...
+            //   I copied it from another usage, but has to be changed
+            throw KeyServiceError.retrieve
+        }
+        let matchingKeys = try await self.keyMethods.filterByPassPhraseMatch(keys: allKeys, passPhrase: passPhrase)
+        // save passphrase for all matching keys
+        self.passPhraseService.savePassPhrasesInMemory(passPhrase, for: matchingKeys)
+        // now figure out if the pass phrase also matched the signing prv itself
+        let matched = matchingKeys.first(where: { $0.fingerprints.first == signingKey.fingerprints.first })
+        return matched != nil// true if the pass phrase matched signing key
     }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:398]: To re-review later

File: FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift [hunk 6]
```diff
@@ -176,9 +171,17 @@ extension SetupBackupsViewController {
...
+        Task {
+            do {
+                try await Task.sleep(nanoseconds: 100 * 1_000_000) // 100 ms
+                try await self.recoverAccount(with: self.fetchedEncryptedKeys, and: passPhrase)
+                moveToMainFlow()
+            } catch {
+                hideSpinner()
+                showAlert(error: error, message: "Failed to set up account", onOk: {
+                    // todo - what to do? maybe nothing, since they should now see the same button again that they can press again
+                })
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupBackupsViewController.swift:183]: File an issue to test this later

File: FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift [hunk 7]
```diff
@@ -137,50 +137,37 @@ extension SetupCreatePassphraseAbstractViewController {
...
-            )
-
-            alert.addTextField { textField in
-                textField.isSecureTextEntry = true
-                textField.accessibilityLabel = "textField"
-            }
-
+    private func awaitUserPassPhraseEntry() async throws -> String? {
+        let alert = UIAlertController(
+            title: "await Pass Phrase",
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift:156]: typo to remove

File: FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift [hunk 8]
```diff
@@ -62,7 +62,21 @@ final class SetupEKMKeyViewController: SetupCreatePassphraseAbstractViewControll
     }
 
     override func setupAccount(with passphrase: String) {
-        setupAccountWithKeysFetchedFromEkm(with: passphrase)
+        Task {
+            do {
+                try await setupAccountWithKeysFetchedFromEkm(with: passphrase)
+                // todo - do this on main thread?
+                self.hideSpinner()
+                self.moveToMainFlow()
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift:70]: ?

File: FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift [hunk 9]
```diff
@@ -62,7 +62,21 @@ final class SetupEKMKeyViewController: SetupCreatePassphraseAbstractViewControll
...
+            } catch {
+                self.hideSpinner()
+                let isErrorHandled = self.handleCommon(error: error)
+                if !isErrorHandled {
+                    self.showAlert(error: error, message: "Could not finish setup, please try again")
+                }
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupEKMKeyViewController.swift:76]: Must be on main thread?

File: FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift [hunk 10]
```diff
@@ -176,7 +176,15 @@ extension SetupManuallyEnterPassPhraseViewController: ASTableDelegate, ASTableDa
                     insets: self.decorator.insets.buttonInsets
                 )
                 return ButtonCellNode(input: input) { [weak self] in
-                    self?.handleContinueAction()
+                    guard let self = self else { return }
+                    Task {
+                        do {
+                            try await self.handleContinueAction()
+                        } catch {
+                            self.handleCommon(error: error)
```
Comment (tomholub) [inline FlowCrypt/Controllers/Setup/SetupManuallyEnterPassPhraseViewController.swift:184]: Necessary to be on main thread or task ok?

File: FlowCrypt/Core/Core.swift [hunk 11]
```diff
@@ -64,30 +64,30 @@ final class Core: KeyDecrypter, KeyParser, CoreComposeMessageType {
     private dynamic var started = false
     private dynamic var ready = false
     
-    private let queue = DispatchQueue(label: "com.flowcrypt.core", qos: .background)
+    private let queue = DispatchQueue(label: "com.flowcrypt.core", qos: .default) // todo - try also with .userInitiated
```
Comment (tomholub) [inline FlowCrypt/Core/Core.swift:67]: Todo - another issue

File: FlowCrypt/Core/Core.swift (hunk 2 above)
Comment (tomholub) [reply FlowCrypt/Core/Core.swift:240]: I'll file it for another issue later

File: FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift [hunk 12]
```diff
@@ -59,116 +59,96 @@ final class MessageService {
...
-    private func savePassPhrases(value passPhrase: String, with privateKeys: [PrvKeyInfo]) {
-        privateKeys
-            .map { PassPhrase(value: passPhrase, fingerprints: $0.fingerprints) }
-            .forEach { self.passPhraseService.savePassPhrase(with: $0, storageMethod: .memory) }
-    }
-
-    func getAndProcessMessage(with input: Message, folder: String) -> Promise<ProcessedMessage> {
+    func decryptAndProcessMessage(mime rawMimeData: Data) -> Promise<ProcessedMessage> {
         Promise { [weak self] resolve, reject in
             guard let self = self else { return }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift:98]: This could maybe be made async method

File: FlowCrypt/Functionality/Pgp/KeyMethods.swift [hunk 13]
```diff
@@ -21,27 +22,38 @@ final class KeyMethods: KeyMethodsType {
         self.decrypter = decrypter
     }
 
-    func filterByPassPhraseMatch(keys: [KeyDetails], passPhrase: String) -> [KeyDetails] {
+    // todo - join these two methods into one
+    func filterByPassPhraseMatch(keys: [PrvKeyInfo], passPhrase: String) async throws -> [PrvKeyInfo] {
```
Comment (tomholub) [inline FlowCrypt/Functionality/Pgp/KeyMethods.swift:26]: Todo for another issue

File: FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift [hunk 14]
```diff
@@ -160,6 +158,7 @@ final class ComposeMessageService {
 
     func getDraft(with identifier: String) {
         Task {
+            // tom - unsure what this does? the result is unused
             let draft = try await draftGateway?.getDraft(with: identifier)
         }
     }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:164]: Todo - file an issue to discuss this

File: FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift [hunk 15]
```diff
@@ -7,22 +7,26 @@
...
+    func getSigningKey() async throws -> PrvKeyInfo?
 }
 
 enum KeyServiceError: Error {
     case unexpected, parsingError, retrieve
 }
 
 final class KeyService: KeyServiceType {
+
+
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift:24]: style - to remove a line

File: FlowCrypt/Functionality/Services/Local Private Key Services/PassPhraseService.swift [hunk 16]
```diff
@@ -12,29 +12,32 @@ import UIKit
...
-        PassPhrase(value: self.value, fingerprints: self.fingerprints, date: Date())
+        PassPhrase(value: self.value, fingerprintsOfAssociatedKey: self.fingerprintsOfAssociatedKey, date: Date())
     }
 
+    // (tom) todo - this is a confusing thing to do
+    // when comparing pass phrases to one another, you would expect that it's compared by the pass phrase string itself, and not by primary fingerprint of the associated key. I understand this is being used somewhere, but I suggest to refactor it to avoid defining this == overload.
     static func == (lhs: PassPhrase, rhs: PassPhrase) -> Bool {
-        lhs.primaryFingerprint == rhs.primaryFingerprint
+        lhs.primaryFingerprintOfAssociatedKey == rhs.primaryFingerprintOfAssociatedKey
     }
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/Local Private Key Services/PassPhraseService.swift:36]: Todo - remove `==` overload from PassPhrase in another issue

File: FlowCryptAppTests/Core/FlowCryptCoreTests.swift [hunk 17]
```diff
@@ -82,17 +82,24 @@ final class FlowCryptCoreTests: XCTestCase {
...
-        XCTAssertThrowsError(try core.decryptKey(armoredPrv: TestData.k0.prv, passphrase: "wrong"))
+    func testDecryptKeyWithWrongPassPhrase() async {
+        do {
+            _ = try await core.decryptKey(armoredPrv: TestData.k0.prv, passphrase: "wrong")
+            XCTFail("Should have thrown above")
+        } catch {
+            // todo - should check exact thrown error
+            return
+        }
+        XCTFail("Should have thrown above")
```
Comment (tomholub) [inline FlowCryptAppTests/Core/FlowCryptCoreTests.swift:102]: todo - finish test

File: FlowCryptAppTests/Core/FlowCryptCoreTests.swift [hunk 18]
```diff
@@ -370,12 +377,53 @@ final class FlowCryptCoreTests: XCTestCase {
...
             XCTFail("Should have thrown above")
         } catch let CoreError.exception(message) {
             XCTAssertNotNil(message.range(of: "Error: Misformed armored text"))
         }
     }
+
+    // this test is only meaningful on a real device
+    // it passes on simulator even if implementation is broken
+    // maybe there's a way to run simulator with more cores? (on a mac that has them) which would simulate real device better
+    func testCoreResponseCorrectnessUnderConcurrency() async throws {
```
Comment (tomholub) [inline FlowCryptAppTests/Core/FlowCryptCoreTests.swift:392]: Is there a way to run this code on simulator that actually uses many OS threads for the simulator?

File: FlowCryptCommon/Logger.swift [hunk 19]
```diff
@@ -92,7 +92,7 @@ public struct Logger {
 
     private func log(
         _ level: Logger.Level,
-        _ message: @autoclosure () -> String,
+        _ message: String,
```
Comment (tomholub) [inline FlowCryptCommon/Logger.swift:95]: This was causing logs to get written with a huge delay, or sometimes after certain unrelated actions completed, making it hard to debug

**Comment by tomholub** [comment]
The unit tests I wrote that reproduced the original issue now passes. So that's the good news. But there's probably a bunch of things still broken in other tests.

@ivan-ushakov could you please help me answer my questions above, especially regarding rendering on main thread?

**Comment by tomholub** [comment]
App locks up now when I open a reply screen, will look into it further.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift (hunk 3 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Compose/ComposeViewController.swift:206]: showToast already does that

**Comment by tomholub** [comment]
I've got my questions answered with the crashes I got

File: FlowCrypt/Core/Core.swift (hunk 11 above)
Comment (tomholub) [reply FlowCrypt/Core/Core.swift:67]: use actor then can throw this out

File: FlowCrypt/Controllers/Msg/MessageViewController.swift [hunk 20]
```diff
@@ -144,35 +147,36 @@ final class MessageViewController: TableNodeViewController {
...
-            self.processedMessage = message
-        }
-        .then(on: .main) { [weak self] in
-            self?.handleReceivedMessage()
-        }
-        .catch(on: .main) { [weak self] error in
-            self?.handleError(error)
+        Task {
+            do {
+                let rawMimeData = try awaitPromise(self.messageProvider.fetchMsg(message: self.input.objMessage, folder: self.input.path))
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Msg/MessageViewController.swift:152]: I think this will run on main thread

File: FlowCrypt/Controllers/Msg/MessageViewController.swift [hunk 21]
```diff
@@ -144,35 +147,36 @@ final class MessageViewController: TableNodeViewController {
...
+                self.processedMessage = try await self.messageService.decryptAndProcessMessage(mime: rawMimeData)
+                DispatchQueue.main.async {
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Msg/MessageViewController.swift:154]: You should be on main thread here

Comment (tomholub) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:154]: Hm. Exactly the following two should not run on main thread:

```
                let rawMimeData = try awaitPromise(self.messageProvider.fetchMsg(message: self.input.objMessage, folder: self.input.path))
```

How to change it to make sure these two run on other thread?

File: FlowCrypt/Controllers/Msg/MessageViewController.swift (hunk 20 above)
Comment (tomholub) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:152]: Will fetching message in async way block the main thread? In other words, is it acceptable to do that on main thread or should we be using other thread, and if so, how?

**Comment by tomholub** [comment]
@ivan-ushakov could you please help me finalize the PR? I'm getting this one when I open compose view, but I don't understand why it's happening.

image

File: FlowCrypt/Controllers/Msg/MessageViewController.swift (hunk 21 above)
Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:154]: You could use actors like I did for other controllers until we move service layer to actors completely

**Comment by ivan-ushakov** [comment]
> @ivan-ushakov could you please help me finalize the PR? I'm getting this one when I open compose view, but I don't understand why it's happening.
Sure, may I continue with it?

**Comment by tomholub** [comment]
> > @ivan-ushakov could you please help me finalize the PR? I'm getting this one when I open compose view, but I don't understand why it's happening.
> 
> Sure, may I continue with it?

Yes, please

**Comment by tomholub** [comment]
@ivan-ushakov I fixed one failing swift test, hopefully all should be passing now. The rest is yours for today

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 22]
```diff
@@ -153,16 +156,10 @@ final class ComposeViewController: TableNodeViewController {
...
-        DispatchQueue.global().async { [weak self] in
-            guard let self = self else { return }
-            self.saveDraftTimer = Timer.scheduledTimer(
-                timeInterval: 1,
-                target: self,
-                selector: #selector(self.saveDraftIfNeeded),
-                userInfo: nil,
-                repeats: true)
-            self.saveDraftTimer?.fire()
+        saveDraftTimer = Timer.scheduledTimer(withTimeInterval: 1.0, repeats: true) { [weak self] _ in
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:159]: Block syntax allows to avoid `@objc` annotation

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 23]
```diff
@@ -328,104 +324,114 @@ extension ComposeViewController {
...
 extension ComposeViewController {
-    private func prepareSigningKey() async throws -> PrvKeyInfo {
-        try await withCheckedThrowingContinuation { (continuation: CheckedContinuation<PrvKeyInfo, Error>) in
-            guard let signingKey = try? keyService.getSigningKey() else {
-                let message = "No available private key has your user id \"\(email)\" in it. Please import the appropriate private key."
-                showAlert(message: message)
-                continuation.resume(throwing: MessageServiceError.unknown)
-                return
-            }
+    @MainActor private func prepareSigningKey() async throws -> PrvKeyInfo {
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:340]: `@MainActor` annotation force invocation on main thread

File: FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift [hunk 24]
```diff
@@ -32,93 +35,87 @@ final class KeyService: KeyServiceType {
...
+            logger.logError("no current user email")
+            throw AppErr.noCurrentUser
         }
-
-        let keysInfo = storage.keysInfo()
-            .filter { $0.account == email }
-
-        guard let foundKey = try findKeyByUserEmail(keysInfo: keysInfo, email: email) else {
+        // get keys associated with this account, freeze them to pass across threads
+        let keysInfo = storage.keysInfo().filter { $0.account == email }.map { $0.freeze() }
```
Comment (ivan-ushakov) [inline FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift:82]: Freeze allows to use Realm objects across threads but makes them readonly

**Review by tomholub — COMMENTED** [review]
updates look good so far

**Review by tomholub — COMMENTED** [review]
👍

**Comment by tomholub** [comment]
Tried logging in with google access previously revoked, and purposefully did not give it all scopes during login/grant. Got:

```
"ℹ️[App Start][GlobalRouter] Sign in with gmailLogin(<FlowCrypt.SignInViewController: 0x11681ce00>)"
"ℹ️[App Start][GlobalRouter] gmail login failed with error The operation couldn’t be completed. (FlowCrypt.GoogleUserServiceError error 3.)"
```

I was sent back to splash screen. I must have broken #531

**Comment by tomholub** [comment]
crash when message is being sent:

```
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIViewController navigationItem]
PID: 4253, TID: 1648112, Thread name: (none), Queue name: com.apple.root.user-initiated-qos.cooperative, QoS: 25
Backtrace:
4   FlowCrypt                           0x00000001044fb8a0 $s9FlowCrypt21ComposeViewControllerC29handleSuccessfullySentMessage33_7A1ECDF8A8586BF8F0F21A8909AD61B9LLyyF + 176
5   FlowCrypt                           0x00000001044f95d0 $s9FlowCrypt21ComposeViewControllerC11sendMessage33_7A1ECDF8A8586BF8F0F21A8909AD61B9LLyyAA10PrvKeyInfoVYaKFTQ2_ + 232
6   libswift_Concurrency.dylib          0x00000001ff06bfec 2DF85DF4-EDDA-3892-8416-79650004A8A4 + 249836
7   libswift_Concurrency.dylib          0x00000001ff06c890 swift_job_run + 188
8   libdispatch.dylib                   0x000000010b7ba688 _dispatch_root_queue_drain + 400
9   libdispatch.dylib                   0x000000010b7bb08c _dispatch_worker_thread2 + 196
10  libsystem_pthread.dylib             0x00000001f3211174 _pthread_wqthread + 228
11  libsystem_pthread.dylib             0x00000001f3210f50 start_wqthread + 8
```

**Comment by tomholub** [comment]
image

**Comment by tomholub** [comment]
@sosnovsky see if this fixes your issue now (ignoring the newly introduced crashes etc). It solved my issue.

**Comment by sosnovsky** [comment]
@tomholub I tried to reply to your latest message, but app crashed when I tapped "Reply" button.
Also my previous issue was fixed after app reinstall, currently messages/replies decrypting works well.

Screenshot 2021-11-01 at 14 48 35

**Comment by ivan-ushakov** [comment]
For some reason draft requires to enter pass phrase all the way

**Comment by tomholub** [comment]
> For some reason draft requires to enter pass phrase all the way

Could you clarify? Do you mean all the time - it doesn't save the pass phrase?

**Comment by tomholub** [comment]
> @tomholub I tried to reply to your latest message, but app crashed when I tapped "Reply" button. Also my previous issue was fixed after app reinstall, currently messages/replies decrypting works well.
> 
> Screenshot 2021-11-01 at 14 48 35

I see. Please observe it in the future, see if you ever manage to reproduce it again.

**Comment by ivan-ushakov** [comment]
> > For some reason draft requires to enter pass phrase all the way
> 
> Could you clarify? Do you mean all the time - it doesn't save the pass phrase?


Simulator Screen Shot - iPhone 11 Pro - 2021-11-01 at 16 01 18

I getting this error and loose focus from edit field

**Comment by tomholub** [comment]
> > > For some reason draft requires to enter pass phrase all the way
> > 
> > 
> > Could you clarify? Do you mean all the time - it doesn't save the pass phrase?
> 
> Simulator Screen Shot - iPhone 11 Pro - 2021-11-01 at 16 01 18
> 
> I getting this error and loose focus from edit field

You could clarify the error handler. If it's a message validation error (when composing a draft), then ignore the error, with a code comment `Drafts should not be saved if message doesn't pass validation`. 

For other types of error, Toast like before.

File: FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift [hunk 25]
```diff
@@ -101,48 +103,49 @@ final class ComposeMessageService {
...
+            to: recipients.map(\.email),
+            cc: [],
+            bcc: [],
+            from: email,
+            subject: subject,
+            replyToMimeMsg: replyToMimeMsg,
+            atts: sendableAttachments,
+            pubKeys: [myPubKey] + allRecipientPubs,
+            signingPrv: signingPrv
+        )
```
Comment (ekievsky) [inline FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: includeAttachments boolean is ignored but should be used, as far as drafts don't need to save attachments.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 26]
```diff
@@ -21,6 +21,7 @@ private struct ComposedDraft: Equatable {
     let contextToSend: ComposeMessageContext
 }
 
+@MainActor
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:24]: One of possible reasons for this could be that `ADK` is Objective C framework

File: FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift (hunk 25 above)
Comment (ivan-ushakov) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: we could create a separate issue for this since this PR is already huge

Comment (tomholub) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: Drafts indeed shouldn't save attachments. Can file in separate issue.

Comment (ekievsky) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: PR is huge indeed, but we should care about old functionality while refactoring new one.
Its really important, because otherwise PRs will produce more pain than effort.

I think PRs like that should be initially split into several ones ( lets try to do like that in future ). Review and ensure that everything that was refactored is not broken - its very hard in current PR.

File: FlowCrypt/Controllers/Compose/ComposeViewController.swift [hunk 27]
```diff
@@ -328,104 +325,112 @@ extension ComposeViewController {
...
-                                                 threadId: input.threadId,
-                                                 progressHandler: { [weak self] progress in
-                    self?.updateSpinner(progress: progress)
-                })
-                handleSuccessfullySentMessage()
-            } catch {
-                if let error = error as? ComposeMessageError {
-                    handle(error: error)
-                }
+        try await Task.sleep(nanoseconds: 100 * 1_000_000) // 100ms
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Compose/ComposeViewController.swift:411]: @tomholub 
Why we need such delays?

Comment (tomholub) [reply FlowCrypt/Controllers/Compose/ComposeViewController.swift:411]: Earlier there was some problem with spinner rendering. Maybe the spinner didn't get rendered before the app got "busy" and then it would remain not rendered until the work was done. Unsure.

**Comment by ivan-ushakov** [comment]
@tomholub 
I think that this PR is ready on my side. Maybe you want to add/change something?

**Comment by tomholub** [comment]
@ivan-ushakov I think the appium tests are failing. Could you run them and fix the app in case that's the case?

File: FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift (hunk 25 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: Yes - I'll fix that in this PR.

This particular PR could not be split easily. Core methods were made async to prevent a bug, and that made the whole app async because they use the core methods.

Comment (tomholub) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: But in general we always try to make refactoring PRs smaller whenever possible.

Comment (tomholub) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:120]: It looks like the original code also ignored it, which is why Ivan proposed to do it in another PR. https://github.com/FlowCrypt/flowcrypt-ios/blob/41a5a6127f5bcdadcc892859ad10beca7cdc0513/FlowCrypt/Functionality/Services/Compose%20Message%20Service/ComposeMessageService.swift#L56 `includeAttachments` is unused.

**Comment by tomholub** [comment]
@fcvakintos is there a way to get the iOS app stack trace that caused it to crash?
```
[debug] [35m[WD Proxy][39m Proxying [POST /element] to [POST http://127.0.0.1:8100/session/0C7B68B4-B838-4115-BF25-D9DD8D8CA6E4/element] with body: {"using":"accessibility id","value":"textField"}
[35m[WD Proxy][39m Got response with status 400: {"value":{"error":"invalid element state","message":"The application under test with bundle id 'com.flowcrypt.as.ios.debug' is not running, possibly crashed","traceback":"(\n\t0   CoreFoundation                      0x00007fff203fbbb4 __exceptionPreprocess + 242\n\t1   libobjc.A.dylib                     0x00007fff2019ebe7 objc_exception_throw + 48\n\t2   CoreFoundation                      0x00007fff203fb855 -[NSException init] + 0\n\t3   WebDriverAgentLib                   0x000000010aa35823 -[FBSession activeApplication] + 979\n\t4   WebDriverAgentLib                   0x000000010aa39472 +[FBFindElementCommands handleFindElement:] + 242\n\t5   WebDriverAgentLib                   0x000000010a9fc40c -[FBRoute_TargetAction mountRequest:intoResponse:] + 172\n\t6   WebDriverAgentLib                   0x000000010a9e5234 __37-[FBWebServer registerRouteHandlers:]_block_invoke + 500\n\t7   WebDriverAgentLib                   0x000000010aa1f28d -[RoutingHTTPServer handleRoute:withRequest:response:] + 189\n\t8   W...
[debug] [35m[W3C][39m Matched W3C error code 'invalid element state' to InvalidElementStateError
[debug] [35m[W3C (28c755cf)][39m Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[debug] [35m[W3C (28c755cf)][39m     at XCUITestDriver.doNativeFind (/Users/luke/git/flowcrypt-ios/appium/node_modules/appium-xcuitest-driver/lib/commands/find.js:130:11)
[debug] [35m[W3C (28c755cf)][39m     at runMicrotasks (<anonymous>)
[debug] [35m[W3C (28c755cf)][39m     at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

File: FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift [hunk 28]
```diff
@@ -137,51 +137,43 @@ extension SetupCreatePassphraseAbstractViewController {
...
-                preferredStyle: .alert
-            )
-
-            alert.addTextField { textField in
-                textField.isSecureTextEntry = true
-                textField.accessibilityLabel = "textField"
-            }
+    private func awaitUserPassPhraseEntry() async throws -> String? {
+        return await withCheckedContinuation { (continuation: CheckedContinuation<String?, Never>) in
+            DispatchQueue.main.async {
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift:156]: Crash was here

```
Thread 1 Crashed:: Dispatch queue: com.apple.root.user-initiated-qos.cooperative
0   libunwind.dylib                     0x000000010f6e1fcc libunwind::UnwindCursor<libunwind::LocalAddressSpace, libunwind::Registers_x86_64>::step() + 384
1   libunwind.dylib                     0x000000010f6e3bc1 _Unwind_RaiseException + 166
2   libc++abi.dylib                     0x000000010b05402d __cxa_throw + 108
3   libobjc.A.dylib                     0x000000010a913cd8 objc_exception_throw + 289
4   com.apple.CoreAutoLayout            0x0000000111f9d3f1 _AssertAutoLayoutOnAllowedThreadsOnly + 422
5   com.apple.CoreAutoLayout            0x0000000111f9d679 -[NSISEngine withBehaviors:performModifications:] + 25
6   com.apple.UIKitCore                 0x000000013a547aae -[UIView(UIConstraintBasedLayout) _calculatedSystemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:hasIntentionallyCollapsedHeight:] + 1034
7   com.apple.UIKitCore                 0x000000013a548f3f -[UIView(AdditionalLayoutSupport) _systemLayoutSizeFittingSize:withHorizontalFittingPriority:verticalFittingPriority:hasIntentionallyCollapsedHeight:] + 587
8   com.apple.UIKitCore                 0x0000000139410334 -[_UIAlertControllerTextFieldViewController _updatePreferredContentSize] + 188
9   com.apple.UIKitCore                 0x00000001394108a1 -[_UIAlertControllerTextFieldViewController updateTextFieldStyle] + 124
10  com.apple.UIKitCore                 0x000000013940fd7a -[_UIAlertControllerTextFieldViewController setVisualStyle:] + 59
11  com.apple.UIKitCore                 0x00000001394387a0 -[UIAlertController _updateProvidedStyleWithTraitCollection:] + 553
12  com.apple.UIKitCore                 0x0000000139438874 -[UIAlertController _updateProvidedStyle] + 57
13  com.apple.UIKitCore                 0x0000000139435d11 -[UIAlertController addAction:] + 353
14  FlowCrypt                           0x00000001034d4ba6 $s9FlowCrypt43SetupCreatePassphraseAbstractViewControllerC24awaitUserPassPhraseEntry33_232761CB30E74E6935BCB3C3859B5A30LLSSSgyYaKFyScCyAFs5NeverOGXEfU0_ + 630 (SetupCreatePassphraseAbstractViewController.swift:167)
15  libswift_Concurrency.dylib          0x000000010e61bab1 $ss23withCheckedContinuation8function_xSS_yScCyxs5NeverOGXEtYalFySccyxADGXEfU_TA + 113
```

Comment (tomholub) [reply FlowCrypt/Controllers/Setup/SetupCreatePassphraseAbstractViewController.swift:156]: Thanks!

**Review by tomholub — COMMENTED** [review]
lgtm so far, let's see the tests

**Comment by ivan-ushakov** [comment]
> lgtm so far, let's see the tests

UI tests failing now because of #895

File: FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift (hunk 25 above)
Comment (tomholub) [reply FlowCrypt/Functionality/Services/Compose Message Service/ComposeMessageService.swift:115]: I fixed it in this PR

File: FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift [hunk 29]
```diff
@@ -59,118 +59,90 @@ final class MessageService {
...
+            var data = meta.data
+            var size = meta.length
+            if block.type == .encryptedAtt { // decrypt
+                let decrypted = try await core.decryptFile(encrypted: data, keys: keys, msgPwd: nil)
+                data = decrypted.content
+                name = decrypted.name
+                size = decrypted.content.count
             }
-
+            attachments.append(MessageAttachment(name: name, size: size, data: data))
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Mail Provider/Message Provider/MessageService.swift:144]: I think it'll be better to move this attachment processing to separate method and simplify code a bit, so we don't need to reassign attachment values:
```swift
var attachments: [MessageAttachment] = []
        for block in attachmentBlocks {
            guard let attachment = try await processAttachment(block: block, keys: keys) else { continue }
            attachments.append(attachment)
        }
....
private func processAttachment(block: MsgBlock, keys: [PrvKeyInfo]) async throws -> MessageAttachment? {
        guard let meta = block.attMeta else { return nil }

        if block.type == .encryptedAtt { // decrypt
            let decrypted = try await core.decryptFile(encrypted: meta.data, keys: keys, msgPwd: nil)
            return MessageAttachment(name: decrypted.name,
                                     size: decrypted.content.count,
                                     data: decrypted.content)
        } else {
            return MessageAttachment(name: meta.name, size: meta.length, data: meta.data)
        }
    }
```

File: FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift [hunk 30]
```diff
@@ -44,7 +44,8 @@ struct ContactsService: ContactsServiceType {
 
 extension ContactsService: ContactsProviderType {
     func searchContact(with email: String) async throws -> RecipientWithSortedPubKeys {
-        guard let contact = localContactsProvider.searchRecipient(with: email) else {
+        let contact = try await localContactsProvider.searchRecipient(with: email)
+        guard let contact = contact else {
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Services/Local Pub Key Services/ContactsService.swift:48]: Can be just 1 line
```swift
guard let contact = try await localContactsProvider.searchRecipient(with: email) else {
...
```

**Review by sosnovsky — COMMENTED** [review]
Overall looks good and works smoothly - haven't got any crashes.
Just left some comments about possible code improvements.

File: FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift [hunk 31]
```diff
@@ -32,93 +35,90 @@ final class KeyService: KeyServiceType {
...
-                try? coreService.parseKeys(armoredOrBinary: $0.data())
-            }
-            .map(\.keyDetails)
-            .flatMap { $0 }
-
-        guard keyDetails.count == privateKeys.count else {
-            return .failure(.parsingError)
+            .joined(separator: "\n")
+        let parsed = try await coreService.parseKeys(armoredOrBinary: privateKeys.data())
+        guard parsed.keyDetails.count == privateKeys.count else {
```
Comment (ivan-ushakov) [inline FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift:51]: @sosnovsky
Little hint for the #895

Comment (sosnovsky) [reply FlowCrypt/Functionality/Services/Local Private Key Services/KeyService.swift:51]: thanks!

File: FlowCrypt/Controllers/Msg/MessageViewController.swift [hunk 32]
```diff
@@ -82,6 +85,11 @@ final class MessageViewController: TableNodeViewController {
         self.trashFolderProvider = trashFolderProvider
         self.onCompletion = completion
         self.filesManager = filesManager
+        self.messageProvider = messageProvider
+        self.serviceActor = ServiceActor(
+            messageService: messageService,
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:90]: @ivan-ushakov is the eventual goal that each if the individual sevices will themselves be an actor?

File: FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift [hunk 33]
```diff
@@ -44,9 +44,14 @@ final class KeySettingsViewController: TableNodeViewController {
...
-
-        loadKeysFromStorageAndRender()
         setupNavigationBar()
+        Task {
+            do {
+                try await loadKeysFromStorageAndRender()
+            } catch {
+                handleCommon(error: error)
+            }
+        }
```
[the remark this answers is not in the document]
Comment (tomholub) [reply FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift:54]: Maybe we could have a convention for this. Like maybe call it `loadKeysTask` or `somethingElseTask` if it's a method that creates a task for async methods. Then, by looking at the method name, you know what type of method it is.

Generally, there should be not more than one Task method per such handler (except when we want things to happen in parallel), so such convention would allow us to see the handler at a glance.

File: FlowCrypt/Controllers/Msg/MessageViewController.swift (hunk 32 above)
[the remark this answers is not in the document]
Comment (ivan-ushakov) [reply FlowCrypt/Controllers/Msg/MessageViewController.swift:90]: Maybe not all services but when we need to run method not on main thread or we need to keep internal state safe for multithreading we could use actor

File: FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift [hunk 34]
```diff
@@ -15,6 +15,7 @@ import FlowCryptUI
  * - User can proceed to importing keys *SetupManuallyImportKeyViewController*
  * - User can see detail information for the key in *KeyDetailViewController*
  */
+@MainActor
```
Comment (ivan-ushakov) [inline FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift:18]: issue #876

**Review by tomholub — COMMENTED** [review]
LGTM

**Review by ivan-ushakov — APPROVED** [review]

File: FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift (hunk 33 above)
[the remark this answers is not in the document]
Comment (sosnovsky) [reply FlowCrypt/Controllers/Settings/KeySettings/Key List/KeySettingsViewController.swift:55]: Sounds good 👍

**Comment by tomholub** [comment]
@ivan-ushakov please help me look at the conflict too

**Comment by tomholub** [comment]
> 
> This branch has conflicts that must be resolved
> Use the web editor or the to resolve conflicts.
> Conflicting files
> FlowCrypt/Controllers/Compose/ComposeViewController.swift
>

**Comment by tomholub** [comment]
@sosnovsky I'm happy you did the review on the other PR but this was an inconvenient time for merging - caused conflicts on this PR that we're trying to merge in.

**Comment by sosnovsky** [comment]
> @sosnovsky I'm happy you did the review on the other PR but this was an inconvenient time for merging - caused conflicts on this PR that we're trying to merge in.

Ah, I see, there were only 3 lines added, should be easy to fix, I can work on these merge conflicts

**Review by sosnovsky — APPROVED** [review]

**Comment by tomholub** [comment]
Thank you - if you take care of merge conflicts, then it's no problem :-)
