### PR TITLE
#1930 fix: draft test

### LINKED ISSUE #1930: Fix drafts test
`check drafts functionality` test occasionally fails on semaphoreci.
Needs to be fixed

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed draft test

close #1930 // if this PR closes an issue

----------------------------------

**Tests** _(delete all except exactly one)_:
- Tests added or updated

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [ ] addresses the issue it closes (if any)
- [ ] code is readable and understandable
- [ ] is accompanied with tests, or tests are not needed
- [ ] is free of vulnerabilities
- [ ] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Comment by ioanmo226** [comment]
let me run test 2-3 times

**Review by sosnovsky — COMMENTED** [review]
Adding `refreshMailList` before `checkIfFolderIsEmpty` check changes test logic, as initially we tested if folder emails list is automatically refreshed even without manual reload.

Initial drafts test never failed for me locally, only on Semaphore, and after latest appium and webdriverio updates it worked pretty well, I think.

**Comment by sosnovsky** [comment]
> But seemed like to me semaphoreci didn't update ui immediately after deleting draft(I might be wrong.)

My another guess was that `autosave` and `delete` mock draft api requests are interfering, which results in creating new draft immediately after deletion the old one. That's why drafts folder isn't empty.

**Comment by ioanmo226** [comment]
Thank you for the hint

File: appium/api-mocks/apis/google/google-endpoints.ts [hunk 1]
```diff
@@ -240,6 +240,7 @@ export const getMockGoogleEndpoints = (
       } else if (isDelete(req)) {
         const id = parseResourceId(req.url!);
         const data = (await GoogleData.withInitializedData(acct, googleConfig));
+        await browser.pause(2000); // wait some time because autosave and delete mock draft api requests might be interfering
```
Comment (ioanmo226) [inline appium/api-mocks/apis/google/google-endpoints.ts:243]: This might be silly fix but maybe easiest fix :-)
I think this semaphoreci case won't happen in live situation though.
Let me know your thought @sosnovsky

Comment (sosnovsky) [reply appium/api-mocks/apis/google/google-endpoints.ts:243]: Yeah, we can try to fix it this way and monitor drafts test further, to see if it was a reason for test fail.

Comment (ioanmo226) [reply appium/api-mocks/apis/google/google-endpoints.ts:243]: It seems fine. Maybe we can merge this PR and see if this issue happens again?

**Review by sosnovsky — APPROVED** [review]
