### PR TITLE
#2099 fix: email showing as plain text issue

### LINKED ISSUE #2099: Some emails are showing just plain html instead of text
Currently app should strip html code and render just plain text for html emails. But it fails for some emails and showing just plain html, which makes it quite difficult to read message content.

### PR DESCRIPTION
**Pull request by ioanmo226**
This PR fixed email showing as plain text issue

close #2099 // if this PR closes an issue

----------------------------------
image

**Tests** _(delete all except exactly one)_:
- Difficult to test (Hard to test in CI env)

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Functionality/Mail Provider/Message Provider/Gmail+MessageExtension.swift [hunk 1]
```diff
@@ -103,7 +103,7 @@ private extension GTLRGmail_Message {
 
     func parseMessageBody() -> MessageBody {
         let html = body(type: .textHtml)
-        let text = body(type: .textPlain) ?? html?.removingHtmlTags() ?? ""
+        let text = (body(type: .textPlain) ?? "").removingHtmlTags() ?? ""
```
Comment (ioanmo226) [inline FlowCrypt/Functionality/Mail Provider/Message Provider/Gmail+MessageExtension.swift:106]: @sosnovsky, Initially, I suspected that the HTML email was displaying as plain text because NSAttributedString initialization didn't recognize the xmlns attribute. 

However, after thorough evaluation, I discovered that my initial assumption was incorrect. The real issue is that `removingHtmlTags` function wasn't invoked for this particular instance.

What's your opinion on this fix?

Comment (sosnovsky) [reply FlowCrypt/Functionality/Mail Provider/Message Provider/Gmail+MessageExtension.swift]: With this fix we'll probably lose message text if there is no plain text body as it'll be converted to `""`?

Comment (ioanmo226) [reply FlowCrypt/Functionality/Mail Provider/Message Provider/Gmail+MessageExtension.swift]: Sorry, it was wrong fix. just pushed new fix

**Comment by ioanmo226** [comment]
@sosnovsky Please re-review

File: FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift [hunk 2]
```diff
@@ -96,6 +96,7 @@ extension ProcessedMessage {
     ) {
         self.message = message
         (self.text, self.quote) = Self.parseQuote(text: text)
+        self.text = self.text.removingHtmlTags() ?? self.text
```
Comment (sosnovsky) [inline FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift:99]: probably we can move `removingHtmlTags` to `parseQuote`, so it'll return text without tags and we won't need to remove them manually each time

Comment (ioanmo226) [reply FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift]: Sounds good!
I also removed html tags for `quote` too. What do you think?

Comment (sosnovsky) [reply FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift]: We don't need `?? ""` for quote text, as in this case quote `...` button becomes visible for all messages (even without quotes)

Comment (ioanmo226) [reply FlowCrypt/Functionality/Mail Provider/Message Provider/ProcessedMessage.swift]: Yep!. Missed it

**Review by sosnovsky — COMMENTED** [review]
I re-checked how it works, and looks like it was a bad idea to run `removingHtmlTags` for all texts. It works well for example message from this issue, but when you open message with only plain text body (for example, encrypted message sent from FlowCrypt) - it'll wrap all message into 1 line, which is not correct behavior.

Probably source of initial issue is that FlowCrypt thinks that initial message has only plain text body (while it has only html text body), and that's why it doesn't run `removingHtmlTags` for it. So we should improve parsing of message body parts to correctly handle html-only messages. Then current code `let text = body(type: .textPlain) ?? html?.removingHtmlTags() ?? ""` should work well

**Comment by sosnovsky** [comment]
`master` branch:

Screenshot 2023-07-21 at 21 57 51


this PR:

Screenshot 2023-07-21 at 21 58 37

**Comment by ioanmo226** [comment]
Nice catch. Let me have a re-look early next week.

**Comment by ioanmo226** [comment]
@sosnovsky Please re-check

**Review by sosnovsky — COMMENTED** [review]
New approach looks good, but it doesn't work for another html message.
I sent this message to you, can you please check it, probably `isHtmlString` regex needs some correction

**Comment by ioanmo226** [comment]
Ok, Let me check

**Comment by ioanmo226** [comment]
Just fixed it.
The problem was I didn't handle the `DocType` when it had attributes. Thanks for your detailed review, by the way!

File: FlowCryptCommon/Extensions/StringExtensions.swift [hunk 3]
```diff
@@ -95,6 +95,13 @@ public extension String {
         ).string
     }
 
+    func isHTMLString() -> Bool {
+        if let _ = self.range(of: "^\\s*(<!doctype html[\\s\\S]*>)?\\s*<[a-z][\\s\\S]*>\\s*$", options: [.regularExpression, .caseInsensitive]) {
+            return true
+        }
+        return false
```
Comment (sosnovsky) [inline FlowCryptCommon/Extensions/StringExtensions.swift:102]: let's simplify it to be just
```swift
func isHTMLString() -> Bool {
  self.range(...) != nil
}
```

**Review by sosnovsky — COMMENTED** [review]
Works great now, thanks for all fixes 👍

File: FlowCryptCommon/Extensions/StringExtensions.swift (hunk 3 above)
Comment (ioanmo226) [reply FlowCryptCommon/Extensions/StringExtensions.swift]: Sounds good!

**Review by sosnovsky — APPROVED** [review]
