### PR TITLE
Revive UI tests

### LINKED ISSUE #465: Wrong error message in case there are no emails on account
Discovered with ui tests and `den@flowcrypt.test` account.
This account doesn't have any emails on account.
Simulator Screen Shot - Clone 1 of iPhone 8 - 2021-08-20 at 14 19 55

### LINKED ISSUE #471: rename att to attachment
I suppose on the line below `fetchMsgAttribute` should be called `fetchMsgAttachment`. Also above, for clarity, rename `attContext` to `attachmentContext`. I'll make a separate issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/pull/466#discussion_r698793570_

### PR DESCRIPTION
**Pull request by Kharchevskyi**
This PR revive imap smtp ui tests

* Login with user without key backups and emails
* Login and cancel login flow
* Add ui test to verify after app restart
* Add ui test for login with bad pass phrase

close #471
close #465
issue #439 // tom

----------------------------------

**Tests**:
- Added UI Tests
--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

**Review by Kharchevskyi — COMMENTED** [review]
lgtm

File: FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift [hunk 1]
```diff
@@ -51,17 +51,20 @@ extension Imap: BackupProvider {
...
                 return parts.map { part in AttContext(path: msgContext.path, msg: msgContext.msg, part: part) }
             }
 
+            // in case there are no attachments return empty data
             guard attContext.isNotEmpty else {
-                throw BackupError.missedAttributes
+                return Data()
             }
 
             let dataArr = try attContext.map { attContext -> Data in
```
Comment (tomholub) [inline FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift:70]: I suppose on the line below `fetchMsgAttribute` should be called `fetchMsgAttachment`. Also above, for clarity, rename `attContext` to `attachmentContext`. I'll make a separate issue.

File: FlowCryptUITests/SignInImapTest.swift [hunk 2]
```diff
@@ -43,6 +40,102 @@ extension SignInImapTest {
...
+        application.buttons["+"].tap()
+        
+        wait(0.3)
+        
+        application.typeText("ElonMusk@gmail.com")
+        application.tables.textFields["Subject"].tap()
+        wait(3)
+        application.tables.textFields["Subject"].tap()
+        
+        application.typeText("SpaceX")
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:57]: Our source code is public, this should be changed to something neutral.

File: FlowCryptUITests/SignInImapTest.swift [hunk 3]
```diff
@@ -43,6 +40,102 @@ extension SignInImapTest {
...
+        
+        snapshot("compose")
+        application.navigationBars.buttons["arrow left c"].tap()
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:60]: Is this a back button?

File: FlowCryptUITests/SignInImapTest.swift [hunk 4]
```diff
@@ -43,6 +40,102 @@ extension SignInImapTest {
...
+    // login -> no messages
+    func test_5_login_no_messages() {
+        verifyFlowWithNoBackups(for: .imapDen)
+    }
+
+    func test_6_has_msgs_no_backups() {
+        verifyFlowWithNoBackups(for: .imapHasMessagesNoBackups)
+        
+        
+
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:117]: Unnecessary empty lines

File: FlowCryptUITests/SignInImapTest.swift [hunk 5]
```diff
@@ -43,6 +40,102 @@ extension SignInImapTest {
...
+        
+                
+    }
+    
+    // login with wrong pass phrase
+    func test_7_login_bad_pass_phrase() {
+        let user = UserCredentials.imapDev
+        loginWithImap(user)
+        
+
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:125]: Is there a way to set maximum one empty line in our linter?

File: FlowCryptUITests/SignInImapTest.swift [hunk 6]
```diff
@@ -43,6 +40,102 @@ extension SignInImapTest {
...
+        
+        let tablesQuery = app.tables
+        XCTAssert(tablesQuery.staticTexts["Remember pass phrase temporarily"].exists)
+        
+        passPhraseTextField.typeText(user.pass + "wrong")
+        tapOnGoButton()
+        wait(2)
+        
+        let errorAlert = app.alerts["Error"]
+        XCTAssert(errorAlert.exists, "Error alert is missing after entering wrong pass phrase")
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:134]: You should check that the message of the alert is what you expected. There could be other alerts.

File: FlowCryptUITests/SignInImapTest.swift [hunk 7]
```diff
@@ -100,28 +193,52 @@ extension SignInImapTest {
...
+        importMyKeyButton.tap()
+        navigationBackButton.tap()
+        
+        createNewKeyButton.tap()
+        navigationBackButton.tap()
+        
+        importMyKeyButton.tap()
+        
+        let loadFromFileButton = tablesQuery.buttons["Load From File"]
+        XCTAssert(loadFromFileButton.exists)
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:220]: We should have a test where we import a key from file, proceed with setup, and decrypt an encrypted message that was in inbox encrypted for that key.

File: FlowCryptUITests/SignInImapTest.swift [hunk 8]
```diff
@@ -100,28 +193,52 @@ extension SignInImapTest {
...
+        
+        let loadFromClipboard = tablesQuery.buttons["Load From Clipboard"]
+        XCTAssert(loadFromClipboard.exists)
+        navigationBackButton.tap()
```
Comment (tomholub) [inline FlowCryptUITests/SignInImapTest.swift:224]: We should have a test where we import a key from clipboard, proceed with setup, and decrypt an encrypted message that was in inbox encrypted for that key.

File: FlowCryptUITests/SignInImapTest.swift (hunk 2 above)
Comment (tomholub) [reply FlowCryptUITests/SignInImapTest.swift:57]: Also, whenever possible, test emails should either used `.test` TLD, or `example.com` domain, so that we don't accidentally send email to an actual email server during tests.

**Comment by tomholub** [comment]
It doesn't seem this closes https://github.com/FlowCrypt/flowcrypt-ios/issues/439 yet - can you confirm? There are still tests left commented - the ones that edit state on IMAP.

File: FlowCryptUITests/SignInImapTest.swift (hunk 5 above)
Comment (Kharchevskyi) [reply FlowCryptUITests/SignInImapTest.swift:125]: We have this autocorrect rule, need to apply it to test target as well

Comment (Kharchevskyi) [reply FlowCryptUITests/SignInImapTest.swift]: created a separate issue for this

File: FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift (hunk 1 above)
Comment (Kharchevskyi) [reply FlowCrypt/Functionality/Mail Provider/Backup Provider/Imap+Backup.swift]: fixed in scope of this PR

**Comment by Kharchevskyi** [comment]
I reenabled only tests which doesn't change state on Imap server.

**Comment by tomholub** [comment]
> I reenabled only tests which doesn't change state on Imap server.

Good - please update the PR description so that it doesn't close #439 since there will be more tests to re-enable later, once we figure out how to run them without messing up the IMAP server data.

**Comment by Kharchevskyi** [comment]
This is just a mention, it will not close the issue. Removed to be 100% sure

**Comment by tomholub** [comment]
I must have overlooked earlier. I just put the mention back.

**Review by tomholub — APPROVED** [review]
