### PR TITLE
Couldn't parse org rules

### LINKED ISSUE #408: couldn't parse data while fetching organizational rules
I have an email on nvimp.com domain. With this, the app will attempt fetching rules from https://fes.nvimp.com/api/ and fail, because there is no FES running there.

Most customers will not run our server software on their domain, therefore this is an expected / normal scenario and the app should continue working.

Follow this logic when calling FES first time to determine if it's running or not in `getActiveFesUrl`:

```
call `https://fes.<domain>/api/`, process the response:
  -> did I receive a response and it's status 200, it's a JSON and has the right service value? -> use FES
  -> did I receive a response and it's status 404? -> don't use FES  
  -> did I receive a response and it's other status 4xx or 5xx? -> show error to user
  -> did I NOT receive a response (server down or timeout) and the internet is otherwise working? -> don't use FES
  -> did I NOT receive a response (server down or timeout) and the internet is not working? -> show error to user
```

That means if I call `https://fes.nvimp.com/api/` and the server is down, but internet is working, then this user does not use FES.

### PR DESCRIPTION
**Pull request by ekievsky**
This PR tolerates not found, timeout, service unavailable errors in EnterpriseService;

close #408

----------------------------------

**Tests**:
- Does not need tests 

--------------------------------

### To be filled by reviewers

I have reviewed that this PR... _(tick whichever items you personally focused on during this review)_:
- [x] addresses the issue it closes (if any)
- [x] code is readable and understandable
- [x] is accompanied with tests, or tests are not needed
- [x] is free of vulnerabilities
- [x] is documented clearly and usefully, or doesn't need documentation

### CODE REVIEW

File: FlowCrypt/Functionality/Services/EnterpriseServerApi.swift [hunk 1]
```diff
@@ -32,6 +32,9 @@ extension EnterpriseServerApiError: LocalizedError {
 class EnterpriseServerApi: EnterpriseServerApiType {
 
     private enum Constants {
+        /// 404 - Not Found, -1001 - request timed out, 503 - service unavailable
+        static let getToleratedStatuses = [404, -1001, 503]
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/EnterpriseServerApi.swift:36]: Please strictly follow this decision chart:

```
call https://fes.<domain>/api/, process the response:
-> did I receive a response and it's status 200, it's a JSON and has the right service value? -> use FES to grab OrgRules
-> did I receive a response and it's status 404? -> don't use FES -> empty OrgRules
-> did I receive a response and it's other status 4xx or 5xx? -> show error to user
-> did I NOT receive a response (server down or timeout) and the internet is otherwise working? -> don't use FES, empty OrgRules
-> did I NOT receive a response (server down or timeout) and the internet is not working? -> show error to user
```

503 falls under `did I receive a response and it's other status 4xx or 5xx? -> show error to user`

File: FlowCrypt/Functionality/Services/EnterpriseServerApi.swift [hunk 2]
```diff
@@ -99,12 +114,24 @@ class EnterpriseServerApi: EnterpriseServerApiType {
...
+                )
+            ) else {
+                reject(EnterpriseServerApiError.parse)
+                return
+            }
+
+            if Constants.getToleratedStatuses.contains(safeReponse.status) {
+                resolve(.empty)
+            }
+
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/EnterpriseServerApi.swift:130]: We should only tolerate the error scenarios when calling `https://fes.<domain>/api/` endpoint specifically, because at that point we don't know if there is any server running there or not.

Don't tolerate any errors when calling `https://fes.\(userDomain)/api/v1/client-configuration` or any other APIs, because once we are calling those, we know that there was supposed to be FES running there (based o successful `https://fes.<domain>/api/` response earlier)

**Review by tomholub — CHANGES_REQUESTED** [review]
> -> did I receive a response and it's other status 4xx or 5xx? -> show error to user

Where was this implemented?

> -> did I NOT receive a response (server down or timeout) and the internet is otherwise working? -> don't use FES, empty OrgRules

Where was this implemented?

> -> did I NOT receive a response (server down or timeout) and the internet is not working? -> show error to user

Where was this implemented?

---------

This PR only addresses 20% of the requirements that were clearly laid out in the issue. If the PR addresses less then all requirements of an issue, you must clearly highlight which parts you addressed, and don't `close` the issue in the PR description.

File: FlowCrypt/Functionality/Services/EnterpriseServerApi.swift (hunk 1 above)
Comment (ekievsky) [reply FlowCrypt/Functionality/Services/EnterpriseServerApi.swift:36]: so how may I understand if `server down`?

Comment (tomholub) [reply FlowCrypt/Functionality/Services/EnterpriseServerApi.swift:36]: In Swift, I'm not sure. But generally, it should fail right away, typically with unknown host:

```
$ curl https://unknownnonexistingserver.com
curl: (6) Could not resolve host: unknownnonexistingserver.com
```

Comment (tomholub) [reply FlowCrypt/Functionality/Services/EnterpriseServerApi.swift:36]: I'm not sure if one can differentiate `server down` from `timeout`. Most servers that are not there, if I try to curl them, I'm getting a timeout. I think that it would be possible to get a response that says "nothing is running here" but I'm not sure what that would look like.

Anyway, 503 counts as 4xx and 5xx, the only tolerated http status, other than 200, is 404.

To summarize:
 - 503 counts as 5xx
 - for now we can assume that `server down` is the same as timeout
 - need to ensure that "could not resolve host" is also handled

File: FlowCrypt/Functionality/Services/EnterpriseServerApi.swift [hunk 3]
```diff
@@ -32,7 +32,11 @@ extension EnterpriseServerApiError: LocalizedError {
 class EnterpriseServerApi: EnterpriseServerApiType {
 
     private enum Constants {
-        static let getActiveFesTimeout: TimeInterval = 4
+        /// 404 - Not Found
+        static let getToleratedHTTPStatuses = [404]
+        /// -1001 - request timed out, -1003 - сannot resolve host
+        static let getToleratedNSErrorCodes = [-1001, -1003]
+        static let getActiveFesTimeout: TimeInterval = 100
```
Comment (tomholub) [inline FlowCrypt/Functionality/Services/EnterpriseServerApi.swift:39]: Also, what is the number 100 here, 100 seconds? Milliseconds?

Comment (ekievsky) [reply FlowCrypt/Functionality/Services/EnterpriseServerApi.swift]: for some reason my lates commit wasn't included :/

**Review by tomholub — APPROVED** [review]

**Review by tomholub — APPROVED** [review]
